<?php

namespace App\Services;

use Illuminate\Support\Facades\Route;
use LogicException;

/** Generates the checked-in endpoint catalogue used by the current ES-module client. */
class JavascriptClientServicesGenerator
{
    public function generateModule(): string
    {
        $endpoints = [];
        foreach (Route::getRoutes() as $route) {
            $name = $route->getName();
            $entryRoutes = ['user.login' => 'loginUser', 'nation.store' => 'storeNation'];
            if (!$name || (!str_starts_with($name, 'ajax.') && !isset($entryRoutes[$name]))) continue;

            $method = in_array('GET', $route->methods()) ? 'GET' : (in_array('PUT', $route->methods()) ? 'PUT' : 'POST');
            if (!in_array($method, $route->methods())) {
                throw new LogicException("Unsupported generated route: $name");
            }
            $key = $entryRoutes[$name] ?? \Illuminate\Support\Str::camel(substr($name, 5));
            $endpoints[$key] = ['method' => $method, 'path' => '/' . $route->uri()];
            if ($name === 'ajax.get-asset-info') {
                // Callers supply a raw URI. PHP and the web server decode the route value twice.
                $endpoints[$key]['doubleEncodedParams'] = ['encodedUri'];
            }
        }
        ksort($endpoints);
        $encode = fn ($value) => json_encode(
            $value,
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR,
        );
        return "// Generated by php8.3 artisan client:generate. Do not edit. No player data.\n"
            . 'export const endpoints = ' . $encode($endpoints) . ";\n";
    }
}
