<?php

namespace App\Services;

use App\Facades\ImageProcessing;
use App\Facades\ImageProcessingError;
use App\Http\Controllers\CreateNationUiRequest;
use App\Models\Nation;
use App\Models\NewNation;
use App\Models\NationWithSameNameAlreadyExists;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

/** Full-form and JSON callers share the same operation. Pending identity is recoverable. */
class NationCreationService
{
    public function create(CreateNationUiRequest $request, LoggedInGameContext $context): Nation
    {
        $game = $context->getGame();
        $user = $context->getUser();
        return Cache::lock("entry-nation-{$game->getId()}", 60)->block(3, function () use ($request, $game, $user) {
            if (Nation::getForUserOrNull($game, $user)) abort(409, __('entry.already_created'));
            $pending = NewNation::getForUserOrNull($game, $user);
            if (!$pending) {
                $pending = NewNation::tryCreate($game, $user, $request->nation_name);
                if ($pending instanceof NationWithSameNameAlreadyExists) {
                    throw ValidationException::withMessages(['nation_name' => __('entry.name_taken')]);
                }
            } else $pending->rename($request->nation_name);
            $written = [];
            try {
                $images = [];
                foreach ([['nation_flag', 300, 200], ['leader_picture', 200, 400]] as [$field, $width, $height]) {
                    $file = $request->file($field);
                    $images[$field] = null;
                    if (!$file) continue;
                    $destination = 'var/entry-' . Str::uuid() . '.png';
                    $written[] = public_path($destination);
                    $result = ImageProcessing::cropFitToPublicImage($file, $width, $height, $destination);
                    if ($result instanceof ImageProcessingError) {
                        throw ValidationException::withMessages([$field => __('entry.image_failed')]);
                    }
                    $images[$field] = $result;
                }
                return $pending->finishSetup(
                    homeTerritoryIds: $request->territory_ids,
                    leaderName: $request->leader_name,
                    flagSrc: $images['nation_flag'],
                    formalName: $request->nation_formal_name ?: null,
                    leaderTitleOrNull: $request->leader_title ?: null,
                    leaderPictureSrcOrNull: $images['leader_picture'],
                    primaryColorId: $request->filled('primary_color_id') ? $request->integer('primary_color_id') : null,
                    secondaryColorId: $request->filled('secondary_color_id') ? $request->integer('secondary_color_id') : null,
                );
            } catch (\Throwable $error) {
                // Only remove files generated by this failed invocation, never supplied/existing assets.
                foreach ($written as $file) if (is_file($file)) unlink($file);
                throw $error;
            }
        });
    }
}
