const pairs = {
    currentEmblem: ['Current emblem composition', 'Composition d’emblème actuelle'],
    emblemColor: ['Emblem colour', 'Couleur de l’emblème'],
    width: ['Width', 'Largeur'],
    height: ['Height', 'Hauteur'],
    title: ['Identity Lab', 'Laboratoire d’identité'],
    eyebrow: ['NOVUS ORDO · EXPERIMENTS', 'NOVUS ORDO · EXPÉRIENCES'],
    description: [
        'Choose a pattern, try new colours or add an emblem. Drag a shape to refine your flag.',
        'Choisissez un motif, essayez des couleurs ou ajoutez un emblème. Déplacez une forme pour affiner le drapeau.',
    ],
    flagTab: ['Flag Editor', 'Éditeur de drapeaux'],
    emblemTab: ['Emblem Editor · Later', 'Éditeur d’emblèmes · Plus tard'],
    armsTab: ['Coat of Arms Editor · Later', 'Éditeur d’armoiries · Plus tard'],
    tabs: ['Identity editors', 'Éditeurs d’identité'],
    tools: ['Tools & experiments', 'Outils et expériences'],
    language: ['Language', 'Langue'],
    preview: ['Your flag', 'Votre drapeau'],
    dimensions: ['3:2 · 900 × 600 PNG', '3:2 · PNG 900 × 600'],
    baseline: ['Solid colour', 'Couleur unie'],
    small: ['At 48 × 32', 'À 48 × 32'],
    baselineHelp: [
        'The same primary colour, before adding a composition.',
        'La même couleur principale, avant d’ajouter une composition.',
    ],
    palette: ['Palette', 'Palette'],
    primary: ['Primary', 'Principale'],
    secondary: ['Secondary', 'Secondaire'],
    supporting: ['Supporting', 'Complémentaire'],
    samples: ['Try alternatives', 'Essayer des variantes'],
    triband: ['Broad triband', 'Trois bandes'],
    nordic: ['Offset cross', 'Croix décalée'],
    union: ['Layered crosses', 'Croix superposées'],
    canton: ['Canton & star', 'Canton et étoile'],
    sunrise: ['Diagonal & sun', 'Diagonale et soleil'],
    pall: ['Three-way divide', 'Division en Y'],
    layers: ['Layers', 'Calques'],
    layer: ['Selected layer', 'Calque sélectionné'],
    color: ['Layer colour', 'Couleur du calque'],
    custom: ['Custom', 'Personnalisée'],
    customColor: ['Custom colour', 'Couleur personnalisée'],
    x: ['Horizontal position', 'Position horizontale'],
    y: ['Vertical position', 'Position verticale'],
    scale: ['Scale', 'Échelle'],
    rotation: ['Rotation', 'Rotation'],
    visible: ['Show this layer', 'Afficher ce calque'],
    flip: ['Mirror horizontally', 'Miroir horizontal'],
    front: ['Move forward', 'Avancer'],
    back: ['Move backward', 'Reculer'],
    undo: ['Undo', 'Annuler'],
    redo: ['Redo', 'Rétablir'],
    name: ['Design name', 'Nom du drapeau'],
    exportPng: ['Export PNG', 'Exporter le PNG'],
    exportJson: ['Export recipe', 'Exporter la recette'],
    importJson: ['Import a recipe', 'Importer une recette'],
    fileHelp: ['Flag recipe JSON · maximum 500 KB.', 'Recette de drapeau JSON · 500 Ko maximum.'],
    ready: ['Try a randomizer or choose a pattern.', 'Essayez une option aléatoire ou choisissez un motif.'],
    edited: [
        'Design updated. Save or export to keep your changes.',
        'Drapeau modifié. Enregistrez-le ou exportez-le pour conserver les changements.',
    ],
    imported: [
        'Recipe restored. You can continue editing.',
        'Recette restaurée. Vous pouvez continuer à la modifier.',
    ],
    exported: [
        'Download prepared from the current design.',
        'Téléchargement préparé à partir du drapeau actuel.',
    ],
    invalidRecipe: [
        'This recipe is invalid. Your current flag was kept.',
        'Cette recette est invalide. Votre drapeau a été conservé.',
    ],
    unsupportedVersion: [
        'This recipe needs a different renderer or artwork library. Your flag was kept.',
        'Cette recette nécessite une autre version du moteur ou des formes. Votre drapeau a été conservé.',
    ],
    tooLarge: [
        'Choose a JSON recipe no larger than 500 KB. Your flag was kept.',
        'Choisissez une recette JSON de 500 Ko maximum. Votre drapeau a été conservé.',
    ],
    stale: [
        'Import cancelled because you edited or selected a newer design.',
        'Import annulé : vous avez modifié ou choisi un drapeau plus récent.',
    ],
    failed: [
        'The operation failed. Your current flag was kept.',
        'L’opération a échoué. Votre drapeau a été conservé.',
    ],
    empty: ['This flag has no additional layers.', 'Ce drapeau n’a aucun calque supplémentaire.'],
    details: ['Recipe details', 'Détails de la recette'],
    'Lower field': ['Lower field', 'Champ inférieur'],
    'Middle band': ['Middle band', 'Bande centrale'],
    'Horizontal border': ['Horizontal border', 'Bordure horizontale'],
    'Vertical border': ['Vertical border', 'Bordure verticale'],
    'Horizontal cross': ['Horizontal cross', 'Croix horizontale'],
    'Vertical cross': ['Vertical cross', 'Croix verticale'],
    'Descending diagonal border': ['Descending diagonal border', 'Bordure diagonale descendante'],
    'Ascending diagonal border': ['Ascending diagonal border', 'Bordure diagonale montante'],
    'Descending diagonal': ['Descending diagonal', 'Diagonale descendante'],
    'Ascending diagonal': ['Ascending diagonal', 'Diagonale montante'],
    'Stripe 1': ['Stripe 1', 'Bande 1'],
    'Stripe 2': ['Stripe 2', 'Bande 2'],
    'Stripe 3': ['Stripe 3', 'Bande 3'],
    Canton: ['Canton', 'Canton'],
    'Canton star': ['Canton star', 'Étoile du canton'],
    'Lower diagonal field': ['Lower diagonal field', 'Champ diagonal inférieur'],
    'Diagonal border': ['Diagonal border', 'Bordure diagonale'],
    Sun: ['Sun', 'Soleil'],
    'Upper field': ['Upper field', 'Champ supérieur'],
    'Upper branch': ['Upper branch', 'Branche supérieure'],
    'Lower branch': ['Lower branch', 'Branche inférieure'],
    'Fly band': ['Fly band', 'Bande extérieure'],
    'Upper branch border': ['Upper branch border', 'Bordure supérieure'],
    'Lower branch border': ['Lower branch border', 'Bordure inférieure'],
    'Fly band border': ['Fly band border', 'Bordure extérieure'],
    pattern: ['Pattern', 'Motif'],
    emblem: ['Flag emblem', 'Emblème du drapeau'],
    symbol: ['Symbol', 'Symbole'],
    noEmblem: ['No emblem', 'Sans emblème'],
    browseSymbols: ['Browse symbols & import SVG', 'Parcourir les symboles et importer un SVG'],
    randomShapes: ['Randomize shapes', 'Formes aléatoires'],
    randomColors: ['Randomize colours', 'Couleurs aléatoires'],
    randomEmblem: ['Randomize emblem', 'Emblème aléatoire'],
    paletteHelp: [
        'Randomize colours finds a matching palette. You can adjust any colour.',
        'L’option aléatoire propose des couleurs assorties. Vous pouvez modifier chaque couleur.',
    ],
    advanced: ['Advanced · edit individual layers', 'Avancé · modifier les calques'],
    refine: ['Fine adjustments', 'Ajustements précis'],
    dragHelp: [
        'Drag a shape to move it. Arrow keys nudge the selected layer; Shift moves by 10.',
        'Déplacez une forme avec la souris. Les flèches déplacent le calque sélectionné ; Maj multiplie le pas par 10.',
    ],
    variation: ['Variation', 'Variante'],
    generate: ['Six more ideas', 'Six autres idées'],
    generationOptions: ['Generation options', 'Options de génération'],
    seed: ['Seed', 'Graine'],
    repeatGeneration: ['Generate with this seed', 'Générer avec cette graine'],
    lockPalette: ['Keep colours', 'Garder les couleurs'],
    lockShapes: ['Keep shapes', 'Garder les formes'],
    lockEmblem: ['Keep emblem & placement', 'Garder l’emblème et sa position'],
    keep: ['Keep this flag', 'Conserver ce drapeau'],
    importExportHelp: [
        'Import a recipe & file information',
        'Importer une recette et informations sur les fichiers',
    ],
    archiveHelp: [
        'Keep both downloads: PNG preserves the finished image; JSON lets you edit it later. Designs stay in this Lab.',
        'Conservez les deux fichiers : le PNG préserve l’image finale ; le JSON permet de la modifier. Les drapeaux restent dans ce laboratoire.',
    ],
    importSvg: ['Import SVG symbol', 'Importer un symbole SVG'],
    svgHelp: [
        'Single-colour SVG, up to 100 KB: plain paths, shapes and groups. No styles, text, gradients, masks, references or images. Up to 8 custom symbols per recipe.',
        'SVG monochrome, 100 Ko maximum : tracés, formes et groupes simples. Sans styles, texte, dégradés, masques, références ni images. 8 symboles personnalisés maximum par recette.',
    ],
    invalidSvg: [
        'This SVG uses unsupported content or exceeds the import limits. Use plain paths/shapes without styles, references or effects. Your flag was kept.',
        'Ce SVG utilise du contenu non pris en charge ou dépasse les limites. Utilisez des tracés ou formes simples sans styles, références ni effets. Votre drapeau a été conservé.',
    ],
    assetsFull: [
        'This recipe already contains 8 imported symbols.',
        'Cette recette contient déjà 8 symboles importés.',
    ],
    layersFull: [
        'This flag already has the maximum 64 layers.',
        'Ce drapeau atteint la limite de 64 calques.',
    ],
    save: ['Save study', 'Enregistrer'],
    saveNew: ['Save as new', 'Enregistrer une copie'],
    saved: ['Saved in this browser.', 'Enregistré dans ce navigateur.'],
    unsaved: ['Unsaved changes', 'Modifications non enregistrées'],
    savedEarlier: [
        'The earlier version was saved. Your newer edits are still unsaved.',
        'La version précédente a été enregistrée. Les dernières modifications ne le sont pas encore.',
    ],
    shelf: ['Local studies', 'Études locales'],
    shelfHelp: [
        'Up to 8 studies in this browser, each with its finished PNG and editable recipe. Download backups before clearing browser data.',
        '8 études maximum dans ce navigateur, chacune avec son PNG et sa recette. Téléchargez une sauvegarde avant d’effacer les données du navigateur.',
    ],
    storageLoading: ['Opening local storage…', 'Ouverture du stockage local…'],
    storageFailed: [
        'Local storage is unavailable or the save failed. Export PNG and JSON to keep your design.',
        'Le stockage local est indisponible ou l’enregistrement a échoué. Exportez le PNG et le JSON pour conserver le drapeau.',
    ],
    shelfFull: [
        'Your shelf has 8 studies. Replace a loaded study or remove one first.',
        'Votre collection contient 8 études. Remplacez une étude chargée ou supprimez-en une.',
    ],
    load: ['Edit study', 'Modifier'],
    loaded: ['Saved recipe loaded for editing.', 'Recette enregistrée chargée pour modification.'],
    deleteStudy: ['Remove study', 'Supprimer'],
    removed: ['Study removed from this browser.', 'Étude supprimée de ce navigateur.'],
    untitled: ['Untitled flag', 'Drapeau sans titre'],
    missingImage: ['Saved image unavailable.', 'Image enregistrée indisponible.'],
    savedUnsupported: [
        'This recipe cannot be edited in this version. Its saved PNG is still available.',
        'Cette recette ne peut pas être modifiée avec cette version. Son PNG enregistré reste disponible.',
    ],
    solid: ['Solid field', 'Champ uni'],
    vertical: ['Vertical halves', 'Deux moitiés verticales'],
    horizontal: ['Horizontal halves', 'Deux moitiés horizontales'],
    'vertical-triband': ['Vertical triband', 'Trois bandes verticales'],
    diagonal: ['Diagonal halves', 'Deux moitiés diagonales'],
    'diagonal-band': ['Diagonal band', 'Bande diagonale'],
    saltire: ['Diagonal cross', 'Croix diagonale'],
    quarters: ['Four quarters', 'Quatre quartiers'],
    stripes: ['Horizontal stripes', 'Bandes horizontales'],
    shape: ['New shape', 'Nouvelle forme'],
    addShape: ['Add shape', 'Ajouter la forme'],
    duplicate: ['Duplicate layer', 'Dupliquer le calque'],
    removeLayer: ['Remove layer', 'Supprimer le calque'],
    rect: ['Rectangle', 'Rectangle'],
    ellipse: ['Ellipse', 'Ellipse'],
    triangle: ['Triangle', 'Triangle'],
    diamond: ['Diamond', 'Losange'],
    chevron: ['Chevron', 'Chevron'],
    crescent: ['Crescent', 'Croissant'],
    repeatCount: ['Number of symbols', 'Nombre de symboles'],
    repeatRow: ['Arrange in a row', 'Disposer en ligne'],
    repeatRing: ['Arrange in a ring', 'Disposer en cercle'],
    Star: ['Star', 'Étoile'],
    Crescent: ['Crescent', 'Croissant'],
    Disc: ['Disc', 'Disque'],
    Diamond: ['Diamond', 'Losange'],
    Cross: ['Cross', 'Croix'],
    Lightning: ['Lightning', 'Éclair'],
    Mountain: ['Mountain', 'Montagne'],
    Tree: ['Tree', 'Arbre'],
    Tower: ['Tower', 'Tour'],
    Anchor: ['Anchor', 'Ancre'],
    Wheat: ['Wheat', 'Blé'],
    Bird: ['Bird', 'Oiseau'],
    'Fleur-de-lis': ['Fleur-de-lis', 'Fleur de lys'],
    'Second field': ['Second field', 'Second champ'],
    'Diagonal band': ['Diagonal band', 'Bande diagonale'],
    'First quarter': ['First quarter', 'Premier quartier'],
    'Last quarter': ['Last quarter', 'Dernier quartier'],
    upgraded: [
        'A new editable copy was created. Any saved original is kept.',
        'Une nouvelle copie modifiable a été créée. L’original enregistré est conservé.',
    ],
};
export function translate(locale, key) {
    return pairs[key]?.[locale === 'fr' ? 1 : 0] ?? key;
}
