export default {
    'territory.inspectNation': 'Inspect {name}',
    'territory.noLeader': 'No leader information available.',
    'territory.productivity': 'Productivity details',
    'territory.loyalPopulation': 'Loyal population: {value} million',
    'territory.populationUnknown': 'Loyal population is unknown.',
    'territory.productivityHint':
        'Terrain rate × loyal population (millions) = potential output for each resource. These are separate capacities, not a forecast of simultaneous production.',
    'territory.potential': 'Potential production',
    'forces.selected': 'Selected attack: {attack} · Defense: {defense}',
    'forces.projected': 'Projected defense before battles: {value}',
    'forces.breakdown':
        'Staying {staying} · Incoming {incoming} · Deployments {deployments}. Confirmed orders only. Disbanding units still defend; militia, draft orders and battle outcomes are excluded.',
    'destinations.label': 'Destinations',
    'destinations.games': 'Games',
    'destinations.admin': 'Administration',
    'destinations.tools': 'Tools & experiments',
    'tools.intro': 'Explore the labs. These experiments are separate from your games.',
    'tools.map': 'Map Lab',
    'tools.mapBody': 'Experiment with geography, terrain and map generation.',
    'tools.portrait': 'Portrait Lab',
    'tools.portraitBody': 'Explore portrait composition and rendering.',
    'tools.identity': 'Identity Lab',
    'tools.identityBody': 'Try layered flags, compare colours and export your design.',
    'tools.gallery': 'UI gallery',
    'tools.galleryBody': 'Browse interface components and their different states.',
    'tools.open': 'Open',
    'entry.install': 'First installation',
    'entry.installBody':
        'If no administrator account exists yet, run this command on the server, then sign in with the generated credentials.',
    'hud.tools': 'Tools & experiments',
    'games.watching': 'Spectator',
    'games.title': 'Games',
    'games.game': 'Game {id}',
    'games.intro': 'Choose a world to play in or watch. Each game progresses independently.',
    'games.empty': 'There are no active games yet.',
    'games.playing': 'Your nation is established.',
    'games.unfinished': 'Nation setup is in progress.',
    'games.open': 'Open for a new nation.',
    'games.full': 'No starting homeland available. You can still watch.',
    'games.play': 'Play',
    'games.resume': 'Continue setup',
    'games.join': 'Join as player',
    'games.spectate': 'Spectate',
    'games.pending': 'A command is still pending. Wait for its result before switching games.',
    'games.leave':
        'Leave this game? Unsubmitted changes will be discarded. Any unresolved command may already have reached the server; review the game when you return.',
    'automation.off': 'Auto-ready: off',
    'automation.otherTab': 'Auto-ready is already active in another tab for this nation.',
    'automation.context':
        'Player or turn context changed. Auto-ready is paused; enable it again after review.',
    'automation.countdown': 'Auto-ready: {seconds}s',
    'automation.enable': 'Enable Auto-ready',
    'automation.pause': 'Pause Auto-ready',
    'automation.resume': 'Resume automation',
    'automation.delay': 'Delay before Ready',
    'automation.help':
        'AI players act one by one. Auto-ready only submits your Ready action; it does not manage your nation. Closing this page stops its driver. Turn reports remain available through News.',
    'automation.protected': 'Human protection is on.',
    'automation.unprotected': 'Human protection is off.',
    'automation.manual': 'Manual command: Auto-ready paused.',
    'automation.newGame': 'New game: Auto-ready is off.',
    'automation.drafts': 'Unsaved orders: Auto-ready paused.',
    'automation.stopped': 'Automation stopped. Review the command outcome, refresh, then resume.',
    'automation.serverPaused': 'AI play paused by the server. Inspect and resume in administration.',
    'automation.finished': 'Game finished. Automation stopped.',
    'automation.controlled':
        'This nation is AI-controlled. Release its controller in administration before playing it.',
    'automation.ready': '✓ Ready',
    'automation.planning': 'Planning',
    'command.orderCosts': 'Additional order costs',
    'command.costAvailable': '{resource}: {cost} required · {available} available',
    'command.costShort': 'Short by {amount}',
    'command.costBlocked': 'Not enough resources to send these orders.',
    'command.costRules':
        'Ordinary movement is free. Starting an attack uses the listed costs; existing attack/raid orders are already budgeted. The server validates the final order.',
    'nation.colorUnavailable': 'Choose an available colour from the palette.',
    'nation.colorHelp':
        'Your primary colour is reserved for your nation. Secondary colours may be shared, including black, white and greys.',
    'turnLoading.title': 'A new turn is taking shape…',
    'turnLoading.waiting': 'Waiting for the new turn',
    'turnLoading.message0': 'Growing forests. Please give the trees a moment.',
    'turnLoading.message1': 'Asking the continents to remain reasonably still.',
    'turnLoading.message2': 'Convincing the generals to agree on a direction.',
    'turnLoading.message3': 'Balancing the treasury. Finding additional imbalance.',
    'turnLoading.slow': 'This is taking longer than usual. We’re still waiting for confirmed game data.',
    'turnLoading.failed':
        'We couldn’t load the new turn. Your game controls will unlock once fresh data arrives.',
    'turnLoading.retry': 'Retry loading',
    'planner.title': 'National production planner',
    'planner.open': 'Open production planner',
    'planner.context': 'Turn {turn} · Local forecast',
    'planner.help':
        'All targets compete for the same territorial workers. Automatic food and other upkeep are allocated first; required Capital labour is reserved. Existing bid priorities are preserved, so this is not an equal-share allocation. Remaining workers produce Capital where possible. Forecasts use current facilities and reserves; the server confirms the result when you apply.',
    'planner.hint': 'Set extra output. Upkeep is automatic; unassigned workers produce Capital.',
    'planner.workforce': 'Total labour',
    'planner.automatic': 'Automatic / reserved',
    'planner.discretionary': 'Available for targets',
    'planner.demand': 'Target labour demand',
    'planner.capital': 'Forecast Capital net',
    'planner.production': 'Output · now → forecast',
    'planner.net': 'Forecast net / turn',
    'planner.labor': 'Labour',
    'planner.target': '{resource} extra / turn',
    'planner.slider': '{resource} target slider',
    'planner.targetHelp':
        'Extra output requested after automatic upkeep. Zero disables the extra bid, not essential upkeep. The exact target may exceed capacity; a shortfall means the full target cannot currently be reached.',
    'planner.advanced': 'Advanced · facility cutoffs',
    'planner.cutoff': '{resource} minimum productivity',
    'planner.cutoffHelp':
        'Zero allows any facility. Raising this excludes less productive facilities; it does not improve them. Workers cannot move between territories.',
    'planner.materials': 'Building materials · no current use · target {value}',
    'planner.territories': 'Territorial allocation forecast',
    'planner.territory': 'Territory',
    'planner.resource': 'Resource',
    'planner.productivity': 'Productivity',
    'planner.output': 'Output / turn',
    'planner.apply': 'Apply production plan',
    'planner.reset': 'Discard edits',
    'planner.review': 'Outcome reviewed',
    'planner.shortfall': '{value} below target',
    'planner.shortfallHelp':
        'Not enough eligible capacity or territorial labour remains after automatic upkeep and competing bids. Lower targets or review the advanced cutoffs. National spare labour may be in the wrong territories.',
    'planner.invalid': 'Enter valid, non-negative targets and cutoffs.',
    'planner.unavailable': 'Forecast unavailable. Refresh before applying.',
    'planner.stale': 'Showing previous data. Refresh before applying.',
    'planner.newTurn': 'Turn changed. Previous edits were cleared; review this turn’s plan.',
    'planner.reserves': 'Forecast uses reserves to cover upkeep.',
    'common.help': 'Help',
    'common.helpFor': 'Help: {name}',
    'command.invalidPlacementShort': 'Cannot place here.',
    'command.draftChangedShort': 'Deployment draft needs updating.',
    'command.selection': 'Select',
    'command.appearance': 'Appearance',
    'command.unitStyle': 'Map unit style',
    'command.miniatures': 'Miniatures',
    'command.flat': 'Flat counters',
    'command.paint': 'Paint / uniform',
    'command.accent': 'Aircraft trim',
    'command.brushHelp':
        'Choose a type, then click highlighted territories: one ghost per click. Right-drag to pan. Confirm once; deployments become active next turn.',
    'command.confirmDeployment': 'Confirm deployment',
    'command.undo': 'Undo last',
    'command.clearDraft': 'Clear draft',
    'command.placeFromList': 'Place using a list',
    'command.addPreview': 'Add to preview',
    'command.draftSummary': '{count} ghost units · {territories} territories',
    'command.invalidPlacement':
        'Cannot place here: check ownership, loyalty, shared resources and the 100-unit draft limit.',
    'command.draftChanged':
        'This draft is no longer affordable or eligible. Undo or clear placements before confirming.',
    'command.selectionHelp':
        'Left-drag selects units; Shift adds to selection. Right-drag pans. + means pending deployment; ◇ means unconfirmed preview.',
    'command.militaryMapLabel':
        'Military map. Left-drag selects units, Shift adds, right-drag pans. Scroll to zoom. Arrow keys pan; plus/minus zoom. Use Forces for keyboard unit selection and Deploy for placement.',
    'hud.menu': 'Game menu',
    'hud.navigation': 'Game workspaces',
    'hud.world': 'World',
    'hud.nation': 'Nation',
    'hud.economy': 'Economy',
    'hud.military': 'Military',
    'hud.reports': 'Reports',
    'hud.admin': 'Administration',
    'hud.mapManager': 'Map manager',
    'hud.logout': 'Sign out',
    'hud.resources': 'Resource balances and reserves',
    'hud.ready': 'Ready',
    'hud.waiting': 'Ready ✓',
    'hud.sending': 'Sending…',
    'hud.readyHint': 'Finish this turn. If all nations are ready, the turn advances immediately.',
    'hud.news': 'News',
    'hud.readiness': '{ready}/{total} ready',
    'hud.players': 'Nation readiness',
    'hud.nationId': 'Nation {id}',
    'hud.isReady': 'Ready',
    'hud.planning': 'Planning',
    'hud.deadline': 'Turn deadline: {date}',
    'hud.noDeadline': 'No turn deadline',
    'hud.turnShort': 'turn',
    'hud.reserveShort': 'Res. {value}',
    'hud.notStockedShort': 'No reserve',
    'hud.notStocked': 'Not stockpiled',
    'hud.balance': 'Net balance / turn',
    'hud.reserve': 'Reserve held',
    'hud.production': 'Production',
    'hud.upkeep': 'Consumption / upkeep',
    'hud.expenses': 'Committed to orders',
    'hud.available': 'Available for commands',
    'hud.budgetHint':
        "Balance = production − upkeep − orders. Reserve is held stock, not an extra spending pool. Available is the engine's command limit.",
    'hud.layers': 'Layers · {mode}',
    'hud.collapseMap': 'Collapse minimap',
    'hud.expandMap': 'Expand minimap',
    'hud.continue': 'Continue playing',
    'hud.briefing': 'Turn {turn} · Briefing',
    'hud.growth': 'Nation growth',
    'hud.population': 'Population: {value} ({change})',
    'hud.territories': 'Territories: {value} ({change})',
    'hud.compared':
        'Change since turn {turn}. Includes territorial gains and losses, not just natural growth.',
    'hud.noBaseline': 'No previous nation turn is available for comparison.',
    'hud.noCompleted': 'No completed deployments recorded for the preceding turn.',
    'hud.availableUnits': 'Available to deploy now',
    'hud.retryNews': 'Retry news',
    'hud.staleNews': 'Updating or stale information. Refresh before acting on these figures.',
    'hud.loadingNews': 'Loading turn reports…',
    'hud.failedNews': 'Reports could not be confirmed. Your game remains available; retry the news read.',
    'hud.newsScope':
        "Results from the transition into this turn. Battles show only your nation's engagements.",
    'hud.battles': 'Battle results',
    'hud.won': 'Victory',
    'hud.lost': 'Defeat',
    'hud.draw': 'No victor',
    'hud.neutral': 'Neutral',
    'hud.versus': 'vs',
    'hud.conquered': 'conquered',
    'hud.repelledBy': 'was repelled by',
    'hud.noBattles': "No battles involving your nation in this turn's results.",
    'hud.headlines': 'World headlines',
    'hud.noNews': 'No new headlines.',
    'hud.completed': 'Completed deployments',
    'world.stale': 'Showing the last confirmed state. Refresh required before commands.',
    'command.reviewed': 'I have checked the orders and budget',
    'command.newTurn': 'The turn changed. Previous command drafts were cleared.',
    'command.unitsChanged': 'Some selected units are no longer available; the selection was updated.',
    'command.invalidDraft': 'This draft is no longer valid. Check quantity, availability and destination.',
    'command.invalidDestination': 'Destination no longer available',
    'command.modes': 'Map modes',
    'command.geopolitical': 'Geopolitical',
    'command.military': 'Military',
    'command.economic': 'Economic',
    'command.find': 'Find territory',
    'command.deploy': 'Deploy',
    'command.forces': 'Forces',
    'command.orders': 'Pending orders',
    'command.move': 'Move / attack',
    'command.resources': 'Available resources',
    'command.commands': 'Selection and commands',
    'command.minimap': 'World overview',
    'command.minimapHelp': 'Minimap. Click to navigate; arrow keys pan; Home centers.',
    'command.available': 'Available after commitments',
    'command.close': 'Close',
    'command.noNation': 'Establish a nation before commanding forces.',
    'command.createNation': 'Create a nation',
    'command.loading': 'Reading your forces…',
    'command.retry': 'Try again',
    'command.selectUnits': 'Select the units to command. Selection alone sends no orders.',
    'command.selectAll': 'Select all shown units',
    'command.selectDivision': 'Select division {id}',
    'command.selectGroup': 'Select {count} {unit} units',
    'command.unitGroup': '{count} × {unit}',
    'command.mixedOrders': 'Mixed orders',
    'command.noForces': 'No active units here. New deployments become active next turn.',
    'command.selected': '{count} units selected',
    'command.cancelSelected': 'Cancel selected orders',
    'command.more': 'More actions',
    'command.disband': 'Disband selected units',
    'command.disbandConfirm': 'Order {count} units to disband at the end of turn {turn}?',
    'command.confirm': 'Confirm',
    'command.territoryDetails': 'Territory details',
    'command.deployHelp':
        'Choose a unit, quantity and highlighted owned territory. Deployment becomes active next turn.',
    'command.unitTypes': 'Existing unit types',
    'command.unknownMax': 'Availability unknown — refresh required',
    'command.max': 'Max affordable: {count}',
    'command.badgeLegend': 'Can add · ◇ Preview',
    'command.previewCount': '{count} in preview',
    'command.unitDetails': 'Unit details',
    'command.unitDetailsFor': '{name}: costs and details',
    'command.draftDetails': 'Preview costs and upkeep',
    'command.costShort': 'Cost',
    'command.quantityShort': 'Quantity',
    'command.limitReached': 'No more units available.',
    'command.noEligibleShort': 'No eligible territory.',
    'command.resourceShortage': '{resource}: need {needed}; available after preview {available}.',
    'command.draftFull': 'This preview has reached the limit of 100 units per request.',
    'command.serverLimit':
        'The server-provided deployment limit is exhausted. Availability includes existing commitments and this preview.',
    'command.cancel': 'Cancel',
    'command.cancelGroup': 'Cancel group',
    'command.cancelGroupLabel': 'Cancel group: {name} ({count} units)',
    'command.action.Deploy': 'Deploy',
    'command.action.Move': 'Move',
    'command.action.Attack': 'Attack',
    'command.action.Raid': 'Raid',
    'command.action.Disband': 'Disband',
    'command.quantity': 'Quantity (up to 100 per request)',
    'command.requestDeployment': 'Request deployment',
    'command.deploymentCost': 'Deployment cost',
    'command.upkeep': 'Upkeep per turn',
    'command.attackCost': 'Attack cost per unit',
    'command.unitStats': 'Movement {moves} · Attack {attack} · Defense {defense}',
    'command.noCapture': 'Cannot capture territory.',
    'command.sharedMax':
        'Left: how many more units you can afford after this preview. ◇: units placed in the unconfirmed preview. Maximums share the same resource pool; they cannot all be used independently.',
    'command.unaffordable': 'Insufficient available resources for this unit.',
    'command.noEligible': 'No owned territory currently has sufficient loyalty for deployment.',
    'command.destination': 'Destination territory',
    'command.chooseDestination': 'Choose on the map or here…',
    'command.chooseFromList': 'Choose from a list',
    'command.pickOnMap': 'Choose a destination on the map',
    'command.pickAnother': 'Choose another destination on the map',
    'command.routeSummary': '{reachable} of {count} units can reach {destination}',
    'command.routeDetails': 'Route details',
    'command.routeGroup': '{count} × {route}',
    'command.unreachableGroup': '{count} cannot reach this destination',
    'command.moveHelp':
        'Choose a destination, review the route, then confirm. Foreign destinations use the existing attack/raid rules. The server validates the order.',
    'command.sendOrders': 'Send move / attack orders',
    'command.unreachable': 'No reachable destination selected.',
    'command.direct': 'Direct route (existing coastal transport rules included)',
    'command.noOrders': 'No pending orders',
    'command.pendingHelp': 'These are accepted orders for this turn, not completed actions.',
    'command.cancelDeployment': 'Cancel deployment #{id}',
    'command.cancelOrder': 'Cancel order #{id}',
    'command.submitting': 'Submitting to the game server…',
    'command.none': 'None',
    'command.unit.Infantry': 'Infantry',
    'command.unit.Armored': 'Armored',
    'command.unit.Artillery': 'Artillery',
    'command.unit.Fighter': 'Fighter',
    'command.unit.Bomber': 'Bomber',
    'command.resource.Capital': 'Capital',
    'command.resource.RecruitmentPool': 'Recruitment pool',
    'command.resource.Food': 'Food',
    'command.resource.Material': 'Material',
    'command.resource.Ore': 'Ore',
    'command.resource.Oil': 'Oil',
    'map.beta': 'Experimental map · Beta',
    'map.generate': 'New game map',
    'errors.stale': 'The world changed. Refresh before continuing.',
    'map.navigation': 'Map navigation',
    'map.world': 'World map',
    'terrain.Water': 'Water',
    'terrain.Plain': 'Plain',
    'terrain.River': 'River',
    'terrain.Desert': 'Desert',
    'terrain.Tundra': 'Tundra',
    'terrain.Mountain': 'Mountain',
    'terrain.Forest': 'Forest',
    'world.connecting': 'Connecting…',
    'world.preview': 'Current game · Experimental interface',
    'world.tagline': 'A world in your hands',
    'world.nav': 'Game navigation',
    'world.signOut': 'Sign out',
    'world.loading': 'Loading world data…',
    'world.signedIn': 'Signed in as {name} · World / Browse',
    'world.inspector': 'Territory intelligence',
    'world.dialog': 'Independent inspector',
    'world.opening': 'Opening the world…',
    'world.turn': 'Turn {turn}',
    'world.context': 'Game {game} · {count} nations',
    'world.synced': 'World synchronized · Experimental interface',
    'world.noNation': 'World synchronized · No nation yet',
    'world.create': 'Create your nation',
    'world.syncing': 'Synchronizing world…',
    'world.unavailable': 'World unavailable',
    'world.update': 'A client update is available. Reload this page to load its new files.',
    'world.connection': 'World connection',
    'world.failed': 'Unable to open the world',
    'world.signIn': 'Sign in again',
    'world.survey': 'World survey',
    'world.browse': 'Browse / select',
    'world.yours': 'Your nation',
    'world.others': 'Other nations',
    'world.zoomNames': 'Names appear when zoomed in',
    'world.search': 'Find a territory…',
    'world.directory': 'World directory',
    'world.known': 'The known world',
    'world.territories': 'Territories',
    'world.searchLabel': 'Search territories',
    'world.layers': 'Map layers',
    'world.count': '{count} territories',
    'world.matching': '{count} territories matching your search',
    'world.ownTerritory': 'Your territory',
    'world.noMatches': 'No matching territories.',
    'layer.terrain': 'Terrain',
    'layer.ownership': 'Ownership',
    'layer.borders': 'Borders',
    'layer.detail': 'Map detail',
    'layer.names': 'Territory names',
    'territory.unclaimed': 'Unclaimed territory',
    'territory.nation': 'Nation',
    'territory.noNation': 'Unclaimed',
    'territory.land': 'Usable land',
    'territory.sea': 'Sea access',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.unknown': 'Unknown',
    'territory.production': 'Current production',
    'territory.noProduction': 'No owner production is reported for this territory.',
    'territory.connections': 'Connections & loyalty',
    'territory.connectionCount': '{land} land connections · {total} total connections',
    'territory.loyalty': 'Nation {nation}: {loyalty}',
    'territory.owner': 'Owner information',
    'territory.deploy': 'Deployment permitted by current loyalty.',
    'territory.noDeploy': 'Deployment restricted by current loyalty.',
    'territory.public': 'Public information only. Private owner details are not requested for other nations.',
    'territory.turn': 'Turn {turn} · Read-only inspection',
    'territory.compare': 'Open separate inspector ↗',
    'surface.reading': 'Reading territory…',
    'surface.failed': 'This feature could not be loaded.',
    'surface.reload': 'Reload the interface',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.retry': 'Try again',
    'common.loading': 'Preparing your world…',
    'common.remove': 'Remove',
    'common.optional': 'Optional',
    'common.language': 'Language',
    'common.close': 'Close',
    'common.refresh': 'Refresh',
    'entry.title': 'Novus Ordo · A new beginning',
    'entry.edition': 'A world of nations',
    'entry.footer': 'Every nation begins with a choice.',
    'entry.welcome': 'Welcome back',
    'entry.intro': 'Your next chapter starts here.',
    'entry.login': 'Enter the world',
    'entry.username': 'Username',
    'entry.password': 'Password',
    'entry.signingIn': 'Signing in…',
    'entry.account': 'Use your existing Novus Ordo account.',
    'entry.ready': 'Your nation awaits',
    'entry.readyBody': 'Return to the world and survey your territories.',
    'entry.client': 'Enter the game',
    'entry.admin': 'Administration',
    'entry.founded': 'A nation is born',
    'entry.foundedBody': 'Your homeland is ready. The next chapter is yours.',
    'entry.unavailable': 'The world is not ready',
    'entry.resume':
        'A founding is already underway. Your nation name was recovered; complete the remaining details.',
    'audio.play': 'Enable music',
    'audio.mute': 'Mute music',
    'audio.volume': 'Music volume',
    'audio.blocked': 'Select to play',
    'audio.error': 'Music unavailable',
    'audio.playing': 'Music playing',
    'wizard.identity': 'Identity',
    'wizard.leader': 'Leadership',
    'wizard.homeland': 'Homeland',
    'wizard.review': 'Foundation',
    'wizard.step': 'Chapter {number} of {total}',
    'wizard.progress': 'Nation creation progress',
    'wizard.found': 'Found your nation',
    'wizard.submitting': 'Founding your nation…',
    'wizard.leave': 'Leave nation creation? Your unsaved details will be lost.',
    'nation.identityTitle': 'Give your nation a name',
    'nation.identityBody': 'The first words in your history.',
    'nation.name': 'Nation name',
    'nation.formalName': 'Formal name',
    'nation.flag': 'National flag',
    'nation.namePlaceholder': 'e.g. Aurelian Union',
    'nation.formalPlaceholder': 'e.g. The Republic of Aurelia',
    'nation.leaderTitle': 'Introduce your leader',
    'nation.leaderBody': 'A face and a name to represent your people.',
    'nation.leaderName': 'Leader name',
    'nation.leaderOffice': 'Title',
    'nation.portrait': 'Leader portrait',
    'nation.upload': 'PNG, JPEG or WebP · Up to 2 MB · Maximum 4096 × 4096',
    'nation.chooseImage': 'Choose an image',
    'nation.defaultFlag': 'A flag will be assigned if none is chosen.',
    'nation.homelandTitle': 'Choose where it begins',
    'nation.homelandBody': 'Select {count} available land territories connected to one another.',
    'nation.selected': '{selected} / {total} territories selected',
    'nation.clear': 'Clear selection',
    'nation.search': 'Find a territory',
    'nation.available': 'Available',
    'nation.chosen': 'Selected',
    'nation.unavailable': 'Unavailable',
    'nation.connected': 'Choose a territory adjoining your selection.',
    'nation.noMatches': 'No matching territories.',
    'nation.reviewTitle': 'The foundations are yours',
    'nation.reviewBody': 'Review your choices before founding your nation.',
    'nation.edit': 'Edit {step}',
    'nation.automatic': 'Assigned by the game',
    'nation.none': 'None',
    'nation.territory': 'Territory',
    'nation.resumeSession': 'Your session expired. Sign in again to continue your draft.',
    'nation.reconciling': 'Checking whether your nation was founded…',
    'nation.uncertain': 'The result could not be confirmed. Check the server before trying again.',
    'nation.recovered':
        'No completed nation was found. Your details are preserved; review and submit when ready.',
    'errors.validation': 'Please check the highlighted fields.',
    'errors.required': 'This field is required.',
    'errors.length': 'Use between {min} and {max} characters.',
    'errors.image': 'Choose a PNG, JPEG or WebP image up to 2 MB.',
    'errors.territories': 'Choose {count} available, connected territories.',
    'errors.network': 'Unable to reach the server. Check your connection and try again.',
    'errors.session': 'Your session changed or expired. Please sign in again.',
    'errors.forbidden': 'You do not have access to this action.',
    'errors.unavailable': 'The world is unavailable or advancing a turn. Please try again shortly.',
    'errors.conflict': 'The world has changed. Refresh before continuing.',
    'errors.server': 'The server could not complete this request.',
    'errors.malformed': 'The server returned an unreadable response.',
    'errors.not-found': 'This information is no longer available.',
    'errors.abort': 'Request cancelled.',
    'errors.unknown': 'Something went wrong. Please try again.',
    'errors.notEnough': 'There are not enough free home territories. Please try again later.',
    'map.label':
        'World map. Drag to pan; scroll to zoom. Arrow keys pan, plus and minus zoom, Home fits the world. Use the territory list to select.',
    'map.zoom': 'Map zoom',
    'map.zoomIn': 'Zoom in',
    'map.zoomOut': 'Zoom out',
    'layer.rivers': 'Rivers',
    'identity.primary': 'Primary colour',
    'identity.secondary': 'Secondary colour',
    'sound.title': 'Sound feedback',
    'sound.enabled': 'Enable sound',
    'sound.interaction': 'Hover and click sounds',
    'sound.events': 'Unit and game-event sounds',
    'sound.volume': 'Sound volume',
    'sound.hint': 'Silent until enabled. Settings are remembered in this browser.',
    'production.title': 'Production',
    'production.hint':
        'Set a national target, then review which territorial facilities can contribute. Labour remains local to each territory; food, upkeep and other bids are allocated by the engine.',
    'production.labor': 'Reassignable labour across your territories: {value}',
    'production.figures': 'Production {production}/turn · Balance {balance}/turn',
    'production.requested': 'Requested: {requested} · Labour allocated: {labor}',
    'production.automatic': 'Managed automatically by the existing economy rules.',
    'production.quantity': 'Production target per turn',
    'production.quantityHelp': 'Set 0 to turn this bid off. The exact target may exceed current output.',
    'production.productivity': 'Minimum facility productivity',
    'production.productivityHelp':
        'Set 0 to use any facility. Raising this excludes less productive territories; it does not improve them.',
    'production.save': 'Save {resource} bid',
    'production.planOff': 'This bid is off. Saving a target of 0 cancels it for future turns.',
    'production.planReady':
        'Estimated demand is {demand} labour; eligible territories currently show {available} free.',
    'production.planNoTerritories':
        'No current territory has a facility at productivity {productivity} or higher.',
    'production.planCapacityLimited':
        'Target {target} exceeds the eligible territorial facility ceiling of {ceiling}.',
    'production.planLaborLimited':
        'Estimated demand is {demand} labour, while eligible territories currently show {available} free. Existing assignments and the server rebalance decide the result.',
    'production.planDemand': 'Estimated labour demand',
    'production.planAvailable': 'Free local labour now',
    'production.planAllocated': 'Currently allocated here',
    'production.planTerritories': 'Eligible territories',
    'production.planCeiling': 'Facility output ceiling',
    'production.planNote':
        'Local preview only. Food, upkeep and other saved bids can change the final server allocation.',
    'production.territorySummary': '{resource} territory breakdown ({count})',
    'production.territoryRow':
        '{territory}: productivity {productivity} · free labour {available}/{size} · allocated here {allocated} · output ceiling {ceiling} · {state}',
    'production.territoryEligible': 'eligible',
    'production.territoryExcluded': 'excluded by cutoff',
    'production.territoryNone': 'No current territorial facility for this resource.',
    'production.facility':
        '{resource}: capacity {capacity} · productivity {productivity} · labour {allocated} · output {output}',
    'production.private': 'Select your own territory to inspect its production facilities.',
    'map.rotateLeft': 'Rotate map left 15°',
    'map.rotateRight': 'Rotate map right 15°',
    'map.northUp': 'Reset rotation (north up)',
    'map.fit': 'Fit world',
    'map.loading': 'Loading map imagery…',
    'map.failed':
        'Some map imagery could not load. Territory outlines and the list remain available. Reload to retry.',
};
