export default {
    "planner.previousEstimate": "Previous estimate shown; waiting for a valid updated preview.",
    "economy.previousEstimate": "Previous estimate shown; waiting for a valid updated preview.",
    "economy.colourIncome": "+ Receipts / income",
    "economy.colourExpense": "− Spending · borrowing in amber",
    "economy.colourProblem": "Shortfalls / losses",

    "planner.referencePrice": "Reference price · money per unit",
    "planner.lastOutput": "Last season · national output",
    "planner.priority": "Priority (lower first)",
    "planner.priorityHelp": "Lower numbers are served first; civilian demand may take precedence.",
    "planner.metric": "Quantity / cost",
    "planner.lastActual": "Last season · actual",
    "planner.savedEstimate": "Next season · saved plan",
    "planner.draftEstimate": "Next season · draft",
    "planner.effectiveRequest": "Acquisition target incl. reserve policy",
    "planner.publicOutput": "National output · public",
    "planner.privateOutput": "National output · private",
    "planner.publicDelivery": "Government delivery · public output",
    "planner.privateDelivery": "Government delivery · private purchase",
    "planner.purchaseCost": "Private purchase expense · money",
    "planner.deliveryCost": "Public delivery cost basis · money",
    "planner.publicDevelopment": "New public capacity · following season",
    "planner.privateDevelopment": "New private capacity · following season",
    "planner.committed": "Committed to orders",
    "planner.available": "Available now",
    "planner.constraints": "Production constraints observed",
    "planner.noConstraints": "None observed; output also follows demand.",
    "planner.constraint_installed_capacity": "Installed capacity",
    "planner.constraint_workers": "Shared workforce",
    "planner.constraint_working_capital": "Producer operating funds",
    "planner.costHelp": "Public delivery cost is inventory cost, not another bill: operating wages are already in the budget. Short deliveries can also reflect funding and civilian demand. New capacity produces in a later season.",
    "planner.forecastShort": "Est. output",
    "planner.forecastOutput": "Next season · national output estimate",
    "planner.workforce": "Shared workforce",
    "planner.workersUsed": "Workers used · all activities",
    "planner.territoryHelp": "Potential and capacity are output per season, not underground reserves. Workers are shared across sectors. This view uses the saved plan.",
    "planner.potential": "Geographic production potential",
    "planner.capacity": "Installed capacity now",
    "planner.production": "Expected output",
    "planner.development": "Added capacity · following season",
    "planner.government": "Public activity",
    "planner.producer": "Private activity",
    "economy.cashFlows": "Treasury movements",
    "economy.cashFlowsHelp": "Totals include financing and all public programs. Closing treasury = opening treasury + inflows − outflows. Financing below is a detail of these totals, not an additional charge.",
    "economy.financing": "Debt and financing",
    "economy.nationalActivity": "National activity · separate from treasury",
    "economy.nationalActivityHelp": "Earned income includes wages and realized profits. Private investment uses civilian funds; neither is additional treasury revenue or spending.",
    "economy.opening_treasury": "Opening treasury",
    "economy.support_paid": "Income support paid",
    "economy.wages": "Wages earned",
    "economy.realized_profit": "Realized producer profit",
    "economy.fiscal.borrowing": "New borrowing",
    "economy.fiscal.interest_due": "Interest due",
    "economy.fiscal.arrears": "Unpaid interest",
    "economy.fiscal.principal_repaid": "Principal repaid",
    "economy.fiscal.relief": "Debt relief",
    "economy.fiscal.closing_debt": "Closing debt",
    "economy.food_civilian.fulfilled": "Civilian needs fulfilled",
    "economy.food_civilian.unmet": "Unmet civilian needs",

    "planner.governmentStock": "Government stock",
    "economy.payroll_shortfall": "Military pay is short; divisions risk desertion.",
    "economy.military_goods_shortfall": "Military goods are missing; divisions risk desertion.",
    "economy.civilian_shortage": "Civilian needs are not fully supplied.",
    "economy.acquisition_shortfall": "Some requested acquisitions cannot be delivered.",
    "economy.food_government_closing": "Closing government reserve",
    "economy.food_government_opening": "Opening government reserve",
    "economy.treasury_outflows": "Total treasury outflows",
    "economy.treasury_inflows": "Total treasury inflows",
    "economy.private_development": "Private development · civilian funds",
    "economy.public_development": "Public capacity development",
    "economy.government_purchases": "Purchases from private producers",
    "economy.public_operations": "Public operating wages",
    "economy.public_payroll_paid": "Military payroll paid",
    "economy.public_payroll_requested": "Military payroll requested",
    "economy.public_sales": "Public sales receipts",
    "economy.earned_income": "Earned income · national",
    "planner.acquired": "Government delivery",
    "planner.nationalOutput": "National production",
    "planner.spendingLimit": "Spending limit",
    "planner.requestedQuantity": "Requested quantity",
    "economy.title": "Budget & Policies",
    "economy.budget": "Budget",
    "economy.policies": "Policies",
    "economy.outlook": "National outlook",
    "economy.changes": "Next-season choices",
    "economy.review": "Review changes",
    "economy.save": "Save seasonal plan",
    "economy.discard": "Discard draft",
    "economy.keepEditing": "Keep editing",
    "economy.timing": "Policies and acquisitions are saved together for next season. Saving does not mark Ready.",
    "economy.cancelPending": "Cancel the saved pending changes; retain current policies.",
    "economy.inForce": "In force",
    "economy.configurationOnly": "Configuration only: economic effects are not implemented yet.",
    "economy.conflict": "Saved policies changed elsewhere. Discard this draft and review the updated choices.",
    "economy.invalid": "Correct the highlighted values before saving.",
    "economy.unsaved": "Unsaved changes. Review and save to queue them for next season.",
    "economy.calculating": "Estimating the effects of your draft…",
    "economy.pending": "Choices saved for next season. Current policies still apply.",
    "economy.noChanges": "No unsaved changes. Current or saved choices will apply next season.",
    "economy.notEnabled": "Start a new game to use the seasonal economy.",
    "economy.availableCash": "Available treasury",
    "economy.treasury": "Treasury",
    "economy.committed": "Cash committed to orders",
    "economy.debt": "Current debt",
    "economy.credit": "Credit limit",
    "economy.credits": "Credits",
    "economy.lastActual": "Last season · actual",
    "economy.savedEstimate": "Next · saved choices",
    "economy.draftEstimate": "Next · with edits",
    "economy.tax_receipts": "Tax receipts",
    "economy.command_costs": "Orders and deployments",
    "economy.repayment": "Debt principal repaid",
    "economy.military_due": "Military requested",
    "economy.interest_due": "Debt interest",
    "economy.infrastructure_requested": "Infrastructure requested",
    "economy.balance": "Change in treasury",
    "economy.borrowing": "New borrowing needed",
    "economy.closing_debt": "Debt after season",
    "economy.closing_treasury": "Treasury after season",
    "economy.military_paid": "Military funded",
    "economy.agriculture_requested": "Agricultural development requested",
    "economy.agriculture_paid": "Agricultural development funded",
    "economy.agriculture_shortfall": "Agricultural development cannot be fully funded.",
    "economy.food_shortage": "Civilian food needs are unmet: unrest rises and population growth deteriorates.",
    "economy.food_reserve_shortfall": "Reserve shortfall",
    "economy.agriculture": "Agricultural potential developed",
    "economy.foodSecurity": "Food security",
    "economy.foodHelp": "Households purchase food from producers. Public reserve releases can cover unmet needs. Public acquisitions require funding and supply; development helps future seasons.",
    "economy.food_opening": "Opening stock",
    "economy.food_production_requested": "Production requested",
    "economy.food_production": "Expected / actual production",
    "economy.food_civilian_requested": "Civilian consumption required",
    "economy.food_civilian_fulfilled": "Civilian consumption supplied",
    "economy.food_civilian_unmet": "Civilian shortage",
    "economy.food_military_requested": "Military upkeep required",
    "economy.food_reserve_target": "Closing reserve target",
    "economy.food_closing": "Closing stock",
    "economy.infrastructure_paid": "Infrastructure funded",
    "economy.civilian_income": "Total civilian income",
    "economy.income_per_person": "Disposable income / 1M people",
    "economy.infrastructure": "Infrastructure",
    "economy.unrest": "Unrest",
    "economy.informal": "Informal economy",
    "economy.next": "Next season",
    "economy.editEffect": "Effect of edits",
    "economy.territories": "Territorial conditions",
    "economy.territory": "Territory",
    "economy.default": "Debt default: new credit restricted.",
    "economy.military_shortfall": "Military underfunding: divisions risk desertion.",
    "economy.infrastructure_shortfall": "Infrastructure requests cannot be fully funded.",
    "economy.credit_low": "Credit is running low.",
    "economy.forecastHelp": "One conditional estimate uses current ownership, population, orders and reference prices. It is not a guaranteed outcome. Both policy and acquisition drafts are included.",
    "economy.outlookHelp": "Current conditions → estimated next-season results. Effects compare your draft with the saved next-season choices. Infrastructure and reinvestment improve later seasons. Income is a flow, not government cash.",
    "economy.moneyHint": "Spendable treasury after accepted orders. Open Budget & Policies for the seasonal cash forecast.",
    "economy.resources": "Resource production",
    'hud.diplomacy': 'Diplomacy',
    'diplomacy.title': 'Diplomacy',
    'diplomacy.nations': 'Nations',
    'diplomacy.back': 'All nations',
    'diplomacy.proposePeace': 'Offer peace treaty',
    'diplomacy.proposeAlliance': 'Offer alliance',
    'diplomacy.cancelTreaty': 'End treaty',
    'diplomacy.older': 'Older messages',
    'diplomacy.latest': 'Latest messages',
    'diplomacy.send': 'Send message',
    'diplomacy.offerGrant': 'Offer grant',
    'diplomacy.refresh': 'Refresh',
    'diplomacy.review': 'I reviewed the outcome',
    'diplomacy.message': 'Message',
    'diplomacy.resource': 'Resource',
    'diplomacy.amount': 'Amount',
    'diplomacy.grant': 'Send a resource grant',
    'diplomacy.conversation': 'Conversation',
    'diplomacy.unavailable': 'Diplomacy is available to participating nations in new games.',
    'diplomacy.stale': 'Messages could not be refreshed. Showing the last confirmed conversation.',
    'diplomacy.delivery': 'Messages arrive during the turn. This inbox checks about every 20 seconds.',
    'diplomacy.ai':
        'Passive nation: messages may be delivered, but it makes no diplomatic choices and cannot process offers.',
    "diplomacy.available": "Available to grant: {amount}. Government stock after accepted orders.",
    'diplomacy.expires': 'Protection ends at the start of turn {turn}.',
    'diplomacy.cancelConfirm': 'Give notice to {name}? Protection remains until the start of turn {turn}.',
    'diplomacy.giveNotice': 'Give five turns’ notice',
    'diplomacy.system': 'Game notice',
    'diplomacy.turn': 'Turn {turn}',
    'diplomacy.accept': 'Accept',
    'diplomacy.decline': 'Decline',
    'diplomacy.cancel': 'Cancel offer',
    'diplomacy.state.NoRelations': 'No relations',
    'diplomacy.state.War': 'At war',
    'diplomacy.state.Peace': 'Peace treaty',
    'diplomacy.state.Allied': 'Allied',
    'diplomacy.kind.Peace': 'Peace treaty offer',
    'diplomacy.kind.Alliance': 'Alliance offer',
    'diplomacy.status.Pending': 'Pending',
    'diplomacy.status.Accepted': 'Accepted',
    'diplomacy.status.Declined': 'Declined',
    'diplomacy.status.Cancelled': 'Cancelled',
    'diplomacy.status.Invalid': 'No longer valid',
    'diplomacy.reason.insufficient_stock':
        'The sender no longer has enough uncommitted stock. Nothing was transferred.',
    'diplomacy.reason.relationship_changed': 'The diplomatic situation changed.',
    'diplomacy.reason.ai_unsupported': 'This nation is passive and cannot process this offer.',
    'diplomacy.relationshipNotice': 'Relationship changed: {state}.',
    'diplomacy.offerResult': 'Offer #{id}: {status}.',
    'diplomacy.returned': '{count} visiting divisions returned to their own territory.',
    'diplomacy.disbanded':
        '{count} stranded divisions were disbanded because their nation owns no suitable territory.',
    'diplomacy.notice': 'Diplomatic notice',
    'diplomacy.reverted': 'This action was reverted by a turn rollback.',

    'territory.inspectNation': 'Inspect {name}',
    'territory.noLeader': 'No leader information available.',
    'territory.productivity': 'Productivity details',
    'territory.loyalPopulation': 'Loyal population: {value} million',
    'territory.populationUnknown': 'Loyal population is unknown.',
    'territory.productivityHint':
        'Terrain rate × loyal population (millions) = potential output for each resource. These are separate capacities, not a forecast of simultaneous production.',
    'territory.potential': 'Potential production',
    'forces.selected': 'Selected attack: {attack} · Defense: {defense}',
    'forces.projected': 'Projected defense before battles: {value}',
    'forces.breakdown':
        'Staying {staying} · Incoming {incoming} · Deployments {deployments}. Confirmed orders only. Disbanding units still defend; militia, draft orders and battle outcomes are excluded.',
    'destinations.label': 'Destinations',
    'destinations.games': 'Games',
    'destinations.admin': 'Administration',
    'destinations.tools': 'Tools & experiments',
    'tools.intro': 'Explore the labs. These experiments are separate from your games.',
    'tools.map': 'Map Lab',
    'tools.mapBody': 'Experiment with geography, terrain and map generation.',
    'tools.portrait': 'Portrait Lab',
    'tools.portraitBody': 'Explore portrait composition and rendering.',
    'tools.identity': 'Identity Lab',
    'tools.economy': 'Economy Lab',
    'tools.economyBody': 'Test copper prices, civilian demand, military spending and international trade.',
    'tools.identityBody': 'Try layered flags, compare colours and export your design.',
    'tools.gallery': 'UI gallery',
    'tools.galleryBody': 'Browse interface components and their different states.',
    'tools.open': 'Open',
    'entry.install': 'First installation',
    'entry.installBody':
        'If no administrator account exists yet, run this command on the server, then sign in with the generated credentials.',
    'hud.tools': 'Tools & experiments',
    'games.watching': 'Spectator',
    'games.title': 'Games',
    'games.game': 'Game {id}',
    'games.intro': 'Choose a world to play in or watch. Each game progresses independently.',
    'games.empty': 'There are no active games yet.',
    'games.playing': 'Your nation is established.',
    'games.unfinished': 'Nation setup is in progress.',
    'games.open': 'Open for a new nation.',
    'games.full': 'No starting homeland available. You can still watch.',
    'games.play': 'Play',
    'games.resume': 'Continue setup',
    'games.join': 'Join as player',
    'games.spectate': 'Spectate',
    'games.pending': 'A command is still pending. Wait for its result before switching games.',
    'games.leave':
        'Leave this game? Unsubmitted changes will be discarded. Any unresolved command may already have reached the server; review the game when you return.',
    'automation.off': 'Auto-ready: off',
    'automation.otherTab': 'Auto-ready is already active in another tab for this nation.',
    'automation.context':
        'Player or turn context changed. Auto-ready is paused; enable it again after review.',
    'automation.countdown': 'Auto-ready: {seconds}s',
    'automation.enable': 'Enable Auto-ready',
    'automation.pause': 'Pause Auto-ready',
    'automation.resume': 'Resume automation',
    'automation.delay': 'Delay before Ready',
    'automation.help':
        'Passive players become Ready one by one. Auto-ready only submits your Ready action; it does not manage your nation. Closing this page stops its driver.',
    'automation.passive': 'Automated nations are in temporary pass-only mode.',
    'automation.passiveLabel': 'Passive',
    'automation.manual': 'Manual command: Auto-ready paused.',
    'automation.newGame': 'New game: Auto-ready is off.',
    'automation.drafts': 'Unsaved orders: Auto-ready paused.',
    'automation.stopped': 'Automation stopped. Review the command outcome, refresh, then resume.',
    'automation.serverPaused': 'Passive players are paused. Inspect and resume in administration.',
    'automation.finished': 'Game finished. Automation stopped.',
    'automation.controlled':
        'This nation is passive-controlled. Release its controller in administration before playing it.',
    'automation.ready': '✓ Ready',
    'automation.planning': 'Planning',
    'command.orderCosts': 'Additional order costs',
    'command.costAvailable': '{resource}: {cost} required · {available} available',
    'command.costShort': 'Short by {amount}',
    'command.costBlocked': 'Not enough resources to send these orders.',
    'command.costRules':
        'Ordinary movement is free. Starting an attack uses the listed costs; existing attack/raid orders are already budgeted. The server validates the final order.',
    'nation.colorUnavailable': 'Choose an available colour from the palette.',
    'nation.colorHelp':
        'Your primary colour is reserved for your nation. Secondary colours may be shared, including black, white and greys.',
    'turnLoading.title': 'A new turn is taking shape…',
    'turnLoading.waiting': 'Waiting for the new turn',
    'turnLoading.message0': 'Growing forests. Please give the trees a moment.',
    'turnLoading.message1': 'Asking the continents to remain reasonably still.',
    'turnLoading.message2': 'Convincing the generals to agree on a direction.',
    'turnLoading.message3': 'Balancing the treasury. Finding additional imbalance.',
    'turnLoading.message4': 'Teaching the borders to colour inside the lines.',
    'turnLoading.message5': 'Counting potatoes. Recounting the suspicious ones.',
    'turnLoading.message6': 'Untangling the diplomatic handshake.',
    'turnLoading.message7': 'Ironing the flags. Mind the little stars.',
    'turnLoading.message8': 'Looking for the general who borrowed the map.',
    'turnLoading.message9': 'Giving the mountains a pep talk.',
    'turnLoading.message10': 'Checking whether the treasury has a false bottom.',
    'turnLoading.message11': 'Asking the artillery to use its indoor voice.',
    'turnLoading.message12': 'Delivering a strongly worded basket of muffins.',
    'turnLoading.message13': 'Persuading the rivers to stay in their beds.',
    'turnLoading.message14': 'Making room for another grand national ambition.',
    'turnLoading.message15': 'Checking the royal pigeon’s flight plan.',
    'turnLoading.message16': 'Putting the tiny trees back on the map.',
    'turnLoading.message17': 'Finding a bigger hat for the minister of hats.',
    'turnLoading.message18': 'Filing the paperwork under “glorious”.',
    'turnLoading.message19': 'Offering the dice a cup of tea.',
    'turnLoading.message20': 'Explaining that “over there” is not a battle plan.',
    'turnLoading.message21': 'Assembling the committee to name the committee.',
    'turnLoading.message22': 'Checking the grain stores for ambitious mice.',
    'turnLoading.message23': 'Polishing the medals before anyone asks for one.',
    'turnLoading.message24': 'Teaching the cavalry to parallel park.',
    'turnLoading.message25': 'Rehearsing the anthem. The tuba has concerns.',
    'turnLoading.message26': 'Asking the fog to respect national boundaries.',
    'turnLoading.message27': 'Sending the budget a reassuring little wave.',
    'turnLoading.message28': 'Measuring the empire. Please hold the other end.',
    'turnLoading.message29': 'Adding an unnecessarily impressive seal to the treaty.',
    'turnLoading.message30': 'Checking that north is still at the top.',
    'turnLoading.message31': 'Looking for the last militia’s lucky socks.',
    'turnLoading.message32': 'Reminding the admirals that this is a land meeting.',
    'turnLoading.message33': 'Giving the border guards a fresh pot of coffee.',
    'turnLoading.message34': 'Sorting the rumours by dramatic potential.',
    'turnLoading.message35': 'Asking the economists to show their work.',
    'turnLoading.message36': 'Checking the secret passage for a gift shop.',
    'turnLoading.message37': 'Making the national bird pose for its portrait.',
    'turnLoading.message38': 'Issuing tiny helmets to very important messengers.',
    'turnLoading.message39': 'Moving the ceremonial ribbon out of the supply road.',
    'turnLoading.message40': 'Negotiating a ceasefire between two office printers.',
    'turnLoading.message41': 'Checking whether “miscellaneous” can fund an army.',
    'turnLoading.message42': 'Giving every province its moment in the sun.',
    'turnLoading.message43': 'Making sure the parade turns at the right street.',
    'turnLoading.message44': 'Folding the world map along the wrong crease.',
    'turnLoading.message45': 'Asking the castle caretaker where the keys went.',
    'turnLoading.message46': 'Preparing a very official-looking sandwich.',
    'turnLoading.message47': 'Checking the lighthouse. Yes, still a light.',
    'turnLoading.message48': 'Convincing the scouts to draw fewer dragons.',
    'turnLoading.message49': 'Reserving a balcony for the next important speech.',
    'turnLoading.message50': 'Teaching the census takers not to count scarecrows.',
    'turnLoading.message51': 'Asking the supply wagons to form a polite queue.',
    'turnLoading.message52': 'Checking the royal decree for biscuit crumbs.',
    'turnLoading.message53': 'Finding a diplomatic way to say “nice hat”.',
    'turnLoading.message54': 'Putting the economic forecast in a sunnier window.',
    'turnLoading.message55': 'Making sure the neutral sheep remain neutral.',
    'turnLoading.message56': 'Unrolling the red carpet. Removing one stubborn cat.',
    'turnLoading.message57': 'Reminding the generals that the map is not a napkin.',
    'turnLoading.message58': 'Checking the emergency reserve of ceremonial trumpets.',
    'turnLoading.message59': 'Giving history a moment to find its glasses.',
    'turnLoading.failed':
        'We couldn’t load the new turn. Your game controls will unlock once fresh data arrives.',
    'turnLoading.retry': 'Retry loading',
    "planner.foodPolicyManaged": "Food reserves also follow the national reserve policy.",
    "planner.foodReserveTarget": "Reserve target",
    "planner.resourceHint": "Request goods and set spending limits. Save includes policy and acquisition drafts. Deliveries become available after the season; national output is not government stock.",
    'planner.extraQuantity': "Extra output target",
    'planner.minimumProductivity': "Minimum productivity (output per million workers)",
    "planner.closingStock": "Closing government stock",
    'planner.unmetDemand': "Unmet demand",
    'planner.calculating': "Calculating production…",
    "planner.title": "Government acquisitions",
    'planner.open': 'Open acquisition planner',
    'planner.context': 'Turn {turn} · Local forecast',
    'planner.resource': 'Resource',
    'planner.productivity': 'Productivity',
    'planner.output': 'Output / turn',
    "planner.apply": "Save seasonal plan",
    'planner.reset': 'Discard edits',
    'planner.review': 'Outcome reviewed',
    'planner.shortfall': '{value} below target',
    'planner.shortfallHelp':
        'Not enough eligible capacity or territorial labour remains after automatic upkeep and competing bids. Lower targets or review the advanced cutoffs. National spare labour may be in the wrong territories.',
    'planner.invalid': 'Enter valid, non-negative targets and cutoffs.',
    'planner.unavailable': 'Forecast unavailable. Refresh before applying.',
    'planner.stale': 'Showing previous data. Refresh before applying.',
    'planner.newTurn': 'Turn changed. Previous edits were cleared; review this turn’s plan.',
    'planner.reserves': 'Forecast uses reserves to cover upkeep.',
    'common.help': 'Help',
    'common.helpFor': 'Help: {name}',
    'command.invalidPlacementShort': 'Cannot place here.',
    'command.draftChangedShort': 'Deployment draft needs updating.',
    'command.selection': 'Select',
    'command.appearance': 'Appearance',
    'command.unitStyle': 'Map unit style',
    'command.miniatures': 'Miniatures',
    'command.flat': 'Flat counters',
    'command.paint': 'Paint / uniform',
    'command.accent': 'Aircraft trim',
    'command.brushHelp':
        'Choose a type, then click highlighted territories: one ghost per click. Right-drag to pan. Confirm once; deployments become active next turn.',
    'command.confirmDeployment': 'Confirm deployment',
    'command.undo': 'Undo last',
    'command.clearDraft': 'Clear draft',
    'command.placeFromList': 'Place using a list',
    'command.addPreview': 'Add to preview',
    'command.draftSummary': '{count} ghost units · {territories} territories',
    'command.invalidPlacement':
        'Cannot place here: check ownership, loyalty, shared resources and the 100-unit draft limit.',
    'command.draftChanged':
        'This draft is no longer affordable or eligible. Undo or clear placements before confirming.',
    'command.selectionHelp':
        'Left-drag selects units; Shift adds to selection. Right-drag pans. + means pending deployment; ◇ means unconfirmed preview.',
    'command.filterUnits': 'Filter units',
    'command.filterIdle': 'Idle',
    'command.filterGuard': 'Guarding',
    'command.filterHint': 'Click to include only · Shift-click to exclude',
    'command.filterButtonHint': '{name}: click to include only; Shift-click to exclude',
    'command.filterAvailable': 'Filter by {name}',
    'command.filterIncluding': 'Including only {name}',
    'command.filterExcluding': 'Excluding {name}',
    'command.clearFilters': 'Clear unit filters',
    'command.noFilterMatches': 'No units match these filters.',
    'command.selectedShown': '{count} units selected · {shown} shown',
    'command.militaryMapLabel':
        'Military map. Left-drag selects units, Shift adds, right-drag pans. Scroll to zoom. Arrow keys pan; plus/minus zoom. Use Forces for keyboard unit selection and Deploy for placement.',
    'hud.menu': 'Game menu',
    'hud.navigation': 'Game workspaces',
    'hud.world': 'World',
    'hud.nation': 'Nation',
    'hud.economy': "Budget & Policies",
    'hud.military': 'Military',
    'hud.reports': 'Reports',
    'hud.admin': 'Administration',
    'hud.mapManager': 'Map manager',
    'hud.logout': 'Sign out',
    'hud.resources': 'Resource balances and reserves',
    'hud.ready': 'Ready',
    'hud.waiting': 'Ready ✓',
    'hud.sending': 'Sending…',
    'hud.readyHint': 'Finish this turn. If all nations are ready, the turn advances immediately.',
    'hud.news': 'News',
    'hud.readiness': '{ready}/{total} ready',
    'hud.players': 'Nation readiness',
    'hud.nationId': 'Nation {id}',
    'hud.isReady': 'Ready',
    'hud.planning': 'Planning',
    'hud.deadline': 'Turn deadline: {date}',
    'hud.noDeadline': 'No turn deadline',
    'hud.turnShort': 'turn',
    'hud.reserveShort': 'Res. {value}',
    'hud.notStockedShort': 'No reserve',
    'hud.notStocked': 'Not stockpiled',
    'hud.balance': 'Net balance / turn',
    'hud.reserve': 'Reserve held',
    'hud.production': 'Production',
    'hud.upkeep': 'Consumption / upkeep',
    'hud.expenses': 'Committed to orders',
    'hud.available': 'Available for commands',
    'hud.budgetHint':
        "Balance = production − upkeep − orders. Reserve is held stock, not an extra spending pool. Available is the engine's command limit.",
    'hud.collapseMap': 'Collapse minimap',
    'hud.expandMap': 'Expand minimap',
    'hud.continue': 'Continue playing',
    'hud.briefing': 'Turn {turn} · Briefing',
    'hud.growth': 'Nation growth',
    'hud.population': 'Population: {value} ({change})',
    'hud.territories': 'Territories: {value} ({change})',
    'hud.compared':
        'Change since turn {turn}. Includes territorial gains and losses, not just natural growth.',
    'hud.noBaseline': 'No previous nation turn is available for comparison.',
    'hud.noCompleted': 'No completed deployments recorded for the preceding turn.',
    'hud.availableUnits': 'Available to deploy now',
    'hud.retryNews': 'Retry news',
    'hud.staleNews': 'Updating or stale information. Refresh before acting on these figures.',
    'hud.loadingNews': 'Loading turn reports…',
    'hud.failedNews': 'Reports could not be confirmed. Your game remains available; retry the news read.',
    'hud.newsScope':
        "Results from the transition into this turn. Battles show only your nation's engagements.",
    'hud.battles': 'Battle results',
    'hud.won': 'Victory',
    'hud.lost': 'Defeat',
    'hud.draw': 'No victor',
    'hud.neutral': 'Neutral',
    'hud.versus': 'vs',
    'hud.conquered': 'conquered',
    'hud.repelledBy': 'was repelled by',
    'ownership.view': 'View on map',
    'ownership.title': 'Ownership change',
    'ownership.loading': 'Loading ownership snapshots…',
    'ownership.failed': 'These ownership snapshots could not be loaded. Try again.',
    'ownership.before': 'Before · Turn {turn}',
    'ownership.after': 'After · Turn {turn}',
    'ownership.scope': 'Territories changing owner: {count}. All changes are shown together.',
    'ownership.unchanged': 'No territories changed owner between these turn boundaries.',
    'ownership.play': 'Play',
    'ownership.pause': 'Pause',
    'ownership.done': 'Done',
    'ownership.retry': 'Retry',
    'hud.noBattles': "No battles involving your nation in this turn's results.",
    'hud.headlines': 'World headlines',
    'hud.noNews': 'No new headlines.',
    'hud.completed': 'Completed deployments',
    'world.stale': 'Showing the last confirmed state. Refresh required before commands.',
    'command.reviewed': 'I have checked the orders and budget',
    'command.newTurn': 'The turn changed. Previous command drafts were cleared.',
    'command.unitsChanged': 'Some selected units are no longer available; the selection was updated.',
    'command.invalidDraft': 'This draft is no longer valid. Check quantity, availability and destination.',
    'command.invalidDestination': 'Destination no longer available',
    'command.modes': 'Map modes',
    'command.geopolitical': 'Geopolitical',
    'command.military': 'Military',
    'command.economic': 'Economic',
    'command.find': 'Find territory',
    'command.deploy': 'Deploy',
    'command.forces': 'Forces',
    'command.orders': 'Pending orders',
    'command.move': 'Move / attack',
    'command.resources': 'Available resources',
    'command.commands': 'Selection and commands',
    'command.minimap': 'World overview',
    'command.minimapHelp': 'Minimap. Click to navigate; arrow keys pan; Home centers.',
    'command.available': 'Available after commitments',
    'command.close': 'Close',
    'command.noNation': 'Establish a nation before commanding forces.',
    'command.createNation': 'Create a nation',
    'command.loading': 'Reading your forces…',
    'command.retry': 'Try again',
    'command.selectUnits': 'Select the units to command. Selection alone sends no orders.',
    'command.selectAll': 'Select all shown units',
    'command.selectDivision': 'Select division {id}',
    'command.selectGroup': 'Select {count} {unit} units',
    'command.unitGroup': '{count} × {unit}',
    'command.mixedOrders': 'Mixed orders',
    'command.noForces': 'No active units here. New deployments become active next turn.',
    'command.selected': '{count} units selected',
    'command.cancelSelected': 'Cancel selected orders',
    'command.disband': 'Disband selected units',
    'command.disbandConfirm': 'Order {count} units to disband at the end of turn {turn}?',
    'command.guard': 'Guard selected units',
    'command.guardConfirm':
        'Place {count} units on persistent Guard duty? Readiness costs 25% of normal operations; responding brings that turn’s cost to 100%. Releasing them later requires one stand-down turn.',
    'command.defensePotential': 'Potential defence for one attack: {value}',
    'command.defensePotentialBreakdown':
        'Base {base} · Reachable Guard {guard} ({count} units). This assumes this territory is the only one attacked.',
    'command.confirm': 'Confirm',
    'command.territoryDetails': 'Territory details',
    'command.deployHelp':
        'Choose a unit, quantity and highlighted owned territory. Deployment becomes active next turn.',
    'command.unitTypes': 'Existing unit types',
    'command.unknownMax': 'Availability unknown — refresh required',
    'command.max': 'Max affordable: {count}',
    'command.badgeLegend': 'Can add · ◇ Preview',
    'command.previewCount': '{count} in preview',
    'command.unitDetails': 'Unit details',
    'command.unitDetailsFor': '{name}: costs and details',
    'command.draftDetails': 'Preview costs and upkeep',
    'command.costShort': 'Cost',
    'command.quantityShort': 'Quantity',
    'command.limitReached': 'No more units available.',
    'command.noEligibleShort': 'No eligible territory.',
    'command.resourceShortage': '{resource}: need {needed}; available after preview {available}.',
    'command.draftFull': 'This preview has reached the limit of 100 units per request.',
    'command.serverLimit':
        'The server-provided deployment limit is exhausted. Availability includes existing commitments and this preview.',
    'command.cancel': 'Cancel',
    'command.release': 'Release',
    'command.releaseGroup': 'Release group',
    'command.releaseGroupLabel': 'Release Guard group: {name} ({count} units)',
    'command.releaseGuard': 'Release Guard order for division {id}',
    'command.cancelGroup': 'Cancel group',
    'command.cancelGroupLabel': 'Cancel group: {name} ({count} units)',
    'command.action.Deploy': 'Deploy',
    'command.action.Move': 'Move',
    'command.action.Attack': 'Attack',
    'command.action.Raid': 'Raid',
    'command.action.Disband': 'Disband',
    'command.action.Guard': 'Guard',
    'command.action.StandDown': 'Standing down',
    'command.quantity': 'Quantity (up to 100 per request)',
    'command.requestDeployment': 'Request deployment',
    'command.deploymentCost': 'Deployment cost',
    'command.upkeep': 'Upkeep per turn',
    'command.attackCost': 'Attack cost per unit',
    'command.unitStats': 'Movement {moves} · Attack {attack} · Defense {defense}',
    'command.noCapture': 'Cannot capture territory.',
    'command.sharedMax':
        'Left: how many more units you can afford after this preview. ◇: units placed in the unconfirmed preview. Maximums share the same resource pool; they cannot all be used independently.',
    'command.unaffordable': 'Insufficient available resources for this unit.',
    'command.noEligible': 'No owned territory currently has sufficient loyalty for deployment.',
    'command.destination': 'Destination territory',
    'command.chooseDestination': 'Choose on the map or here…',
    'command.chooseFromList': 'Choose from a list',
    'command.pickOnMap': 'Choose a destination on the map',
    'command.pickAnother': 'Choose another destination on the map',
    'command.routeSummary': '{reachable} of {count} units can reach {destination}',
    'command.routeDetails': 'Route details',
    'command.routeGroup': '{count} × {route}',
    'command.unreachableGroup': '{count} cannot reach this destination',
    'command.moveHelp':
        'Choose a destination, review the route, then confirm. Foreign destinations use the existing attack/raid rules. The server validates the order.',
    'command.sendOrders': 'Send move / attack orders',
    'command.unreachable': 'No reachable destination selected.',
    'command.direct': 'Direct route (existing coastal transport rules included)',
    'command.noOrders': 'No pending orders',
    'command.pendingHelp': 'These are accepted orders for this turn, not completed actions.',
    'command.cancelDeployment': 'Cancel deployment #{id}',
    'command.cancelOrder': 'Cancel order #{id}',
    'command.submitting': 'Submitting to the game server…',
    'command.none': 'None',
    'command.unit.Infantry': 'Infantry',
    'command.unit.Armored': 'Armored',
    'command.unit.Artillery': 'Artillery',
    'command.unit.Fighter': 'Fighter',
    'command.unit.Bomber': 'Bomber',
    'command.resource.Capital': 'Capital',
    'command.resource.RecruitmentPool': 'Recruitment pool',
    'command.resource.Food': 'Food',
    'command.resource.Material': 'Material',
    'command.resource.Ore': 'Ore',
    'command.resource.Oil': 'Oil',
    'map.generate': 'New game map',
    'errors.stale': 'The world changed. Refresh before continuing.',
    'map.navigation': 'Map navigation',
    'map.world': 'World map',
    'terrain.Water': 'Water',
    'terrain.Plain': 'Plain',
    'terrain.River': 'River',
    'terrain.Desert': 'Desert',
    'terrain.Tundra': 'Tundra',
    'terrain.Mountain': 'Mountain',
    'terrain.Forest': 'Forest',
    'world.connecting': 'Connecting…',
    'world.preview': 'Current game',
    'world.tagline': 'A world in your hands',
    'world.nav': 'Game navigation',
    'world.signOut': 'Sign out',
    'world.loading': 'Loading world data…',
    'world.signedIn': 'Signed in as {name} · World / Browse',
    'world.inspector': 'Territory intelligence',
    'world.dialog': 'Independent inspector',
    'world.opening': 'Opening the world…',
    'world.turn': 'Turn {turn}',
    'world.context': 'Game {game} · {count} nations',
    'world.synced': 'World synchronized · Experimental interface',
    'world.noNation': 'World synchronized · No nation yet',
    'world.create': 'Create your nation',
    'world.syncing': 'Synchronizing world…',
    'world.unavailable': 'World unavailable',
    'world.update': 'A client update is available. Reload this page to load its new files.',
    'world.connection': 'World connection',
    'world.failed': 'Unable to open the world',
    'world.signIn': 'Sign in again',
    'world.survey': 'World survey',
    'world.browse': 'Browse / select',
    'world.yours': 'Your nation',
    'world.others': 'Other nations',
    'world.zoomNames': 'Names appear when zoomed in',
    'world.search': 'Find a territory…',
    'world.directory': 'World directory',
    'world.known': 'The known world',
    'world.territories': 'Territories',
    'world.searchLabel': 'Search territories',
    'world.count': '{count} territories',
    'world.matching': '{count} territories matching your search',
    'world.ownTerritory': 'Your territory',
    'world.noMatches': 'No matching territories.',
    'territory.unclaimed': 'Unclaimed territory',
    'territory.nation': 'Nation',
    'territory.noNation': 'Unclaimed',
    'territory.land': 'Usable land',
    'territory.sea': 'Sea access',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.unknown': 'Unknown',
    'territory.production': 'Current production',
    'territory.noProduction': 'No owner production is reported for this territory.',
    'territory.connections': 'Connections & loyalty',
    'territory.connectionCount': '{land} land connections · {total} total connections',
    'territory.loyalty': 'Nation {nation}: {loyalty}',
    'territory.owner': 'Owner information',
    'territory.deploy': 'Deployment permitted by current loyalty.',
    'territory.noDeploy': 'Deployment restricted by current loyalty.',
    'territory.public': 'Public information only. Private owner details are not requested for other nations.',
    'territory.turn': 'Turn {turn} · Read-only inspection',
    'territory.compare': 'Open separate inspector ↗',
    'surface.reading': 'Reading territory…',
    'surface.failed': 'This feature could not be loaded.',
    'surface.reload': 'Reload the interface',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.retry': 'Try again',
    'common.loading': 'Preparing your world…',
    'common.remove': 'Remove',
    'common.optional': 'Optional',
    'common.language': 'Language',
    'common.close': 'Close',
    'common.refresh': 'Refresh',
    'entry.title': 'Novus Ordo · A new beginning',
    'entry.edition': 'A world of nations',
    'entry.footer': 'Every nation begins with a choice.',
    'entry.welcome': 'Welcome back',
    'entry.intro': 'Your next chapter starts here.',
    'entry.login': 'Enter the world',
    'entry.username': 'Username',
    'entry.password': 'Password',
    'entry.signingIn': 'Signing in…',
    'entry.account': 'Use your existing Novus Ordo account.',
    'entry.ready': 'Your nation awaits',
    'entry.readyBody': 'Return to the world and survey your territories.',
    'entry.client': 'Enter the game',
    'entry.admin': 'Administration',
    'entry.founded': 'A nation is born',
    'entry.foundedBody': 'Your homeland is ready. The next chapter is yours.',
    'entry.unavailable': 'The world is not ready',
    'entry.resume':
        'A founding is already underway. Your nation name was recovered; complete the remaining details.',
    'audio.play': 'Enable music',
    'audio.mute': 'Mute music',
    'audio.volume': 'Music volume',
    'audio.blocked': 'Select to play',
    'audio.error': 'Music unavailable',
    'audio.playing': 'Music playing',
    'wizard.identity': 'Identity',
    'wizard.leader': 'Leadership',
    'wizard.homeland': 'Homeland',
    'wizard.review': 'Foundation',
    'wizard.step': 'Chapter {number} of {total}',
    'wizard.progress': 'Nation creation progress',
    'wizard.found': 'Found your nation',
    'wizard.submitting': 'Founding your nation…',
    'wizard.leave': 'Leave nation creation? Your unsaved details will be lost.',
    'nation.identityTitle': 'Give your nation a name',
    'nation.identityBody': 'The first words in your history.',
    'nation.name': 'Nation name',
    'nation.formalName': 'Formal name',
    'nation.flag': 'National flag',
    'nation.namePlaceholder': 'e.g. Aurelian Union',
    'nation.formalPlaceholder': 'e.g. The Republic of Aurelia',
    'nation.leaderTitle': 'Introduce your leader',
    'nation.leaderBody': 'A face and a name to represent your people.',
    'nation.leaderName': 'Leader name',
    'nation.leaderOffice': 'Title',
    'nation.portrait': 'Leader portrait',
    'nation.upload': 'PNG, JPEG or WebP · Up to 2 MB · Maximum 4096 × 4096',
    'nation.chooseImage': 'Choose an image',
    'common.cancel': 'Cancel',
    'nation.designFlag': 'Design flag',
    'nation.editFlag': 'Edit flag',
    'nation.useFlag': 'Use this flag',
    'nation.flagEditorFailed': 'The flag editor could not prepare your flag. Please try again.',
    'nation.defaultFlag': 'A flag will be assigned if none is chosen.',
    'nation.homelandTitle': 'Choose where it begins',
    'nation.homelandBody': 'Select {count} available land territories connected to one another.',
    'nation.selected': '{selected} / {total} territories selected',
    'nation.clear': 'Clear selection',
    'nation.search': 'Find a territory',
    'nation.available': 'Available',
    'nation.chosen': 'Selected',
    'nation.unavailable': 'Unavailable',
    'nation.connected': 'Choose a territory adjoining your selection.',
    'nation.noMatches': 'No matching territories.',
    'nation.reviewTitle': 'The foundations are yours',
    'nation.reviewBody': 'Review your choices before founding your nation.',
    'nation.edit': 'Edit {step}',
    'nation.automatic': 'Assigned by the game',
    'nation.none': 'None',
    'nation.territory': 'Territory',
    'nation.resumeSession': 'Your session expired. Sign in again to continue your draft.',
    'nation.reconciling': 'Checking whether your nation was founded…',
    'nation.uncertain': 'The result could not be confirmed. Check the server before trying again.',
    'nation.recovered':
        'No completed nation was found. Your details are preserved; review and submit when ready.',
    'errors.validation': 'Please check the highlighted fields.',
    'errors.required': 'This field is required.',
    'errors.length': 'Use between {min} and {max} characters.',
    'errors.image': 'Choose a PNG, JPEG or WebP image up to 2 MB.',
    'errors.territories': 'Choose {count} available, connected territories.',
    'errors.network': 'Unable to reach the server. Check your connection and try again.',
    'errors.session': 'Your session changed or expired. Please sign in again.',
    'errors.forbidden': 'You do not have access to this action.',
    'errors.unavailable': 'The world is unavailable or advancing a turn. Please try again shortly.',
    'errors.conflict': 'The world has changed. Refresh before continuing.',
    'errors.server': 'The server could not complete this request.',
    'errors.malformed': 'The server returned an unreadable response.',
    'errors.not-found': 'This information is no longer available.',
    'errors.abort': 'Request cancelled.',
    'errors.unknown': 'Something went wrong. Please try again.',
    'errors.notEnough': 'There are not enough free home territories. Please try again later.',
    'map.label':
        'World map. Drag to pan; scroll to zoom. Arrow keys pan, plus and minus zoom, Home fits the world. Use the territory list to select.',
    'map.zoom': 'Map zoom',
    'map.zoomIn': 'Zoom in',
    'map.zoomOut': 'Zoom out',
    'identity.primary': 'Primary colour',
    'identity.secondary': 'Secondary colour',
    'sound.title': 'Sound feedback',
    'sound.enabled': 'Enable sound',
    'sound.interaction': 'Hover and click sounds',
    'sound.events': 'Unit and game-event sounds',
    'sound.volume': 'Sound volume',
    'sound.hint': 'Silent until enabled. Settings are remembered in this browser.',
    'production.title': 'Production',
    'production.hint':
        'Set a national target, then review which territorial facilities can contribute. Labour remains local to each territory; food, upkeep and other bids are allocated by the engine.',
    'production.labor': 'Reassignable labour across your territories: {value}',
    'production.figures': 'Production {production}/turn · Balance {balance}/turn',
    'production.requested': 'Requested: {requested} · Labour allocated: {labor}',
    'production.automatic': 'Managed automatically by the existing economy rules.',
    'production.quantity': 'Production target per turn',
    'production.quantityHelp': 'Set 0 to turn this bid off. The exact target may exceed current output.',
    'production.productivity': 'Minimum facility productivity',
    'production.productivityHelp':
        'Set 0 to use any facility. Raising this excludes less productive territories; it does not improve them.',
    'production.save': 'Save {resource} bid',
    'production.planOff': 'This bid is off. Saving a target of 0 cancels it for future turns.',
    'production.planReady':
        'Estimated demand is {demand} labour; eligible territories currently show {available} free.',
    'production.planNoTerritories':
        'No current territory has a facility at productivity {productivity} or higher.',
    'production.planCapacityLimited':
        'Target {target} exceeds the eligible territorial facility ceiling of {ceiling}.',
    'production.planLaborLimited':
        'Estimated demand is {demand} labour, while eligible territories currently show {available} free. Existing assignments and the server rebalance decide the result.',
    'production.planDemand': 'Estimated labour demand',
    'production.planAvailable': 'Free local labour now',
    'production.planAllocated': 'Currently allocated here',
    'production.planTerritories': 'Eligible territories',
    'production.planCeiling': 'Facility output ceiling',
    'production.planNote':
        'Local preview only. Food, upkeep and other saved bids can change the final server allocation.',
    'production.territorySummary': '{resource} territory breakdown ({count})',
    'production.territoryRow':
        '{territory}: productivity {productivity} · free labour {available}/{size} · allocated here {allocated} · output ceiling {ceiling} · {state}',
    'production.territoryEligible': 'eligible',
    'production.territoryExcluded': 'excluded by cutoff',
    'production.territoryNone': 'No current territorial facility for this resource.',
    'production.facility':
        '{resource}: capacity {capacity} · productivity {productivity} · labour {allocated} · output {output}',
    'production.private': 'Select your own territory to inspect its production facilities.',
    'map.rotateLeft': 'Rotate map left 15°',
    'map.rotateRight': 'Rotate map right 15°',
    'map.northUp': 'Reset rotation (north up)',
    'map.fit': 'Fit world',
    'map.loading': 'Loading map imagery…',
    'map.failed':
        'Some map imagery could not load. Territory outlines and the list remain available. Reload to retry.',
};
