export default {
    'territory.inspectNation': 'Inspecter {name}',
    'territory.noLeader': 'Aucune information sur le dirigeant.',
    'territory.productivity': 'Détails de productivité',
    'territory.loyalPopulation': 'Population loyale : {value} millions',
    'territory.populationUnknown': 'Population loyale inconnue.',
    'territory.productivityHint':
        'Taux du terrain × population loyale (millions) = production potentielle par ressource. Ces capacités sont indépendantes, sans prévision de production simultanée.',
    'territory.potential': 'Production potentielle',
    'forces.selected': 'Attaque sélectionnée : {attack} · Défense : {defense}',
    'forces.projected': 'Défense prévue avant les batailles : {value}',
    'forces.breakdown':
        'Sur place {staying} · Arrivées {incoming} · Déploiements {deployments}. Ordres confirmés uniquement. Les unités à dissoudre défendent encore ; hors milices, brouillons et résultats des combats.',
    'destinations.label': 'Destinations',
    'destinations.games': 'Parties',
    'destinations.admin': 'Administration',
    'destinations.tools': 'Outils et expériences',
    'tools.intro': 'Découvrez les laboratoires. Ces expériences sont indépendantes de vos parties.',
    'tools.map': 'Laboratoire de cartes',
    'tools.mapBody': 'Expérimentez avec la géographie, les terrains et la génération de cartes.',
    'tools.portrait': 'Laboratoire de portraits',
    'tools.portraitBody': 'Explorez la composition et le rendu des portraits.',
    'tools.identity': 'Laboratoire d’identité',
    'tools.identityBody': 'Essayez les drapeaux à calques, comparez les couleurs et exportez votre création.',
    'tools.gallery': 'Galerie d’interface',
    'tools.galleryBody': 'Découvrez les composants de l’interface et leurs différents états.',
    'tools.open': 'Ouvrir',
    'entry.install': 'Première installation',
    'entry.installBody':
        'Si aucun compte administrateur n’existe encore, exécutez cette commande sur le serveur, puis connectez-vous avec les identifiants générés.',
    'hud.tools': 'Outils et expériences',
    'games.watching': 'Spectateur',
    'games.title': 'Parties',
    'games.game': 'Partie {id}',
    'games.intro': 'Choisissez un monde pour jouer ou observer. Chaque partie évolue indépendamment.',
    'games.empty': 'Aucune partie active pour le moment.',
    'games.playing': 'Votre nation est établie.',
    'games.unfinished': 'La création de votre nation est en cours.',
    'games.open': 'Disponible pour une nouvelle nation.',
    'games.full': 'Aucun territoire de départ disponible. Vous pouvez observer.',
    'games.play': 'Jouer',
    'games.resume': 'Continuer la création',
    'games.join': 'Rejoindre comme joueur',
    'games.spectate': 'Observer',
    'games.pending': 'Une commande est en cours. Attendez son résultat avant de changer de partie.',
    'games.leave':
        'Quitter cette partie ? Les modifications non envoyées seront perdues. Une commande sans résultat confirmé peut avoir atteint le serveur ; vérifiez la partie à votre retour.',
    'automation.off': 'Prêt auto : non',
    'automation.otherTab': 'Prêt auto est déjà actif dans un autre onglet pour cette nation.',
    'automation.context': 'Le joueur ou le contexte du tour a changé. Vérifiez puis réactivez Prêt auto.',
    'automation.countdown': 'Prêt auto : {seconds}s',
    'automation.enable': 'Activer Prêt auto',
    'automation.pause': 'Suspendre Prêt auto',
    'automation.resume': 'Reprendre l’automatisation',
    'automation.delay': 'Délai avant Prêt',
    'automation.help':
        'Les IA jouent une par une. Prêt auto valide seulement votre tour, sans gérer votre nation. Fermer cette page arrête son pilote. Les rapports restent accessibles dans Actualités.',
    'automation.protected': 'La protection des joueurs humains est active.',
    'automation.unprotected': 'La protection des joueurs humains est inactive.',
    'automation.manual': 'Action manuelle : Prêt auto suspendu.',
    'automation.newGame': 'Nouvelle partie : Prêt auto désactivé.',
    'automation.drafts': 'Ordres non envoyés : Prêt auto suspendu.',
    'automation.stopped': 'Automatisation arrêtée. Vérifiez le résultat, actualisez, puis reprenez.',
    'automation.serverPaused': 'IA suspendues par le serveur. Vérifiez et reprenez dans l’administration.',
    'automation.finished': 'Partie terminée. Automatisation arrêtée.',
    'automation.controlled':
        'Cette nation est contrôlée par une IA. Libérez son contrôleur dans l’administration pour la jouer.',
    'automation.ready': '✓ Prêt',
    'automation.planning': 'Préparation',
    'command.orderCosts': 'Coûts supplémentaires des ordres',
    'command.costAvailable': '{resource} : {cost} requis · {available} disponibles',
    'command.costShort': 'Il manque {amount}',
    'command.costBlocked': 'Ressources insuffisantes pour envoyer ces ordres.',
    'command.costRules':
        'Un déplacement ordinaire est gratuit. Une nouvelle attaque utilise les coûts indiqués ; les attaques et raids en cours sont déjà budgétés. Le serveur valide l’ordre final.',
    'nation.colorUnavailable': 'Choisissez une couleur disponible dans la palette.',
    'nation.colorHelp':
        'La couleur principale est réservée à votre nation. Les couleurs secondaires sont partagées, y compris le noir, le blanc et les gris.',
    'turnLoading.title': 'Un nouveau tour prend forme…',
    'turnLoading.waiting': 'En attente du nouveau tour',
    'turnLoading.message0': 'Les forêts poussent. Accordez un instant aux arbres.',
    'turnLoading.message1': 'On demande aux continents de ne pas trop bouger.',
    'turnLoading.message2': 'On convainc les généraux de choisir la même direction.',
    'turnLoading.message3': 'On équilibre le trésor. On découvre un nouveau déséquilibre.',
    'turnLoading.slow':
        'Cela prend plus de temps que prévu. Nous attendons encore les données confirmées du jeu.',
    'turnLoading.failed':
        'Impossible de charger le nouveau tour. Les commandes seront réactivées dès réception des données à jour.',
    'turnLoading.retry': 'Réessayer le chargement',
    'planner.title': 'Planificateur de production nationale',
    'planner.open': 'Ouvrir le planificateur de production',
    'planner.context': 'Tour {turn} · Prévision locale',
    'planner.help':
        'Les objectifs se partagent les travailleurs de chaque territoire. La nourriture et les autres besoins automatiques passent en premier ; le travail nécessaire au Capital est réservé. Les priorités existantes sont conservées : ce n’est pas un partage égal. Les travailleurs restants produisent du Capital si possible. La prévision utilise les installations et réserves actuelles ; le serveur confirme le résultat après application.',
    'planner.hint':
        'Réglez la production supplémentaire. Entretien automatique ; travail restant affecté au Capital.',
    'planner.workforce': 'Travail total',
    'planner.automatic': 'Automatique / réservé',
    'planner.discretionary': 'Disponible pour les objectifs',
    'planner.demand': 'Travail demandé',
    'planner.capital': 'Solde prévu du Capital',
    'planner.production': 'Production · actuelle → prévue',
    'planner.net': 'Solde prévu / tour',
    'planner.labor': 'Travail',
    'planner.target': '{resource} en plus / tour',
    'planner.slider': 'Curseur de production : {resource}',
    'planner.targetHelp':
        'Production supplémentaire demandée après l’entretien automatique. Zéro désactive la demande supplémentaire, pas l’entretien essentiel. La valeur exacte peut dépasser la capacité ; un déficit indique que l’objectif ne peut pas être atteint actuellement.',
    'planner.advanced': 'Avancé · seuils des installations',
    'planner.cutoff': 'Productivité minimale : {resource}',
    'planner.cutoffHelp':
        'Zéro accepte toute installation. Augmenter le seuil exclut les installations moins productives sans les améliorer. Les travailleurs ne changent pas de territoire.',
    'planner.materials': 'Matériaux · sans usage actuel · objectif {value}',
    'planner.territories': 'Prévision par territoire',
    'planner.territory': 'Territoire',
    'planner.resource': 'Ressource',
    'planner.productivity': 'Productivité',
    'planner.output': 'Production / tour',
    'planner.apply': 'Appliquer le plan de production',
    'planner.reset': 'Annuler les modifications',
    'planner.review': 'Résultat vérifié',
    'planner.shortfall': 'Objectif manqué de {value}',
    'planner.shortfallHelp':
        'Capacité admissible ou travail local insuffisant après l’entretien et les demandes concurrentes. Réduisez les objectifs ou vérifiez les seuils avancés. Le travail disponible au niveau national peut se trouver dans les mauvais territoires.',
    'planner.invalid': 'Saisissez des objectifs et seuils valides, positifs ou nuls.',
    'planner.unavailable': 'Prévision indisponible. Actualisez avant d’appliquer.',
    'planner.stale': 'Données anciennes. Actualisez avant d’appliquer.',
    'planner.newTurn': 'Nouveau tour. Les modifications précédentes ont été effacées ; vérifiez le plan.',
    'planner.reserves': 'La prévision utilise les réserves pour couvrir l’entretien.',
    'common.help': 'Aide',
    'common.helpFor': 'Aide : {name}',
    'command.invalidPlacementShort': 'Placement impossible.',
    'command.draftChangedShort': 'Aperçu du déploiement à revoir.',
    'command.selection': 'Sélection',
    'command.appearance': 'Apparence',
    'command.unitStyle': 'Style des unités sur la carte',
    'command.miniatures': 'Miniatures',
    'command.flat': 'Pions plats',
    'command.paint': 'Peinture / uniforme',
    'command.accent': 'Finition des avions',
    'command.brushHelp':
        'Choisissez un type puis cliquez les territoires surlignés : un aperçu par clic. Glissez avec le bouton droit pour déplacer la carte. Confirmez une fois ; les unités seront actives au prochain tour.',
    'command.confirmDeployment': 'Confirmer le déploiement',
    'command.undo': 'Annuler le dernier',
    'command.clearDraft': 'Effacer le brouillon',
    'command.placeFromList': 'Placer depuis une liste',
    'command.addPreview': 'Ajouter à l’aperçu',
    'command.draftSummary': '{count} unités en aperçu · {territories} territoires',
    'command.invalidPlacement':
        'Placement impossible : vérifiez propriété, loyauté, ressources partagées et limite de 100 unités.',
    'command.draftChanged':
        'Ce brouillon n’est plus abordable ou admissible. Annulez des placements avant de confirmer.',
    'command.selectionHelp':
        'Glissez à gauche pour sélectionner ; Maj ajoute. Glissez à droite pour déplacer la carte. + : déploiement confirmé ; ◇ : aperçu non confirmé.',
    'command.militaryMapLabel':
        'Carte militaire. Glissez à gauche pour sélectionner, Maj pour ajouter, à droite pour déplacer. Molette pour zoomer. Flèches pour déplacer ; plus/moins pour zoomer. Utilisez Forces pour la sélection au clavier et Déployer pour le placement.',
    'hud.menu': 'Menu du jeu',
    'hud.navigation': 'Espaces de jeu',
    'hud.world': 'Monde',
    'hud.nation': 'Nation',
    'hud.economy': 'Économie',
    'hud.military': 'Armée',
    'hud.reports': 'Rapports',
    'hud.admin': 'Administration',
    'hud.mapManager': 'Gestion des cartes',
    'hud.logout': 'Déconnexion',
    'hud.resources': 'Soldes et réserves des ressources',
    'hud.ready': 'Prêt',
    'hud.waiting': 'Prêt ✓',
    'hud.sending': 'Envoi…',
    'hud.readyHint': 'Terminer ce tour. Si toutes les nations sont prêtes, le tour avance immédiatement.',
    'hud.news': 'Journal',
    'hud.readiness': '{ready}/{total} prêts',
    'hud.players': 'État des nations',
    'hud.nationId': 'Nation {id}',
    'hud.isReady': 'Prête',
    'hud.planning': 'Préparation',
    'hud.deadline': 'Échéance du tour : {date}',
    'hud.noDeadline': 'Aucune échéance',
    'hud.turnShort': 'tour',
    'hud.reserveShort': 'Rés. {value}',
    'hud.notStockedShort': 'Sans réserve',
    'hud.notStocked': 'Non stockable',
    'hud.balance': 'Solde net / tour',
    'hud.reserve': 'Réserve détenue',
    'hud.production': 'Production',
    'hud.upkeep': 'Consommation / entretien',
    'hud.expenses': 'Engagé dans les ordres',
    'hud.available': 'Disponible pour les ordres',
    'hud.budgetHint':
        'Solde = production − entretien − ordres. La réserve est le stock détenu, pas un budget supplémentaire. Le disponible est la limite calculée par le moteur.',
    'hud.layers': 'Couches · {mode}',
    'hud.collapseMap': 'Réduire la minicarte',
    'hud.expandMap': 'Développer la minicarte',
    'hud.continue': 'Continuer à jouer',
    'hud.briefing': 'Tour {turn} · Bulletin',
    'hud.growth': 'Évolution de la nation',
    'hud.population': 'Population : {value} ({change})',
    'hud.territories': 'Territoires : {value} ({change})',
    'hud.compared':
        'Variation depuis le tour {turn}, incluant les gains et pertes de territoires, pas seulement la croissance naturelle.',
    'hud.noBaseline': 'Aucun tour précédent de cette nation pour comparer.',
    'hud.noCompleted': 'Aucun déploiement achevé enregistré pour le tour précédent.',
    'hud.availableUnits': 'Déploiements possibles maintenant',
    'hud.retryNews': 'Réessayer le journal',
    'hud.staleNews': "Données en cours de mise à jour ou périmées. Actualisez avant d'agir.",
    'hud.loadingNews': 'Chargement des rapports du tour…',
    'hud.failedNews':
        'Impossible de confirmer les rapports. Le jeu reste accessible ; réessayez la lecture du journal.',
    'hud.newsScope': 'Résultats du passage à ce tour. Seuls les combats de votre nation sont présentés.',
    'hud.battles': 'Résultats des combats',
    'hud.won': 'Victoire',
    'hud.lost': 'Défaite',
    'hud.draw': 'Sans vainqueur',
    'hud.neutral': 'Neutre',
    'hud.versus': 'contre',
    'hud.conquered': 'a conquis',
    'hud.repelledBy': 'a été repoussé par',
    'hud.noBattles': 'Aucun combat de votre nation dans les résultats de ce tour.',
    'hud.headlines': 'Actualités du monde',
    'hud.noNews': 'Aucune nouvelle actualité.',
    'hud.completed': 'Déploiements achevés',
    'world.stale': 'Dernier état confirmé affiché. Actualisez avant toute commande.',
    'command.reviewed': 'J’ai vérifié les ordres et le budget',
    'command.newTurn': 'Le tour a changé. Les anciens brouillons d’ordres ont été effacés.',
    'command.unitsChanged':
        'Certaines unités sélectionnées ne sont plus disponibles ; la sélection a été mise à jour.',
    'command.invalidDraft':
        'Ce brouillon n’est plus valide. Vérifiez quantité, disponibilité et destination.',
    'command.invalidDestination': 'Destination indisponible',
    'command.modes': 'Modes de carte',
    'command.geopolitical': 'Géopolitique',
    'command.military': 'Militaire',
    'command.economic': 'Économique',
    'command.find': 'Chercher un territoire',
    'command.deploy': 'Déployer',
    'command.forces': 'Forces',
    'command.orders': 'Ordres en attente',
    'command.move': 'Déplacer / attaquer',
    'command.resources': 'Ressources disponibles',
    'command.commands': 'Sélection et commandes',
    'command.minimap': 'Vue du monde',
    'command.minimapHelp': 'Minicarte. Cliquer pour naviguer ; flèches pour déplacer ; Début pour centrer.',
    'command.available': 'Disponible après engagements',
    'command.close': 'Fermer',
    'command.noNation': 'Fondez une nation avant de commander des forces.',
    'command.createNation': 'Créer une nation',
    'command.loading': 'Chargement de vos forces…',
    'command.retry': 'Réessayer',
    'command.selectUnits': 'Sélectionnez les unités à commander. Cela ne transmet aucun ordre.',
    'command.selectAll': 'Sélectionner toutes les unités affichées',
    'command.selectDivision': 'Sélectionner la division {id}',
    'command.selectGroup': 'Sélectionner {count} unités {unit}',
    'command.unitGroup': '{count} × {unit}',
    'command.mixedOrders': 'Ordres différents',
    'command.noForces': 'Aucune unité active ici. Les déploiements deviennent actifs au prochain tour.',
    'command.selected': '{count} unités sélectionnées',
    'command.cancelSelected': 'Annuler les ordres sélectionnés',
    'command.more': 'Autres actions',
    'command.disband': 'Dissoudre les unités sélectionnées',
    'command.disbandConfirm': 'Ordonner la dissolution de {count} unités à la fin du tour {turn} ?',
    'command.confirm': 'Confirmer',
    'command.territoryDetails': 'Détails du territoire',
    'command.deployHelp':
        'Choisissez une unité, une quantité et un territoire possédé en surbrillance. Le déploiement sera actif au prochain tour.',
    'command.unitTypes': 'Types d’unités existants',
    'command.unknownMax': 'Disponibilité inconnue — actualisation requise',
    'command.max': 'Maximum abordable : {count}',
    'command.badgeLegend': 'Ajout possible · ◇ Aperçu',
    'command.previewCount': '{count} en aperçu',
    'command.unitDetails': 'Détails de l’unité',
    'command.unitDetailsFor': '{name} : coûts et détails',
    'command.draftDetails': 'Coûts et entretien de l’aperçu',
    'command.costShort': 'Coût',
    'command.quantityShort': 'Quantité',
    'command.limitReached': 'Aucune unité supplémentaire disponible.',
    'command.noEligibleShort': 'Aucun territoire admissible.',
    'command.resourceShortage': '{resource} : coût {needed} ; disponible après aperçu {available}.',
    'command.draftFull': 'Cet aperçu atteint la limite de 100 unités par demande.',
    'command.serverLimit':
        'La limite de déploiement fournie par le serveur est atteinte. La disponibilité tient compte des engagements existants et de cet aperçu.',
    'command.cancel': 'Annuler',
    'command.cancelGroup': 'Annuler le groupe',
    'command.cancelGroupLabel': 'Annuler le groupe : {name} ({count} unités)',
    'command.action.Deploy': 'Déployer',
    'command.action.Move': 'Déplacer',
    'command.action.Attack': 'Attaquer',
    'command.action.Raid': 'Raid',
    'command.action.Disband': 'Dissoudre',
    'command.quantity': 'Quantité (100 maximum par demande)',
    'command.requestDeployment': 'Demander le déploiement',
    'command.deploymentCost': 'Coût du déploiement',
    'command.upkeep': 'Entretien par tour',
    'command.attackCost': 'Coût d’attaque par unité',
    'command.unitStats': 'Mouvement {moves} · Attaque {attack} · Défense {defense}',
    'command.noCapture': 'Ne peut pas capturer de territoire.',
    'command.sharedMax':
        'À gauche : unités supplémentaires abordables après cet aperçu. ◇ : unités placées dans l’aperçu non confirmé. Les maximums partagent les mêmes ressources ; ils ne sont pas indépendants.',
    'command.unaffordable': 'Ressources disponibles insuffisantes pour cette unité.',
    'command.noEligible': 'Aucun territoire possédé ne dispose de la loyauté requise.',
    'command.destination': 'Territoire de destination',
    'command.chooseDestination': 'Choisir sur la carte ou ici…',
    'command.chooseFromList': 'Choisir dans une liste',
    'command.pickOnMap': 'Choisissez une destination sur la carte',
    'command.pickAnother': 'Choisir une autre destination sur la carte',
    'command.routeSummary': '{reachable} unités sur {count} peuvent atteindre {destination}',
    'command.routeDetails': 'Détails des trajets',
    'command.routeGroup': '{count} × {route}',
    'command.unreachableGroup': '{count} ne peuvent pas atteindre cette destination',
    'command.moveHelp':
        'Choisissez une destination, vérifiez le trajet et confirmez. Les destinations étrangères utilisent les règles d’attaque/raid existantes. Le serveur valide l’ordre.',
    'command.sendOrders': 'Envoyer les ordres de mouvement / attaque',
    'command.unreachable': 'Aucune destination accessible sélectionnée.',
    'command.direct': 'Trajet direct (transport côtier existant inclus)',
    'command.noOrders': 'Aucun ordre en attente',
    'command.pendingHelp': 'Ces ordres ont été acceptés pour ce tour ; ils ne sont pas encore exécutés.',
    'command.cancelDeployment': 'Annuler le déploiement nº{id}',
    'command.cancelOrder': 'Annuler l’ordre nº{id}',
    'command.submitting': 'Envoi au serveur de jeu…',
    'command.none': 'Aucun',
    'command.unit.Infantry': 'Infanterie',
    'command.unit.Armored': 'Blindés',
    'command.unit.Artillery': 'Artillerie',
    'command.unit.Fighter': 'Chasseur',
    'command.unit.Bomber': 'Bombardier',
    'command.resource.Capital': 'Capital',
    'command.resource.RecruitmentPool': 'Recrutement',
    'command.resource.Food': 'Nourriture',
    'command.resource.Material': 'Matériaux',
    'command.resource.Ore': 'Minerai',
    'command.resource.Oil': 'Pétrole',
    'map.beta': 'Carte expérimentale · Bêta',
    'map.generate': 'Carte de nouvelle partie',
    'errors.stale': 'Le monde a changé. Actualisez avant de continuer.',
    'map.navigation': 'Navigation de la carte',
    'map.world': 'Carte du monde',
    'terrain.Water': 'Eau',
    'terrain.Plain': 'Plaine',
    'terrain.River': 'Fleuve',
    'terrain.Desert': 'Désert',
    'terrain.Tundra': 'Toundra',
    'terrain.Mountain': 'Montagne',
    'terrain.Forest': 'Forêt',
    'world.connecting': 'Connexion…',
    'world.preview': 'Monde actuel · Interface expérimentale',
    'world.tagline': 'Un monde entre vos mains',
    'world.nav': 'Navigation du jeu',
    'world.signOut': 'Déconnexion',
    'world.loading': 'Chargement du monde…',
    'world.signedIn': 'Connecté en tant que {name} · Monde / Exploration',
    'world.inspector': 'Renseignements territoriaux',
    'world.dialog': 'Inspecteur indépendant',
    'world.opening': 'Ouverture du monde…',
    'world.turn': 'Tour {turn}',
    'world.context': 'Monde {game} · {count} nations',
    'world.synced': 'Monde synchronisé · Interface expérimentale',
    'world.noNation': 'Monde synchronisé · Aucune nation',
    'world.create': 'Créer votre nation',
    'world.syncing': 'Synchronisation du monde…',
    'world.unavailable': 'Monde indisponible',
    'world.update': 'Une mise à jour est disponible. Rechargez cette page pour la recevoir.',
    'world.connection': 'Connexion au monde',
    'world.failed': 'Impossible d’ouvrir le monde',
    'world.signIn': 'Se reconnecter',
    'world.survey': 'Vue du monde',
    'world.browse': 'Explorer / sélectionner',
    'world.yours': 'Votre nation',
    'world.others': 'Autres nations',
    'world.zoomNames': 'Les noms apparaissent en zoomant',
    'world.search': 'Rechercher un territoire…',
    'world.directory': 'Répertoire du monde',
    'world.known': 'Le monde connu',
    'world.territories': 'Territoires',
    'world.searchLabel': 'Rechercher des territoires',
    'world.layers': 'Couches de la carte',
    'world.count': '{count} territoires',
    'world.matching': '{count} territoires correspondent à votre recherche',
    'world.ownTerritory': 'Votre territoire',
    'world.noMatches': 'Aucun territoire correspondant.',
    'layer.terrain': 'Terrain',
    'layer.ownership': 'Propriété',
    'layer.borders': 'Frontières',
    'layer.detail': 'Détails',
    'layer.names': 'Noms des territoires',
    'territory.unclaimed': 'Territoire indépendant',
    'territory.nation': 'Nation',
    'territory.noNation': 'Indépendant',
    'territory.land': 'Terres utilisables',
    'territory.sea': 'Accès à la mer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.unknown': 'Inconnu',
    'territory.production': 'Production actuelle',
    'territory.noProduction': 'Aucune production du propriétaire n’est indiquée pour ce territoire.',
    'territory.connections': 'Connexions et loyauté',
    'territory.connectionCount': '{land} connexions terrestres · {total} connexions au total',
    'territory.loyalty': 'Nation {nation} : {loyalty}',
    'territory.owner': 'Informations du propriétaire',
    'territory.deploy': 'Déploiement autorisé par la loyauté actuelle.',
    'territory.noDeploy': 'Déploiement limité par la loyauté actuelle.',
    'territory.public':
        'Informations publiques uniquement. Les données privées des autres nations ne sont pas demandées.',
    'territory.turn': 'Tour {turn} · Consultation en lecture seule',
    'territory.compare': 'Ouvrir un inspecteur séparé ↗',
    'surface.reading': 'Lecture du territoire…',
    'surface.failed': 'Cette fonctionnalité n’a pas pu être chargée.',
    'surface.reload': 'Recharger l’interface',
    'common.back': 'Retour',
    'common.continue': 'Continuer',
    'common.retry': 'Réessayer',
    'common.loading': 'Préparation de votre monde…',
    'common.remove': 'Retirer',
    'common.optional': 'Facultatif',
    'common.language': 'Langue',
    'common.close': 'Fermer',
    'common.refresh': 'Actualiser',
    'entry.title': 'Novus Ordo · Un nouveau départ',
    'entry.edition': 'Un monde de nations',
    'entry.footer': 'Chaque nation commence par un choix.',
    'entry.welcome': 'Bienvenue',
    'entry.intro': 'Votre prochain chapitre commence ici.',
    'entry.login': 'Entrer dans le monde',
    'entry.username': 'Nom d’utilisateur',
    'entry.password': 'Mot de passe',
    'entry.signingIn': 'Connexion…',
    'entry.account': 'Utilisez votre compte Novus Ordo existant.',
    'entry.ready': 'Votre nation vous attend',
    'entry.readyBody': 'Retrouvez le monde et explorez vos territoires.',
    'entry.client': 'Entrer dans le jeu',
    'entry.admin': 'Administration',
    'entry.founded': 'Une nation est née',
    'entry.foundedBody': 'Votre patrie est prête. À vous d’écrire la suite.',
    'entry.unavailable': 'Le monde n’est pas prêt',
    'entry.resume':
        'Une fondation est déjà en cours. Le nom de votre nation a été retrouvé ; complétez les autres informations.',
    'audio.play': 'Activer la musique',
    'audio.mute': 'Couper la musique',
    'audio.volume': 'Volume de la musique',
    'audio.blocked': 'Cliquer pour écouter',
    'audio.error': 'Musique indisponible',
    'audio.playing': 'Musique en cours',
    'wizard.identity': 'Identité',
    'wizard.leader': 'Direction',
    'wizard.homeland': 'Patrie',
    'wizard.review': 'Fondation',
    'wizard.step': 'Chapitre {number} sur {total}',
    'wizard.progress': 'Progression de la création',
    'wizard.found': 'Fonder votre nation',
    'wizard.submitting': 'Fondation de votre nation…',
    'wizard.leave': 'Quitter la création ? Vos informations non enregistrées seront perdues.',
    'nation.identityTitle': 'Donnez un nom à votre nation',
    'nation.identityBody': 'Les premiers mots de votre histoire.',
    'nation.name': 'Nom de la nation',
    'nation.formalName': 'Nom officiel',
    'nation.flag': 'Drapeau national',
    'nation.namePlaceholder': 'Ex. Union aurélienne',
    'nation.formalPlaceholder': 'Ex. La République d’Aurélie',
    'nation.leaderTitle': 'Présentez votre dirigeant',
    'nation.leaderBody': 'Un visage et un nom pour représenter votre peuple.',
    'nation.leaderName': 'Nom du dirigeant',
    'nation.leaderOffice': 'Titre',
    'nation.portrait': 'Portrait du dirigeant',
    'nation.upload': 'PNG, JPEG ou WebP · 2 Mo maximum · 4096 × 4096 maximum',
    'nation.chooseImage': 'Choisir une image',
    'nation.defaultFlag': 'Un drapeau sera attribué si vous n’en choisissez pas.',
    'nation.homelandTitle': 'Choisissez votre point de départ',
    'nation.homelandBody': 'Sélectionnez {count} territoires disponibles et reliés entre eux.',
    'nation.selected': '{selected} / {total} territoires sélectionnés',
    'nation.clear': 'Effacer la sélection',
    'nation.search': 'Rechercher un territoire',
    'nation.available': 'Disponible',
    'nation.chosen': 'Sélectionné',
    'nation.unavailable': 'Indisponible',
    'nation.connected': 'Choisissez un territoire voisin de votre sélection.',
    'nation.noMatches': 'Aucun territoire correspondant.',
    'nation.reviewTitle': 'Les fondations vous appartiennent',
    'nation.reviewBody': 'Vérifiez vos choix avant de fonder votre nation.',
    'nation.edit': 'Modifier : {step}',
    'nation.automatic': 'Attribué par le jeu',
    'nation.none': 'Aucun',
    'nation.territory': 'Territoire',
    'nation.resumeSession': 'Votre session a expiré. Reconnectez-vous pour reprendre votre création.',
    'nation.reconciling': 'Vérification de la fondation de votre nation…',
    'nation.uncertain': 'Le résultat n’a pas pu être confirmé. Vérifiez le serveur avant de réessayer.',
    'nation.recovered':
        'Aucune nation terminée n’a été trouvée. Vos informations sont conservées ; vérifiez-les avant de les envoyer.',
    'errors.validation': 'Vérifiez les champs signalés.',
    'errors.required': 'Ce champ est obligatoire.',
    'errors.length': 'Utilisez entre {min} et {max} caractères.',
    'errors.image': 'Choisissez une image PNG, JPEG ou WebP de 2 Mo maximum.',
    'errors.territories': 'Choisissez {count} territoires disponibles et reliés entre eux.',
    'errors.network': 'Le serveur est injoignable. Vérifiez votre connexion et réessayez.',
    'errors.session': 'Votre session a changé ou a expiré. Reconnectez-vous.',
    'errors.forbidden': 'Vous n’avez pas accès à cette action.',
    'errors.unavailable': 'Le monde est indisponible ou passe au tour suivant. Réessayez dans un instant.',
    'errors.conflict': 'Le monde a changé. Actualisez avant de continuer.',
    'errors.server': 'Le serveur n’a pas pu terminer cette demande.',
    'errors.malformed': 'Le serveur a renvoyé une réponse illisible.',
    'errors.not-found': 'Cette information n’est plus disponible.',
    'errors.abort': 'Demande annulée.',
    'errors.unknown': 'Une erreur est survenue. Réessayez.',
    'errors.notEnough': 'Il n’y a pas assez de territoires de départ libres. Réessayez plus tard.',
    'map.label':
        'Carte du monde. Glissez pour déplacer ; faites défiler pour zoomer. Flèches pour déplacer, plus et moins pour zoomer, Début pour recentrer. Utilisez la liste pour sélectionner.',
    'map.zoom': 'Zoom de la carte',
    'map.zoomIn': 'Agrandir',
    'map.zoomOut': 'Réduire',
    'layer.rivers': 'Rivières',
    'identity.primary': 'Couleur principale',
    'identity.secondary': 'Couleur secondaire',
    'sound.title': 'Retour sonore',
    'sound.enabled': 'Activer les sons',
    'sound.interaction': 'Sons de survol et de clic',
    'sound.events': 'Sons des unités et des événements',
    'sound.volume': 'Volume sonore',
    'sound.hint': 'Silencieux avant activation. Réglages conservés dans ce navigateur.',
    'production.title': 'Production',
    'production.hint':
        'Définissez un objectif national, puis vérifiez quels établissements territoriaux peuvent contribuer. La main-d’œuvre reste locale à chaque territoire ; le moteur attribue la nourriture, l’entretien et les autres demandes.',
    'production.labor': 'Main-d’œuvre réaffectable dans vos territoires : {value}',
    'production.figures': 'Production {production}/tour · Solde {balance}/tour',
    'production.requested': 'Demande : {requested} · Main-d’œuvre attribuée : {labor}',
    'production.automatic': 'Gérée automatiquement par les règles économiques existantes.',
    'production.quantity': 'Objectif de production par tour',
    'production.quantityHelp':
        'Mettez 0 pour désactiver cette demande. La valeur exacte peut dépasser la production actuelle.',
    'production.productivity': 'Productivité minimale des établissements',
    'production.productivityHelp':
        'Mettez 0 pour accepter tout établissement. Une valeur plus élevée exclut les territoires moins productifs ; elle ne les améliore pas.',
    'production.save': 'Enregistrer : {resource}',
    'production.planOff':
        'Cette demande est désactivée. Enregistrer un objectif de 0 l’annule pour les prochains tours.',
    'production.planReady':
        'Le besoin estimé est de {demand} unités de main-d’œuvre ; les territoires admissibles en affichent actuellement {available} de libres.',
    'production.planNoTerritories':
        'Aucun territoire actuel ne possède un établissement de productivité {productivity} ou plus.',
    'production.planCapacityLimited':
        'L’objectif {target} dépasse le plafond territorial admissible de {ceiling}.',
    'production.planLaborLimited':
        'Le besoin estimé est de {demand} unités de main-d’œuvre, contre {available} actuellement libres dans les territoires admissibles. Les affectations existantes et le recalcul du serveur déterminent le résultat.',
    'production.planDemand': 'Besoin estimé en main-d’œuvre',
    'production.planAvailable': 'Main-d’œuvre locale libre',
    'production.planAllocated': 'Actuellement affectée ici',
    'production.planTerritories': 'Territoires admissibles',
    'production.planCeiling': 'Plafond de production',
    'production.planNote':
        'Aperçu local uniquement. La nourriture, l’entretien et les autres demandes enregistrées peuvent modifier l’attribution finale du serveur.',
    'production.territorySummary': 'Détail territorial — {resource} ({count})',
    'production.territoryRow':
        '{territory} : productivité {productivity} · main-d’œuvre libre {available}/{size} · affectée ici {allocated} · plafond {ceiling} · {state}',
    'production.territoryEligible': 'admissible',
    'production.territoryExcluded': 'exclu par le seuil',
    'production.territoryNone': 'Aucun établissement territorial actuel pour cette ressource.',
    'production.facility':
        '{resource} : capacité {capacity} · productivité {productivity} · travail {allocated} · production {output}',
    'production.private': 'Sélectionnez un de vos territoires pour voir ses installations de production.',
    'map.rotateLeft': 'Tourner la carte de 15° vers la gauche',
    'map.rotateRight': 'Tourner la carte de 15° vers la droite',
    'map.northUp': 'Réinitialiser la rotation (nord en haut)',
    'map.fit': 'Voir le monde',
    'map.loading': 'Chargement de la carte…',
    'map.failed':
        'Certaines images n’ont pas pu être chargées. Les contours et la liste restent disponibles. Rechargez pour réessayer.',
};
