export default {
    'history.earnedIncome': 'Revenu national gagné',
    'history.disposableIncome': 'Revenu disponible estimé',
    'history.economicStrength': 'Force économique',
    'history.dynamism': 'Dynamisme',
    'history.activity': 'Revenu civil et conditions',
    'history.conditions': 'Conditions économiques',
    'history.acquisitionHelp':
        'Les unités livrées et leur coût public réel. Ce sont des acquisitions publiques, pas des recettes de ventes civiles.',
    'history.acquisitionSpending': 'Dépenses d’acquisition',
    'history.acquisitions': 'Acquisitions publiques',
    'history.services': 'Santé, éducation et services sociaux',
    'planner.constraint_capacity_inputs_or_workforce':
        'Les capacités, les intrants ou les travailleurs disponibles limitent les livraisons.',
    'planner.privateDevelopmentBudget': 'Dépense de développement privé · monnaie',
    'planner.capacityTarget': 'Capacité cible évaluée',
    'economy.cause_no_workforce': 'aucune main-d’œuvre disponible',
    'economy.cause_policy_funding': 'financement de l’entretien inférieur aux besoins',
    'economy.cause_treasury_shortfall': 'trésorerie et crédit disponibles insuffisants',
    'economy.cause_construction_workforce': 'main-d’œuvre de construction disponible insuffisante',
    'economy.new_borrowing': 'Un nouvel emprunt est nécessaire pour couvrir les dépenses.',
    'economy.interest_default': 'Les intérêts ne sont pas payés; les nouveaux crédits sont restreints.',
    'economy.military_funding_shortfall':
        'L’entretien militaire est sous-financé; les divisions risquent de déserter.',
    'economy.infrastructure_maintenance_shortfall':
        'Le territoire #{territory} ne peut pas achever l’entretien des infrastructures ({cause}).',
    'economy.program_funding_shortfall': 'Le programme {program} ne peut pas être entièrement financé.',
    'economy.civilian_supply_shortfall': 'Il manque {missing} unités de {resource} pour les besoins civils.',
    'economy.programs.environment.paid': 'Protection environnementale',
    'economy.programs.welfare.paid': 'Protection sociale',
    'economy.programs.police.paid': 'Financement de la sécurité publique',
    'economy.programs.education.paid': 'Financement de l’éducation',
    'economy.programs.health.paid': 'Financement de la santé',
    'economy.environment': 'Qualité environnementale',
    'economy.inequality': 'Indice d’inégalité',
    'economy.crime': 'Criminalité',
    'economy.dynamism': 'Dynamisme',
    'economy.education': 'Éducation',
    'economy.health': 'Santé',
    'economy.economic_strength': 'Vigueur économique',
    'economy.tab_services': 'Services et développement',
    'economy.military_costs_paid': 'Coûts militaires récurrents payés',
    'economy.private_development_unused': 'Enveloppe privée inutilisée',
    'economy.private_development_allowance': 'Enveloppe de développement privé',
    'economy.disposable_income_estimate': 'Revenu disponible estimé · national',
    'hud.debtShort': 'Dette',
    'hud.debtChange': 'Variation prévue de la dette / saison',
    'hud.debtInterest': 'Intérêts dus la saison prochaine',
    'hud.creditRemaining': 'Crédit disponible après la saison',
    'hud.creditRestricted': 'Les nouveaux emprunts sont restreints.',
    'hud.debtHint':
        'La dette est le montant dû actuellement. La flèche, les intérêts et le crédit disponible suivent la prévision saisonnière enregistrée.',
    'hud.debtTrend_rising': 'Hausse de la dette prévue',
    'hud.debtTrend_falling': 'Baisse de la dette prévue',
    'hud.debtTrend_steady': 'Dette prévue inchangée',
    'hud.debtTrend_unknown': 'Prévision de dette indisponible',
    'hud.seasonalBalance': 'Solde saisonnier avant financement',
    'hud.seasonalBalanceHint':
        'Prévision enregistrée : recettes moins dépenses et intérêts, hors nouveaux emprunts et remboursements du capital.',
    'planner.publicInvestment': 'Expansion des capacités publiques (%)',
    'planner.publicInvestmentBlocked':
        'Votre politique de propriété des investissements suspend l’expansion publique.',
    'planner.publicInvestmentNoCapacity':
        'Aucune capacité supplémentaire n’est constructible cette saison. Augmenter le financement ne crée pas de gisements.',
    'planner.publicInvestmentHelp':
        'Part de la construction réalisable à financer chaque saison. 0 % arrête l’expansion, pas la production existante. Les nouvelles capacités produisent la saison suivante; l’investissement public doit être autorisé. La production industrielle est vendue aux usines civiles, tandis que les acquisitions constituent les réserves de l’État.',
    'planner.industryRequested': 'Besoin de réapprovisionnement industriel',
    'planner.industryDelivery': 'Production publique vendue aux industries · saison suivante',
    'planner.industryRevenue': 'Ventes publiques aux industries · recettes du trésor',
    'planner.publicDevelopmentBudget': 'Dépense de développement public · monnaie',
    'economy.civilianConstraints': 'Limites de production observées',
    'economy.civilianCauseUnknown': 'Voir les détails de disponibilité et de pouvoir d’achat ci-dessous',
    'economy.publicIndustrySupply': 'Offre industrielle publique / besoin de réapprovisionnement',
    'planner.resources': 'Ressources à acquérir',
    'planner.accountingDetails': 'Comparaison saisonnière et détail des coûts',
    'planner.invalidResource': 'Vérifiez les valeurs de cette ressource',
    'planner.orderShortfall': 'Livraison prévue inférieure à la quantité demandée',
    'planner.unsaved': 'Modifications non enregistrées',
    'planner.wholePlan': 'Plan saisonnier complet · estimation du brouillon',
    'planner.totalSpending': 'Dépenses publiques totales',
    'planner.treasuryAfter': 'Trésorerie après la saison',
    'planner.previousEstimate': 'Estimation précédente affichée ; en attente d’un nouvel aperçu valide.',
    'economy.previousEstimate': 'Estimation précédente affichée ; en attente d’un nouvel aperçu valide.',
    'economy.colourIncome': '+ Recettes / revenus',
    'economy.colourExpense': '− Dépenses · emprunts en ambre',
    'economy.colourProblem': 'Manques / pertes',

    'planner.referencePrice': 'Prix de référence · monnaie par unité',
    'planner.lastOutput': 'Saison passée · production nationale',
    'planner.priority': 'Priorité (plus bas en premier)',
    'planner.priorityHelp':
        'Les nombres inférieurs passent en premier; les besoins civils peuvent être prioritaires.',
    'planner.metric': 'Quantité / coût',
    'planner.lastActual': 'Saison passée · résultat',
    'planner.savedEstimate': 'Saison suivante · plan enregistré',
    'planner.draftEstimate': 'Saison suivante · brouillon',
    'planner.effectiveRequest': 'Objectif d’acquisition, politique de réserve incluse',
    'planner.purchaseCost': 'Dépense d’acquisition publique · monnaie',
    'planner.committed': 'Engagé pour les ordres',
    'planner.available': 'Disponible maintenant',
    'planner.constraints': 'Contraintes de production observées',
    'planner.noConstraints': 'Aucune observée; la production dépend aussi de la demande.',
    'planner.constraint_installed_capacity': 'Capacité installée',
    'planner.constraint_workers': 'Main-d’œuvre partagée',
    'planner.costHelp':
        'Chaque unité livrée à l’État est facturée une seule fois au prix configuré, quel que soit le régime économique. Les besoins civils et les intrants sont servis en priorité. Les nouvelles capacités produisent dès la saison suivante.',
    'planner.forecastShort': 'Prod. estimée',
    'planner.forecastOutput': 'Saison suivante · production nationale estimée',
    'planner.workforce': 'Main-d’œuvre partagée',
    'planner.workersUsed': 'Travailleurs mobilisés · toutes activités',
    'planner.territoryHelp':
        'Les capacités sont partagées. La production prévue dépend des travailleurs et des intrants actuels; les ajouts produisent dès la saison suivante.',
    'planner.potential': 'Potentiel de production géographique',
    'planner.capacity': 'Capacité installée actuelle',
    'planner.production': 'Production prévue',
    'planner.development': 'Capacité ajoutée · saison ultérieure',
    'planner.government': 'Activité publique',
    'planner.producer': 'Activité privée',
    'economy.cashFlows': 'Mouvements du Trésor',
    'economy.cashFlowsHelp':
        'Les totaux incluent financement et programmes publics. Trésor final = Trésor initial + entrées − sorties. Le financement ci-dessous détaille ces totaux sans ajouter de dépense.',
    'economy.financing': 'Dette et financement',
    'economy.nationalActivity': 'Activité nationale · distincte du Trésor',
    'economy.nationalActivityHelp':
        'La population et la vigueur économique territoriale génèrent une seule fois le revenu national. Les impôts financent le trésor; l’activité après impôt soutient les services et le développement privés. Ces valeurs ne sont pas des recettes publiques supplémentaires.',
    'economy.opening_treasury': 'Trésor initial',
    'economy.support_paid': 'Soutien au revenu versé',
    'economy.support_requested': 'Soutien au revenu demandé',
    'economy.income_support_shortfall':
        'Les fonds disponibles ne couvrent pas entièrement le soutien au revenu.',
    'economy.tab_support': 'Soutien au revenu',
    'economy.civilianSupport': 'Soutien au revenu · versé / demandé (crédits)',
    'economy.civilianPurchases': 'Achats commerciaux (unités)',
    'economy.civilianUnmet': 'Besoins non satisfaits (unités)',
    'economy.civilianPurchasingPower': 'Les ménages ne peuvent pas acheter assez de biens.',
    'economy.civilianSupplyShortage': 'Il n’y a pas assez de biens disponibles.',
    'economy.publicInvestmentInactive':
        'Inactif : seuls les investissements privés sont permis. Choisissez les investissements mixtes ou publics pour financer le développement public. Le financement saisi est conservé.',
    'economy.fiscal.borrowing': 'Nouvel emprunt',
    'economy.fiscal.interest_due': 'Intérêts dus',
    'economy.fiscal.arrears': 'Intérêts impayés',
    'economy.fiscal.principal_repaid': 'Capital remboursé',
    'economy.fiscal.relief': 'Allègement de dette',
    'economy.fiscal.closing_debt': 'Dette finale',
    'economy.food_civilian.fulfilled': 'Besoins civils satisfaits',
    'economy.food_civilian.unmet': 'Besoins civils non satisfaits',

    'planner.governmentStock': 'Stock public',
    'economy.payroll_shortfall': 'La solde militaire est insuffisante; des divisions risquent de déserter.',
    'economy.military_goods_shortfall': 'Des biens militaires manquent; des divisions risquent de déserter.',
    'economy.civilian_shortage': 'Les besoins civils ne sont pas entièrement satisfaits.',
    'economy.acquisition_shortfall': 'Il manque {missing} unités de {resource} pour l’acquisition demandée.',
    'economy.food_government_closing': 'Réserve publique finale',
    'economy.food_government_opening': 'Réserve publique initiale',
    'economy.treasury_outflows': 'Sorties totales du Trésor',
    'economy.treasury_inflows': 'Entrées totales du Trésor',
    'economy.private_development': 'Développement privé · réinvestissement estimé',
    'economy.public_development': 'Développement économique public et capacités',
    'economy.government_purchases': 'Acquisitions publiques',
    'economy.earned_income': 'Revenu national',
    'planner.acquired': 'Livraison publique',
    'planner.nationalOutput': 'Production nationale',
    'planner.spendingLimit': 'Plafond de dépenses',
    'planner.requestedQuantity': 'Quantité demandée',
    'economy.title': 'Budget et politiques',
    'economy.budget': 'Budget',
    'economy.policies': 'Politiques',
    'economy.outlook': 'Perspectives nationales',
    'economy.changes': 'Choix pour la prochaine saison',
    'economy.review': 'Vérifier les modifications',
    'economy.save': 'Enregistrer le plan saisonnier',
    'economy.discard': 'Abandonner le brouillon',
    'economy.keepEditing': 'Continuer à modifier',
    'economy.timing':
        'Politiques et acquisitions sont enregistrées ensemble pour la prochaine saison. Enregistrer ne vous déclare pas prêt.',
    'economy.cancelPending': 'Annuler les choix en attente et conserver les politiques actuelles.',
    'economy.inForce': 'En vigueur',
    'economy.configurationOnly': 'Configuration seulement : effets économiques à venir.',
    'economy.conflict':
        'Les choix enregistrés ont changé ailleurs. Abandonnez ce brouillon pour consulter les nouveaux choix.',
    'economy.invalid': 'Corrigez les valeurs avant d’enregistrer.',
    'economy.unsaved': 'Modifications non enregistrées. Vérifiez et enregistrez pour la prochaine saison.',
    'economy.calculating': 'Estimation des effets du brouillon…',
    'economy.pending':
        'Choix enregistrés pour la prochaine saison. Les politiques actuelles restent en vigueur.',
    'economy.noChanges': 'Aucune modification non enregistrée.',
    'economy.notEnabled': 'Créez une nouvelle partie pour utiliser l’économie saisonnière.',
    'economy.availableCash': 'Trésorerie disponible',
    'economy.treasury': 'Trésorerie',
    'economy.committed': 'Fonds engagés dans les ordres',
    'economy.debt': 'Dette actuelle',
    'economy.credit': 'Limite de crédit',
    'economy.credits': 'Crédits',
    'economy.lastActual': 'Saison passée · réel',
    'economy.savedEstimate': 'Prochaine · choix enregistrés',
    'economy.draftEstimate': 'Prochaine · avec modifications',
    'economy.tax_receipts': 'Recettes fiscales',
    'economy.command_costs': 'Ordres et déploiements',
    'economy.repayment': 'Remboursement du capital',
    'economy.military_due': 'Dépenses militaires prévues',
    'economy.interest_due': 'Intérêts de la dette',
    'economy.infrastructure_requested': 'Infrastructures prévues',
    'economy.balance': 'Variation du Trésor',
    'economy.treasuryChangeHelp':
        'Trésor prévu après la saison moins le trésor initial. Cela inclut les emprunts et les remboursements de dette. Le solde saisonnier montre les revenus moins les dépenses avant ces mouvements de financement.',
    'economy.seasonBalanceHelp':
        'Recettes moins dépenses, intérêts compris. Les nouveaux emprunts et remboursements du capital sont exclus. La trésorerie de fin de saison inclut ces mouvements de financement.',
    'economy.financingHelp':
        'Emprunter augmente la trésorerie et la dette. Les intérêts sont une dépense; rembourser le capital réduit trésorerie et dette. Le solde saisonnier exclut emprunts et remboursements du capital.',
    'economy.borrowing': 'Nouvel emprunt nécessaire',
    'economy.closing_debt': 'Dette après la saison',
    'economy.closing_treasury': 'Trésorerie après la saison',
    'economy.military_paid': 'Dépenses militaires financées',
    'economy.agriculture_requested': 'Développement agricole demandé',
    'economy.agriculture_paid': 'Développement agricole financé',
    'economy.agriculture_shortfall': 'Le développement agricole ne peut pas être entièrement financé.',
    'economy.food_shortage':
        'Des besoins alimentaires civils restent insatisfaits : les troubles augmentent et la croissance démographique se dégrade.',
    'economy.food_reserve_shortfall': 'Manque à la réserve',
    'economy.agriculture': 'Potentiel agricole développé',
    'economy.civilianTitle': 'Conditions de vie civiles',
    'economy.civilianMeasure': 'Résultat saisonnier',
    'economy.civilianHelp':
        'Les besoins civils reçoivent les biens en priorité, sans comptes individuels. La géographie, les capacités, les intrants et les travailleurs limitent la production. Le même calcul saisonnier fournit les prévisions sauvegardées et modifiées.',
    'economy.civilianNeedsMet': 'Les besoins civils en biens sont couverts.',
    'economy.civilianNeedsMissed': 'Certains besoins civils manquent de biens.',
    'economy.needsMet': 'besoins satisfaits / requis',
    'economy.civilianWorkers': 'Travailleurs utilisés / disponibles (production et construction)',
    'economy.civilianOutput': 'production marchande',
    'planner.constraint_input': 'Intrant manquant',
    'economy.foodSecurity': 'Sécurité alimentaire',
    'economy.foodHelp':
        'Les ménages achètent aux producteurs. Les réserves publiques peuvent couvrir les besoins non satisfaits. Les acquisitions exigent des fonds et une offre; le développement aide les saisons futures.',
    'economy.food_opening': 'Stock initial',
    'economy.food_production_requested': 'Production demandée',
    'economy.food_production': 'Production prévue / réalisée',
    'economy.food_civilian_requested': 'Consommation civile nécessaire',
    'economy.food_civilian_fulfilled': 'Consommation civile satisfaite',
    'economy.food_civilian_unmet': 'Pénurie civile',
    'economy.food_military_requested': 'Besoins militaires',
    'economy.food_reserve_target': 'Réserve finale visée',
    'economy.food_closing': 'Stock final',
    'economy.infrastructure_paid': 'Infrastructures financées',
    'economy.civilian_income': 'Revenu civil total',
    'economy.income_per_person': 'Revenu disponible / 1 M hab.',
    'economy.infrastructure': 'Infrastructures',
    'economy.unrest': 'Troubles',
    'economy.informal': 'Économie informelle',
    'economy.next': 'Prochaine saison',
    'economy.editEffect': 'Effet des modifications',
    'economy.territories': 'Conditions territoriales',
    'economy.territory': 'Territoire',
    'economy.default': 'Défaut de paiement : crédit restreint.',
    'economy.military_shortfall': 'Armée sous-financée : risque de désertion.',
    'economy.maintenance_shortfall':
        'L’entretien des infrastructures est sous-financé : les territoires concernés vont se dégrader.',
    'economy.infrastructure_shortfall': 'Le financement des infrastructures sera incomplet.',
    'economy.annexed_maintenance_no_workforce':
        'Le territoire nouvellement annexé nº {territory} ne peut pas effectuer son entretien cette saison, car aucune main-d’œuvre n’est disponible. Votre financement des infrastructures est suffisant.',
    'economy.credit_low': 'Le crédit disponible devient faible.',
    'economy.forecastHelp':
        'Cette estimation utilise la propriété, la population, les ordres et les prix de référence actuels. Le résultat n’est pas garanti. Politiques et acquisitions proposées sont incluses.',
    'economy.outlookHelp':
        'Conditions actuelles → résultats estimés. Les effets comparent le brouillon aux choix enregistrés. Infrastructures et réinvestissement bénéficient aux saisons suivantes. Le revenu est un flux, pas la trésorerie publique.',
    'economy.moneyHint':
        'Trésor disponible après les ordres acceptés. Consultez Budget et politiques pour les prévisions.',
    'economy.resources': 'Production de ressources',
    'hud.diplomacy': 'Diplomatie',
    'diplomacy.title': 'Diplomatie',
    'diplomacy.nations': 'Nations',
    'diplomacy.back': 'Toutes les nations',
    'diplomacy.proposePeace': 'Proposer un traité de paix',
    'diplomacy.proposeAlliance': 'Proposer une alliance',
    'diplomacy.cancelTreaty': 'Mettre fin au traité',
    'diplomacy.older': 'Messages précédents',
    'diplomacy.latest': 'Derniers messages',
    'diplomacy.send': 'Envoyer le message',
    'diplomacy.offerGrant': 'Proposer le don',
    'diplomacy.refresh': 'Actualiser',
    'diplomacy.review': 'J’ai vérifié le résultat',
    'diplomacy.message': 'Message',
    'diplomacy.resource': 'Ressource',
    'diplomacy.amount': 'Quantité',
    'diplomacy.grant': 'Faire un don de ressources',
    'diplomacy.conversation': 'Conversation',
    'diplomacy.unavailable': 'La diplomatie est accessible aux nations participantes des nouvelles parties.',
    'diplomacy.stale': 'Actualisation impossible. Dernière conversation confirmée affichée.',
    'diplomacy.delivery':
        'Les messages arrivent pendant le tour. Actualisation environ toutes les 20 secondes.',
    'diplomacy.ai':
        'Nation passive : les messages peuvent être transmis, mais elle ne prend aucune décision diplomatique et ne traite aucune offre.',
    'diplomacy.available': 'Disponible au transfert : {amount}. Stock public après les ordres acceptés.',
    'diplomacy.expires': 'La protection prend fin au début du tour {turn}.',
    'diplomacy.cancelConfirm':
        'Donner un préavis à {name} ? La protection reste active jusqu’au début du tour {turn}.',
    'diplomacy.giveNotice': 'Donner cinq tours de préavis',
    'diplomacy.system': 'Avis du jeu',
    'diplomacy.turn': 'Tour {turn}',
    'diplomacy.accept': 'Accepter',
    'diplomacy.decline': 'Refuser',
    'diplomacy.cancel': 'Annuler l’offre',
    'diplomacy.state.NoRelations': 'Aucune relation',
    'diplomacy.state.War': 'En guerre',
    'diplomacy.state.Peace': 'Traité de paix',
    'diplomacy.state.Allied': 'Alliés',
    'diplomacy.kind.Peace': 'Offre de traité de paix',
    'diplomacy.kind.Alliance': 'Offre d’alliance',
    'diplomacy.status.Pending': 'En attente',
    'diplomacy.status.Accepted': 'Acceptée',
    'diplomacy.status.Declined': 'Refusée',
    'diplomacy.status.Cancelled': 'Annulée',
    'diplomacy.status.Invalid': 'N’est plus valide',
    'diplomacy.reason.insufficient_stock':
        'Le donateur ne dispose plus du stock nécessaire. Aucun transfert effectué.',
    'diplomacy.reason.relationship_changed': 'La situation diplomatique a changé.',
    'diplomacy.reason.ai_unsupported':
        'Cette nation est maintenant contrôlée par une IA et ne peut pas traiter cette offre.',
    'diplomacy.relationshipNotice': 'Nouvelle relation : {state}.',
    'diplomacy.offerResult': 'Offre nº {id} : {status}.',
    'diplomacy.returned': '{count} divisions en visite sont rentrées sur leur territoire.',
    'diplomacy.disbanded':
        '{count} divisions isolées ont été démobilisées, leur nation n’ayant plus de territoire adapté.',
    'diplomacy.notice': 'Avis diplomatique',
    'diplomacy.reverted': 'Cette action a été annulée par un retour au tour précédent.',

    'territory.inspectNation': 'Inspecter {name}',
    'territory.noLeader': 'Aucune information sur le dirigeant.',
    'territory.productivity': 'Détails de productivité',
    'territory.loyalPopulation': 'Population loyale : {value} millions',
    'territory.populationUnknown': 'Population loyale inconnue.',
    'territory.productivityHint':
        'Taux du terrain × population loyale (millions) = production potentielle par ressource. Ces capacités sont indépendantes, sans prévision de production simultanée.',
    'territory.potential': 'Production potentielle',
    'forces.selected': 'Attaque sélectionnée : {attack} · Défense : {defense}',
    'forces.projected': 'Défense prévue avant les batailles : {value}',
    'forces.breakdown':
        'Sur place {staying} · Arrivées {incoming} · Déploiements {deployments}. Ordres confirmés uniquement. Les unités à dissoudre défendent encore ; hors milices, brouillons et résultats des combats.',
    'destinations.label': 'Destinations',
    'destinations.games': 'Parties',
    'destinations.admin': 'Administration',
    'destinations.tools': 'Outils et expériences',
    'tools.intro': 'Découvrez les laboratoires. Ces expériences sont indépendantes de vos parties.',
    'tools.map': 'Laboratoire de cartes',
    'tools.mapBody': 'Expérimentez avec la géographie, les terrains et la génération de cartes.',
    'tools.portrait': 'Laboratoire de portraits',
    'tools.portraitBody': 'Explorez la composition et le rendu des portraits.',
    'tools.identity': 'Laboratoire d’identité',
    'tools.economy': 'Laboratoire économique',
    'tools.economyBody':
        'Testez les prix du cuivre, la demande civile, les dépenses militaires et le commerce international.',
    'tools.identityBody': 'Essayez les drapeaux à calques, comparez les couleurs et exportez votre création.',
    'tools.gallery': 'Galerie d’interface',
    'tools.galleryBody': 'Découvrez les composants de l’interface et leurs différents états.',
    'tools.open': 'Ouvrir',
    'entry.install': 'Première installation',
    'entry.installBody':
        'Si aucun compte administrateur n’existe encore, exécutez cette commande sur le serveur, puis connectez-vous avec les identifiants générés.',
    'hud.tools': 'Outils et expériences',
    'games.watching': 'Spectateur',
    'games.title': 'Parties',
    'games.game': 'Partie {id}',
    'games.intro': 'Choisissez un monde pour jouer ou observer. Chaque partie évolue indépendamment.',
    'games.empty': 'Aucune partie active pour le moment.',
    'games.playing': 'Votre nation est établie.',
    'games.unfinished': 'La création de votre nation est en cours.',
    'games.open': 'Disponible pour une nouvelle nation.',
    'games.full': 'Aucun territoire de départ disponible. Vous pouvez observer.',
    'games.play': 'Jouer',
    'games.resume': 'Continuer la création',
    'games.join': 'Rejoindre comme joueur',
    'games.spectate': 'Observer',
    'games.pending': 'Une commande est en cours. Attendez son résultat avant de changer de partie.',
    'games.leave':
        'Quitter cette partie ? Les modifications non envoyées seront perdues. Une commande sans résultat confirmé peut avoir atteint le serveur ; vérifiez la partie à votre retour.',
    'automation.off': 'Prêt auto : non',
    'automation.otherTab': 'Prêt auto est déjà actif dans un autre onglet pour cette nation.',
    'automation.context': 'Le joueur ou le contexte du tour a changé. Vérifiez puis réactivez Prêt auto.',
    'automation.countdown': 'Prêt auto : {seconds}s',
    'automation.enable': 'Activer Prêt auto',
    'automation.pause': 'Suspendre Prêt auto',
    'automation.resume': 'Reprendre l’automatisation',
    'automation.delay': 'Délai avant Prêt',
    'automation.help':
        'Les nations passives deviennent prêtes une par une. Prêt auto valide seulement votre tour, sans gérer votre nation. Fermer cette page arrête son pilote.',
    'automation.passive': 'Les nations automatisées sont temporairement en mode passif.',
    'automation.passiveLabel': 'Passive',
    'automation.manual': 'Action manuelle : Prêt auto suspendu.',
    'automation.newGame': 'Nouvelle partie : Prêt auto désactivé.',
    'automation.drafts': 'Ordres non envoyés : Prêt auto suspendu.',
    'automation.stopped': 'Automatisation arrêtée. Vérifiez le résultat, actualisez, puis reprenez.',
    'automation.serverPaused': 'Nations passives suspendues. Vérifiez et reprenez dans l’administration.',
    'automation.finished': 'Partie terminée. Automatisation arrêtée.',
    'automation.controlled':
        'Cette nation est contrôlée en mode passif. Libérez son contrôleur dans l’administration pour la jouer.',
    'automation.ready': '✓ Prêt',
    'automation.planning': 'Préparation',
    'command.orderCosts': 'Coûts supplémentaires des ordres',
    'command.costAvailable': '{resource} : {cost} requis · {available} disponibles',
    'command.costShort': 'Il manque {amount}',
    'command.costBlocked': 'Ressources insuffisantes pour envoyer ces ordres.',
    'command.costRules':
        'Un déplacement ordinaire est gratuit. Une nouvelle attaque utilise les coûts indiqués ; les attaques et raids en cours sont déjà budgétés. Le serveur valide l’ordre final.',
    'nation.colorUnavailable': 'Choisissez une couleur disponible dans la palette.',
    'nation.colorHelp':
        'La couleur principale est réservée à votre nation. Les couleurs secondaires sont partagées, y compris le noir, le blanc et les gris.',
    'turnLoading.title': 'Un nouveau tour prend forme…',
    'turnLoading.waiting': 'En attente du nouveau tour',
    'turnLoading.message0': 'Les forêts poussent. Accordez un instant aux arbres.',
    'turnLoading.message1': 'On demande aux continents de ne pas trop bouger.',
    'turnLoading.message2': 'On convainc les généraux de choisir la même direction.',
    'turnLoading.message3': 'On équilibre le trésor. On découvre un nouveau déséquilibre.',
    'turnLoading.message4': 'On apprend aux frontières à respecter les lignes.',
    'turnLoading.message5': 'On compte les patates. On recompte les plus suspectes.',
    'turnLoading.message6': 'On démêle la poignée de main diplomatique.',
    'turnLoading.message7': 'On repasse les drapeaux. Attention aux petites étoiles.',
    'turnLoading.message8': 'On cherche le général qui a emprunté la carte.',
    'turnLoading.message9': 'On encourage les montagnes. Elles restent de marbre.',
    'turnLoading.message10': 'On vérifie si le trésor possède un double fond.',
    'turnLoading.message11': 'On demande à l’artillerie de parler moins fort.',
    'turnLoading.message12': 'On livre un panier de muffins au ton très ferme.',
    'turnLoading.message13': 'On persuade les rivières de rester dans leur lit.',
    'turnLoading.message14': 'On fait de la place pour une autre grande ambition nationale.',
    'turnLoading.message15': 'On vérifie le plan de vol du pigeon royal.',
    'turnLoading.message16': 'On remet les petits arbres sur la carte.',
    'turnLoading.message17': 'On cherche un plus grand chapeau pour le ministre des Chapeaux.',
    'turnLoading.message18': 'On classe les documents sous « glorieux ».',
    'turnLoading.message19': 'On offre une tasse de thé aux dés.',
    'turnLoading.message20': 'On explique que « par là » n’est pas un plan de bataille.',
    'turnLoading.message21': 'On forme le comité chargé de nommer le comité.',
    'turnLoading.message22': 'On cherche les souris ambitieuses dans les greniers.',
    'turnLoading.message23': 'On polit les médailles avant qu’on nous en réclame.',
    'turnLoading.message24': 'On apprend à la cavalerie à se stationner en parallèle.',
    'turnLoading.message25': 'On répète l’hymne. Le tuba a des réserves.',
    'turnLoading.message26': 'On demande au brouillard de respecter les frontières.',
    'turnLoading.message27': 'On fait un petit signe rassurant au budget.',
    'turnLoading.message28': 'On mesure l’empire. Tenez l’autre bout, s’il vous plaît.',
    'turnLoading.message29': 'On ajoute un sceau inutilement impressionnant au traité.',
    'turnLoading.message30': 'On vérifie que le nord est toujours en haut.',
    'turnLoading.message31': 'On cherche les chaussettes porte-bonheur de la dernière milice.',
    'turnLoading.message32': 'On rappelle aux amiraux que la réunion se tient sur terre.',
    'turnLoading.message33': 'On apporte du café frais aux gardes-frontières.',
    'turnLoading.message34': 'On trie les rumeurs selon leur potentiel dramatique.',
    'turnLoading.message35': 'On demande aux économistes de montrer leurs calculs.',
    'turnLoading.message36': 'On cherche une boutique de souvenirs dans le passage secret.',
    'turnLoading.message37': 'On fait poser l’oiseau national pour son portrait.',
    'turnLoading.message38': 'On distribue de petits casques aux messagers très importants.',
    'turnLoading.message39': 'On retire le ruban cérémonial de la route du ravitaillement.',
    'turnLoading.message40': 'On négocie un cessez-le-feu entre deux imprimantes.',
    'turnLoading.message41': 'On vérifie si le budget « divers » peut financer une armée.',
    'turnLoading.message42': 'On accorde à chaque province son petit moment au soleil.',
    'turnLoading.message43': 'On vérifie que le défilé tourne à la bonne rue.',
    'turnLoading.message44': 'On replie la carte du monde le long du mauvais pli.',
    'turnLoading.message45': 'On demande au gardien du château où sont passées les clés.',
    'turnLoading.message46': 'On prépare un sandwich à l’allure très officielle.',
    'turnLoading.message47': 'On vérifie le phare. Oui, il éclaire toujours.',
    'turnLoading.message48': 'On convainc les éclaireurs de dessiner moins de dragons.',
    'turnLoading.message49': 'On réserve un balcon pour le prochain grand discours.',
    'turnLoading.message50': 'On rappelle aux recenseurs de ne pas compter les épouvantails.',
    'turnLoading.message51': 'On demande aux chariots de ravitaillement de faire la file.',
    'turnLoading.message52': 'On enlève les miettes de biscuits du décret royal.',
    'turnLoading.message53': 'On cherche une façon diplomatique de dire « beau chapeau ».',
    'turnLoading.message54': 'On place les prévisions économiques près d’une fenêtre ensoleillée.',
    'turnLoading.message55': 'On s’assure que les moutons neutres restent neutres.',
    'turnLoading.message56': 'On déroule le tapis rouge. On déloge un chat obstiné.',
    'turnLoading.message57': 'On rappelle aux généraux que la carte n’est pas une serviette.',
    'turnLoading.message58': 'On vérifie la réserve d’urgence de trompettes cérémonielles.',
    'turnLoading.message59': 'On laisse à l’Histoire un instant pour trouver ses lunettes.',
    'turnLoading.failed':
        'Impossible de charger le nouveau tour. Les commandes seront réactivées dès réception des données à jour.',
    'turnLoading.retry': 'Réessayer le chargement',
    'planner.foodPolicyManaged': 'Les réserves alimentaires suivent aussi la politique nationale.',
    'planner.foodReserveTarget': 'Réserve visée',
    'planner.resourceHint':
        'Commandes répétées chaque saison, livrées à sa fin. Enregistrer inclut toutes les ressources et politiques.',
    'planner.extraQuantity': 'Objectif supplémentaire',
    'planner.minimumProductivity': 'Productivité minimale (production par million de travailleurs)',
    'planner.closingStock': 'Stock public final',
    'planner.unmetDemand': 'Demande non satisfaite',
    'planner.calculating': 'Calcul de la production…',
    'planner.title': 'Production et acquisitions',
    'planner.open': 'Ouvrir le planificateur de production',
    'planner.context': 'Tour {turn} · Prévision locale',
    'planner.resource': 'Ressource',
    'planner.productivity': 'Productivité',
    'planner.output': 'Production / tour',
    'planner.apply': 'Enregistrer le plan saisonnier',
    'planner.reset': 'Annuler les modifications',
    'planner.review': 'Résultat vérifié',
    'planner.shortfall': 'Objectif manqué de {value}',
    'planner.shortfallHelp':
        'Capacité admissible ou travail local insuffisant après l’entretien et les demandes concurrentes. Réduisez les objectifs ou vérifiez les seuils avancés. Le travail disponible au niveau national peut se trouver dans les mauvais territoires.',
    'planner.invalid':
        'Vérifiez les onglets signalés : quantités et plafonds positifs ou nuls (6 décimales maximum) ; priorité entière positive ou nulle.',
    'planner.unavailable': 'Prévision indisponible. Actualisez avant d’appliquer.',
    'planner.stale': 'Données anciennes. Actualisez avant d’appliquer.',
    'planner.newTurn': 'Nouveau tour. Les modifications précédentes ont été effacées ; vérifiez le plan.',
    'planner.reserves': 'La prévision utilise les réserves pour couvrir l’entretien.',
    'common.help': 'Aide',
    'common.helpFor': 'Aide : {name}',
    'command.invalidPlacementShort': 'Placement impossible.',
    'command.draftChangedShort': 'Aperçu du déploiement à revoir.',
    'command.selection': 'Sélection',
    'command.appearance': 'Apparence',
    'command.unitStyle': 'Style des unités sur la carte',
    'command.miniatures': 'Miniatures',
    'command.flat': 'Pions plats',
    'command.paint': 'Peinture / uniforme',
    'command.accent': 'Finition des avions',
    'command.brushHelp':
        'Choisissez un type puis cliquez les territoires surlignés : un aperçu par clic. Glissez avec le bouton droit pour déplacer la carte. Confirmez une fois ; les unités seront actives au prochain tour.',
    'command.confirmDeployment': 'Confirmer le déploiement',
    'command.undo': 'Annuler le dernier',
    'command.clearDraft': 'Effacer le brouillon',
    'command.placeFromList': 'Placer depuis une liste',
    'command.addPreview': 'Ajouter à l’aperçu',
    'command.draftSummary': '{count} unités en aperçu · {territories} territoires',
    'command.invalidPlacement':
        'Placement impossible : vérifiez propriété, loyauté, ressources partagées et limite de 100 unités.',
    'command.draftChanged':
        'Ce brouillon n’est plus abordable ou admissible. Annulez des placements avant de confirmer.',
    'command.selectionHelp':
        'Glissez à gauche pour sélectionner ; Maj ajoute. Glissez à droite pour déplacer la carte. + : déploiement confirmé ; ◇ : aperçu non confirmé.',
    'command.filterUnits': 'Filtrer les unités',
    'command.filterIdle': 'Sans ordre',
    'command.filterGuard': 'En garde',
    'command.filterHint': 'Cliquez pour inclure seulement · Maj-clic pour exclure',
    'command.filterButtonHint': '{name} : cliquez pour inclure seulement ; Maj-clic pour exclure',
    'command.filterAvailable': 'Filtrer par {name}',
    'command.filterIncluding': 'Inclure seulement {name}',
    'command.filterExcluding': 'Exclure {name}',
    'command.clearFilters': 'Effacer les filtres d’unités',
    'command.noFilterMatches': 'Aucune unité ne correspond à ces filtres.',
    'command.selectedShown': '{count} unités sélectionnées · {shown} affichées',
    'command.militaryMapLabel':
        'Carte militaire. Glissez à gauche pour sélectionner, Maj pour ajouter, à droite pour déplacer. Molette pour zoomer. Flèches pour déplacer ; plus/moins pour zoomer. Utilisez Forces pour la sélection au clavier et Déployer pour le placement.',
    'hud.menu': 'Menu du jeu',
    'hud.navigation': 'Espaces de jeu',
    'hud.world': 'Monde',
    'hud.nation': 'Nation',
    'hud.economy': 'Budget et politiques',
    'hud.military': 'Armée',
    'hud.reports': 'Rapports',
    'hud.admin': 'Administration',
    'hud.mapManager': 'Gestion des cartes',
    'hud.logout': 'Déconnexion',
    'hud.resources': 'Soldes et réserves des ressources',
    'hud.ready': 'Prêt',
    'hud.waiting': 'Prêt ✓',
    'hud.sending': 'Envoi…',
    'hud.readyHint': 'Terminer ce tour. Si toutes les nations sont prêtes, le tour avance immédiatement.',
    'hud.news': 'Journal',
    'hud.readiness': '{ready}/{total} prêts',
    'hud.players': 'État des nations',
    'hud.nationId': 'Nation {id}',
    'hud.isReady': 'Prête',
    'hud.planning': 'Préparation',
    'hud.deadline': 'Échéance du tour : {date}',
    'hud.noDeadline': 'Aucune échéance',
    'hud.turnShort': 'tour',
    'hud.reserveShort': 'Rés. {value}',
    'hud.notStockedShort': 'Sans réserve',
    'hud.notStocked': 'Non stockable',
    'hud.balance': 'Solde net / tour',
    'hud.reserve': 'Réserve détenue',
    'hud.production': 'Production',
    'hud.upkeep': 'Consommation / entretien',
    'hud.expenses': 'Engagé dans les ordres',
    'hud.available': 'Disponible pour les ordres',
    'hud.budgetHint':
        'La production nationale est un flux, pas une réserve détenue. Le changement de stock inclut les acquisitions livrées, les distributions et la consommation militaire. Le disponible est le stock détenu après les ordres acceptés.',
    'hud.collapseMap': 'Réduire la minicarte',
    'hud.expandMap': 'Développer la minicarte',
    'hud.continue': 'Continuer à jouer',
    'hud.briefing': 'Tour {turn} · Bulletin',
    'hud.growth': 'Évolution de la nation',
    'hud.population': 'Population : {value} ({change})',
    'hud.territories': 'Territoires : {value} ({change})',
    'hud.compared':
        'Variation depuis le tour {turn}, incluant les gains et pertes de territoires, pas seulement la croissance naturelle.',
    'hud.noBaseline': 'Aucun tour précédent de cette nation pour comparer.',
    'hud.noCompleted': 'Aucun déploiement achevé enregistré pour le tour précédent.',
    'hud.availableUnits': 'Déploiements possibles maintenant',
    'hud.retryNews': 'Réessayer le journal',
    'hud.staleNews': "Données en cours de mise à jour ou périmées. Actualisez avant d'agir.",
    'hud.loadingNews': 'Chargement des rapports du tour…',
    'hud.failedNews':
        'Impossible de confirmer les rapports. Le jeu reste accessible ; réessayez la lecture du journal.',
    'hud.newsScope': 'Résultats du passage à ce tour. Seuls les combats de votre nation sont présentés.',
    'hud.battles': 'Résultats des combats',
    'hud.won': 'Victoire',
    'hud.lost': 'Défaite',
    'hud.draw': 'Sans vainqueur',
    'hud.neutral': 'Neutre',
    'hud.versus': 'contre',
    'hud.conquered': 'a conquis',
    'hud.repelledBy': 'a été repoussé par',
    'ownership.view': 'Voir sur la carte',
    'ownership.title': 'Changement de propriétaire',
    'ownership.loading': 'Chargement des cartes des deux tours…',
    'ownership.failed': 'Impossible de charger ces cartes. Réessayez.',
    'ownership.before': 'Avant · Tour {turn}',
    'ownership.after': 'Après · Tour {turn}',
    'ownership.scope':
        'Territoires ayant changé de propriétaire : {count}. Tous les changements sont affichés ensemble.',
    'ownership.unchanged': 'Aucun territoire n’a changé de propriétaire entre ces deux tours.',
    'ownership.play': 'Lecture',
    'ownership.pause': 'Pause',
    'ownership.done': 'Terminé',
    'ownership.retry': 'Réessayer',
    'hud.noBattles': 'Aucun combat de votre nation dans les résultats de ce tour.',
    'hud.headlines': 'Actualités du monde',
    'hud.noNews': 'Aucune nouvelle actualité.',
    'hud.completed': 'Déploiements achevés',
    'world.stale': 'Dernier état confirmé affiché. Actualisez avant toute commande.',
    'command.reviewed': 'J’ai vérifié les ordres et le budget',
    'command.newTurn': 'Le tour a changé. Les anciens brouillons d’ordres ont été effacés.',
    'command.unitsChanged':
        'Certaines unités sélectionnées ne sont plus disponibles ; la sélection a été mise à jour.',
    'command.invalidDraft':
        'Ce brouillon n’est plus valide. Vérifiez quantité, disponibilité et destination.',
    'command.invalidDestination': 'Destination indisponible',
    'command.modes': 'Modes de carte',
    'command.geopolitical': 'Géopolitique',
    'command.military': 'Militaire',
    'command.economic': 'Économique',
    'command.find': 'Chercher un territoire',
    'command.deploy': 'Déployer',
    'command.forces': 'Forces',
    'command.orders': 'Ordres en attente',
    'command.move': 'Déplacer / attaquer',
    'command.resources': 'Ressources disponibles',
    'command.commands': 'Sélection et commandes',
    'command.minimap': 'Vue du monde',
    'command.minimapHelp': 'Minicarte. Cliquer pour naviguer ; flèches pour déplacer ; Début pour centrer.',
    'command.available': 'Disponible après engagements',
    'command.close': 'Fermer',
    'command.noNation': 'Fondez une nation avant de commander des forces.',
    'command.createNation': 'Créer une nation',
    'command.loading': 'Chargement de vos forces…',
    'command.retry': 'Réessayer',
    'command.selectUnits': 'Sélectionnez les unités à commander. Cela ne transmet aucun ordre.',
    'command.selectAll': 'Sélectionner toutes les unités affichées',
    'command.selectDivision': 'Sélectionner la division {id}',
    'command.selectGroup': 'Sélectionner {count} unités {unit}',
    'command.unitGroup': '{count} × {unit}',
    'command.mixedOrders': 'Ordres différents',
    'command.noForces': 'Aucune unité active ici. Les déploiements deviennent actifs au prochain tour.',
    'command.selected': '{count} unités sélectionnées',
    'command.cancelSelected': 'Annuler les ordres sélectionnés',
    'command.disband': 'Dissoudre les unités sélectionnées',
    'command.disbandConfirm': 'Ordonner la dissolution de {count} unités à la fin du tour {turn} ?',
    'command.guard': 'Mettre les unités sélectionnées en garde',
    'command.guardConfirm':
        'Mettre {count} unités en garde permanente ? La disponibilité coûte 25 % des frais d’opération habituels; une intervention porte le coût du tour à 100 %. Leur retrait exigera ensuite un tour de désengagement.',
    'command.defensePotential': 'Défense potentielle pour une attaque : {value}',
    'command.defensePotentialBreakdown':
        'Base {base} · Garde à portée {guard} ({count} unités). Ce calcul suppose que ce territoire est le seul attaqué.',
    'command.confirm': 'Confirmer',
    'command.territoryDetails': 'Détails du territoire',
    'command.deployHelp':
        'Choisissez une unité, une quantité et un territoire possédé en surbrillance. Le déploiement sera actif au prochain tour.',
    'command.unitTypes': 'Types d’unités existants',
    'command.unknownMax': 'Disponibilité inconnue — actualisation requise',
    'command.max': 'Maximum abordable : {count}',
    'command.badgeLegend': 'Ajout possible · ◇ Aperçu',
    'command.previewCount': '{count} en aperçu',
    'command.unitDetails': 'Détails de l’unité',
    'command.unitDetailsFor': '{name} : coûts et détails',
    'command.draftDetails': 'Coûts et entretien de l’aperçu',
    'command.costShort': 'Coût',
    'command.quantityShort': 'Quantité',
    'command.limitReached': 'Aucune unité supplémentaire disponible.',
    'command.noEligibleShort': 'Aucun territoire admissible.',
    'command.resourceShortage': '{resource} : coût {needed} ; disponible après aperçu {available}.',
    'command.draftFull': 'Cet aperçu atteint la limite de 100 unités par demande.',
    'command.serverLimit':
        'La limite de déploiement fournie par le serveur est atteinte. La disponibilité tient compte des engagements existants et de cet aperçu.',
    'command.cancel': 'Annuler',
    'command.release': 'Retirer',
    'command.releaseGroup': 'Retirer le groupe',
    'command.releaseGroupLabel': 'Retirer le groupe de la garde : {name} ({count} unités)',
    'command.releaseGuard': 'Retirer la division {id} de la garde',
    'command.cancelGroup': 'Annuler le groupe',
    'command.cancelGroupLabel': 'Annuler le groupe : {name} ({count} unités)',
    'command.action.Deploy': 'Déployer',
    'command.action.Move': 'Déplacer',
    'command.action.Attack': 'Attaquer',
    'command.action.Raid': 'Raid',
    'command.action.Disband': 'Dissoudre',
    'command.action.Guard': 'Garde',
    'command.action.StandDown': 'Désengagement',
    'command.quantity': 'Quantité (100 maximum par demande)',
    'command.requestDeployment': 'Demander le déploiement',
    'command.deploymentCost': 'Coût du déploiement',
    'command.upkeep': 'Entretien par tour',
    'command.attackCost': 'Coût d’attaque par unité',
    'command.unitStats': 'Mouvement {moves} · Attaque {attack} · Défense {defense}',
    'command.noCapture': 'Ne peut pas capturer de territoire.',
    'command.sharedMax':
        'À gauche : unités supplémentaires abordables après cet aperçu. ◇ : unités placées dans l’aperçu non confirmé. Les maximums partagent les mêmes ressources ; ils ne sont pas indépendants.',
    'command.unaffordable': 'Ressources disponibles insuffisantes pour cette unité.',
    'command.noEligible': 'Aucun territoire possédé ne dispose de la loyauté requise.',
    'command.destination': 'Territoire de destination',
    'command.chooseDestination': 'Choisir sur la carte ou ici…',
    'command.chooseFromList': 'Choisir dans une liste',
    'command.pickOnMap': 'Choisissez une destination sur la carte',
    'command.pickAnother': 'Choisir une autre destination sur la carte',
    'command.routeSummary': '{reachable} unités sur {count} peuvent atteindre {destination}',
    'command.routeDetails': 'Détails des trajets',
    'command.routeGroup': '{count} × {route}',
    'command.unreachableGroup': '{count} ne peuvent pas atteindre cette destination',
    'command.moveHelp':
        'Choisissez une destination, vérifiez le trajet et confirmez. Les destinations étrangères utilisent les règles d’attaque/raid existantes. Le serveur valide l’ordre.',
    'command.sendOrders': 'Envoyer les ordres de mouvement / attaque',
    'command.unreachable': 'Aucune destination accessible sélectionnée.',
    'command.direct': 'Trajet direct (transport côtier existant inclus)',
    'command.noOrders': 'Aucun ordre en attente',
    'command.pendingHelp': 'Ces ordres ont été acceptés pour ce tour ; ils ne sont pas encore exécutés.',
    'command.cancelDeployment': 'Annuler le déploiement nº{id}',
    'command.cancelOrder': 'Annuler l’ordre nº{id}',
    'command.submitting': 'Envoi au serveur de jeu…',
    'command.none': 'Aucun',
    'command.unit.Infantry': 'Infanterie',
    'command.unit.Armored': 'Blindés',
    'command.unit.Artillery': 'Artillerie',
    'command.unit.Fighter': 'Chasseur',
    'command.unit.Bomber': 'Bombardier',
    'command.resource.Capital': 'Capital',
    'command.resource.RecruitmentPool': 'Recrutement',
    'command.resource.Food': 'Nourriture',
    'command.resource.Material': 'Matériaux',
    'command.resource.Ore': 'Minerai',
    'command.resource.Oil': 'Pétrole',
    'map.generate': 'Carte de nouvelle partie',
    'errors.stale': 'Le monde a changé. Actualisez avant de continuer.',
    'map.navigation': 'Navigation de la carte',
    'map.world': 'Carte du monde',
    'terrain.Water': 'Eau',
    'terrain.Plain': 'Plaine',
    'terrain.River': 'Fleuve',
    'terrain.Desert': 'Désert',
    'terrain.Tundra': 'Toundra',
    'terrain.Mountain': 'Montagne',
    'terrain.Forest': 'Forêt',
    'world.connecting': 'Connexion…',
    'world.preview': 'Monde actuel',
    'world.tagline': 'Un monde entre vos mains',
    'world.nav': 'Navigation du jeu',
    'world.signOut': 'Déconnexion',
    'world.loading': 'Chargement du monde…',
    'world.signedIn': 'Connecté en tant que {name} · Monde / Exploration',
    'world.inspector': 'Renseignements territoriaux',
    'world.dialog': 'Inspecteur indépendant',
    'world.opening': 'Ouverture du monde…',
    'world.turn': 'Tour {turn}',
    'world.context': 'Monde {game} · {count} nations',
    'world.synced': 'Monde synchronisé · Interface expérimentale',
    'world.noNation': 'Monde synchronisé · Aucune nation',
    'world.create': 'Créer votre nation',
    'world.syncing': 'Synchronisation du monde…',
    'world.unavailable': 'Monde indisponible',
    'world.update': 'Une mise à jour est disponible. Rechargez cette page pour la recevoir.',
    'world.connection': 'Connexion au monde',
    'world.failed': 'Impossible d’ouvrir le monde',
    'world.signIn': 'Se reconnecter',
    'world.survey': 'Vue du monde',
    'world.browse': 'Explorer / sélectionner',
    'world.yours': 'Votre nation',
    'world.others': 'Autres nations',
    'world.zoomNames': 'Les noms apparaissent en zoomant',
    'world.search': 'Rechercher un territoire…',
    'world.directory': 'Répertoire du monde',
    'world.known': 'Le monde connu',
    'world.territories': 'Territoires',
    'world.searchLabel': 'Rechercher des territoires',
    'world.count': '{count} territoires',
    'world.matching': '{count} territoires correspondent à votre recherche',
    'world.ownTerritory': 'Votre territoire',
    'world.noMatches': 'Aucun territoire correspondant.',
    'territory.unclaimed': 'Territoire indépendant',
    'territory.nation': 'Nation',
    'territory.noNation': 'Indépendant',
    'territory.land': 'Terres utilisables',
    'territory.sea': 'Accès à la mer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.unknown': 'Inconnu',
    'territory.production': 'Production actuelle',
    'territory.noProduction': 'Aucune production du propriétaire n’est indiquée pour ce territoire.',
    'territory.connections': 'Connexions et loyauté',
    'territory.connectionCount': '{land} connexions terrestres · {total} connexions au total',
    'territory.loyalty': 'Nation {nation} : {loyalty}',
    'territory.owner': 'Informations du propriétaire',
    'territory.deploy': 'Déploiement autorisé par la loyauté actuelle.',
    'territory.noDeploy': 'Déploiement limité par la loyauté actuelle.',
    'territory.public':
        'Informations publiques uniquement. Les données privées des autres nations ne sont pas demandées.',
    'territory.turn': 'Tour {turn} · Consultation en lecture seule',
    'territory.compare': 'Ouvrir un inspecteur séparé ↗',
    'surface.reading': 'Lecture du territoire…',
    'surface.failed': 'Cette fonctionnalité n’a pas pu être chargée.',
    'surface.reload': 'Recharger l’interface',
    'common.back': 'Retour',
    'common.continue': 'Continuer',
    'common.retry': 'Réessayer',
    'common.loading': 'Préparation de votre monde…',
    'common.remove': 'Retirer',
    'common.optional': 'Facultatif',
    'common.language': 'Langue',
    'common.close': 'Fermer',
    'common.refresh': 'Actualiser',
    'entry.title': 'Novus Ordo · Un nouveau départ',
    'entry.edition': 'Un monde de nations',
    'entry.footer': 'Chaque nation commence par un choix.',
    'entry.welcome': 'Bienvenue',
    'entry.intro': 'Votre prochain chapitre commence ici.',
    'entry.login': 'Entrer dans le monde',
    'entry.hideLogin': 'Revenir au diaporama',
    'entry.username': 'Nom d’utilisateur',
    'entry.password': 'Mot de passe',
    'entry.signingIn': 'Connexion…',
    'entry.account': 'Utilisez votre compte Novus Ordo existant.',
    'entry.ready': 'Votre nation vous attend',
    'entry.readyBody': 'Retrouvez le monde et explorez vos territoires.',
    'entry.client': 'Entrer dans le jeu',
    'entry.admin': 'Administration',
    'entry.founded': 'Une nation est née',
    'entry.foundedBody': 'Votre patrie est prête. À vous d’écrire la suite.',
    'entry.unavailable': 'Le monde n’est pas prêt',
    'entry.resume':
        'Une fondation est déjà en cours. Le nom de votre nation a été retrouvé ; complétez les autres informations.',
    'audio.play': 'Activer la musique',
    'audio.mute': 'Couper la musique',
    'audio.volume': 'Volume de la musique',
    'audio.blocked': 'Cliquer pour écouter',
    'audio.error': 'Musique indisponible',
    'audio.playing': 'Musique en cours',
    'wizard.identity': 'Identité',
    'wizard.leader': 'Direction',
    'wizard.homeland': 'Patrie',
    'wizard.review': 'Fondation',
    'wizard.step': 'Chapitre {number} sur {total}',
    'wizard.progress': 'Progression de la création',
    'wizard.found': 'Fonder votre nation',
    'wizard.submitting': 'Fondation de votre nation…',
    'wizard.leave': 'Quitter la création ? Vos informations non enregistrées seront perdues.',
    'nation.identityTitle': 'Donnez un nom à votre nation',
    'nation.identityBody': 'Les premiers mots de votre histoire.',
    'nation.name': 'Nom de la nation',
    'nation.formalName': 'Nom officiel',
    'nation.flag': 'Drapeau national',
    'nation.namePlaceholder': 'Ex. Union aurélienne',
    'nation.formalPlaceholder': 'Ex. La République d’Aurélie',
    'nation.leaderTitle': 'Présentez votre dirigeant',
    'nation.leaderBody': 'Un visage et un nom pour représenter votre peuple.',
    'nation.leaderName': 'Nom du dirigeant',
    'nation.leaderOffice': 'Titre',
    'nation.portrait': 'Portrait du dirigeant',
    'nation.upload': 'PNG, JPEG ou WebP · 2 Mo maximum · 4096 × 4096 maximum',
    'nation.chooseImage': 'Choisir une image',
    'common.cancel': 'Annuler',
    'nation.designFlag': 'Créer le drapeau',
    'nation.editFlag': 'Modifier le drapeau',
    'nation.useFlag': 'Utiliser ce drapeau',
    'nation.flagEditorFailed': 'Le créateur de drapeau n’a pas pu préparer votre drapeau. Réessayez.',
    'nation.defaultFlag': 'Un drapeau sera attribué si vous n’en choisissez pas.',
    'nation.homelandTitle': 'Choisissez votre point de départ',
    'nation.homelandBody': 'Sélectionnez {count} territoires disponibles et reliés entre eux.',
    'nation.selected': '{selected} / {total} territoires sélectionnés',
    'nation.clear': 'Effacer la sélection',
    'nation.search': 'Rechercher un territoire',
    'nation.available': 'Disponible',
    'nation.chosen': 'Sélectionné',
    'nation.unavailable': 'Indisponible',
    'nation.connected': 'Choisissez un territoire voisin de votre sélection.',
    'nation.noMatches': 'Aucun territoire correspondant.',
    'nation.reviewTitle': 'Les fondations vous appartiennent',
    'nation.reviewBody': 'Vérifiez vos choix avant de fonder votre nation.',
    'nation.edit': 'Modifier : {step}',
    'nation.automatic': 'Attribué par le jeu',
    'nation.none': 'Aucun',
    'nation.territory': 'Territoire',
    'nation.resumeSession': 'Votre session a expiré. Reconnectez-vous pour reprendre votre création.',
    'nation.reconciling': 'Vérification de la fondation de votre nation…',
    'nation.uncertain': 'Le résultat n’a pas pu être confirmé. Vérifiez le serveur avant de réessayer.',
    'nation.recovered':
        'Aucune nation terminée n’a été trouvée. Vos informations sont conservées ; vérifiez-les avant de les envoyer.',
    'errors.validation': 'Vérifiez les champs signalés.',
    'errors.required': 'Ce champ est obligatoire.',
    'errors.length': 'Utilisez entre {min} et {max} caractères.',
    'errors.image': 'Choisissez une image PNG, JPEG ou WebP de 2 Mo maximum.',
    'errors.territories': 'Choisissez {count} territoires disponibles et reliés entre eux.',
    'errors.network': 'Le serveur est injoignable. Vérifiez votre connexion et réessayez.',
    'errors.session': 'Votre session a changé ou a expiré. Reconnectez-vous.',
    'errors.forbidden': 'Vous n’avez pas accès à cette action.',
    'errors.unavailable': 'Le monde est indisponible ou passe au tour suivant. Réessayez dans un instant.',
    'errors.conflict': 'Le monde a changé. Actualisez avant de continuer.',
    'errors.server': 'Le serveur n’a pas pu terminer cette demande.',
    'errors.malformed': 'Le serveur a renvoyé une réponse illisible.',
    'errors.not-found': 'Cette information n’est plus disponible.',
    'errors.abort': 'Demande annulée.',
    'errors.unknown': 'Une erreur est survenue. Réessayez.',
    'errors.notEnough': 'Il n’y a pas assez de territoires de départ libres. Réessayez plus tard.',
    'map.label':
        'Carte du monde. Glissez pour déplacer ; faites défiler pour zoomer. Flèches pour déplacer, plus et moins pour zoomer, Début pour recentrer. Utilisez la liste pour sélectionner.',
    'map.zoom': 'Zoom de la carte',
    'map.zoomIn': 'Agrandir',
    'map.zoomOut': 'Réduire',
    'identity.primary': 'Couleur principale',
    'identity.secondary': 'Couleur secondaire',
    'sound.title': 'Retour sonore',
    'sound.enabled': 'Activer les sons',
    'sound.interaction': 'Sons de survol et de clic',
    'sound.events': 'Sons des unités et des événements',
    'sound.volume': 'Volume sonore',
    'sound.hint': 'Silencieux avant activation. Réglages conservés dans ce navigateur.',
    'production.title': 'Production',
    'production.hint':
        'Définissez un objectif national, puis vérifiez quels établissements territoriaux peuvent contribuer. La main-d’œuvre reste locale à chaque territoire ; le moteur attribue la nourriture, l’entretien et les autres demandes.',
    'production.labor': 'Main-d’œuvre réaffectable dans vos territoires : {value}',
    'production.figures': 'Production {production}/tour · Solde {balance}/tour',
    'production.requested': 'Demande : {requested} · Main-d’œuvre attribuée : {labor}',
    'production.automatic': 'Gérée automatiquement par les règles économiques existantes.',
    'production.quantity': 'Objectif de production par tour',
    'production.quantityHelp':
        'Mettez 0 pour désactiver cette demande. La valeur exacte peut dépasser la production actuelle.',
    'production.productivity': 'Productivité minimale des établissements',
    'production.productivityHelp':
        'Mettez 0 pour accepter tout établissement. Une valeur plus élevée exclut les territoires moins productifs ; elle ne les améliore pas.',
    'production.save': 'Enregistrer : {resource}',
    'production.planOff':
        'Cette demande est désactivée. Enregistrer un objectif de 0 l’annule pour les prochains tours.',
    'production.planReady':
        'Le besoin estimé est de {demand} unités de main-d’œuvre ; les territoires admissibles en affichent actuellement {available} de libres.',
    'production.planNoTerritories':
        'Aucun territoire actuel ne possède un établissement de productivité {productivity} ou plus.',
    'production.planCapacityLimited':
        'L’objectif {target} dépasse le plafond territorial admissible de {ceiling}.',
    'production.planLaborLimited':
        'Le besoin estimé est de {demand} unités de main-d’œuvre, contre {available} actuellement libres dans les territoires admissibles. Les affectations existantes et le recalcul du serveur déterminent le résultat.',
    'production.planDemand': 'Besoin estimé en main-d’œuvre',
    'production.planAvailable': 'Main-d’œuvre locale libre',
    'production.planAllocated': 'Actuellement affectée ici',
    'production.planTerritories': 'Territoires admissibles',
    'production.planCeiling': 'Plafond de production',
    'production.planNote':
        'Aperçu local uniquement. La nourriture, l’entretien et les autres demandes enregistrées peuvent modifier l’attribution finale du serveur.',
    'production.territorySummary': 'Détail territorial — {resource} ({count})',
    'production.territoryRow':
        '{territory} : productivité {productivity} · main-d’œuvre libre {available}/{size} · affectée ici {allocated} · plafond {ceiling} · {state}',
    'production.territoryEligible': 'admissible',
    'production.territoryExcluded': 'exclu par le seuil',
    'production.territoryNone': 'Aucun établissement territorial actuel pour cette ressource.',
    'production.facility':
        '{resource} : capacité {capacity} · productivité {productivity} · travail {allocated} · production {output}',
    'production.private': 'Sélectionnez un de vos territoires pour voir ses installations de production.',
    'map.rotateLeft': 'Tourner la carte de 15° vers la gauche',
    'map.rotateRight': 'Tourner la carte de 15° vers la droite',
    'map.northUp': 'Réinitialiser la rotation (nord en haut)',
    'map.fit': 'Voir le monde',
    'map.loading': 'Chargement de la carte…',
    'map.failed':
        'Certaines images n’ont pas pu être chargées. Les contours et la liste restent disponibles. Rechargez pour réessayer.',
    'economy.workspaceSides': 'Budget et politiques',
    'economy.reviewSave': 'Vérifier et enregistrer',
    'economy.seasonBalance': 'Solde saisonnier',
    'economy.receipts': 'Recettes',
    'economy.spending': 'Dépenses',
    'economy.revenue': 'Recettes',
    'economy.tab_spending': 'Dépenses',
    'economy.tab_revenue': 'Recettes',
    'economy.tab_finance': 'Dette et trésorerie',
    'economy.tab_civilian': 'Économie civile',
    'economy.tab_history': 'Historique / Tendances',
    'economy.tab_territories': 'Territoires',
    'economy.tab_taxation': 'Fiscalité',
    'economy.tab_infrastructure': 'Infrastructures',
    'economy.tab_production': 'Production',
    'economy.tab_food': 'Sécurité alimentaire',
    'economy.tab_institutions': 'Institutions',
    'economy.tab_other': 'Autres politiques',
    'history.industry': 'Besoins industriels',
    'history.industryReport': 'Historique de cette industrie',
    'history.view': 'Vue',
    'history.period': 'Période',
    'history.seasons': '{count} dernières saisons',
    'history.season': 'Saison',
    'history.exactValues': 'Observations exactes',
    'history.enlargeChart': 'Agrandir {title}',
    'history.keyboard': 'Sélectionnez une saison avec les flèches, Début ou Fin',
    'history.policyChanged': 'Politiques modifiées',
    'history.empty': 'Aucune saison terminée enregistrée.',
    'history.loading': 'Chargement de l’historique…',
    'history.failed': 'Historique indisponible. Vos modifications sont conservées.',
    'history.stale': 'Actualisation impossible; observations précédentes affichées.',
    'history.retry': 'Réessayer',
    'history.national': 'Budget national',
    'history.currency': 'Crédits',
    'history.units': 'Unités',
    'history.budget': 'Recettes et dépenses',
    'history.cash': 'Trésorerie et dette',
    'history.spending': 'Destination des dépenses',
    'history.supply': 'Produisons-nous assez ?',
    'history.development': 'L’industrie se développe-t-elle ?',
    'history.balance': 'Solde saisonnier',
    'history.receipts': 'Recettes',
    'history.treasury': 'Trésorerie finale',
    'history.debt': 'Dette finale',
    'history.military': 'Militaire',
    'history.purchases': 'Achats publics',
    'history.support': 'Soutien aux revenus',
    'history.infrastructure': 'Infrastructures',
    'history.interest': 'Intérêts payés',
    'history.other': 'Autres dépenses',
    'history.production': 'Production nationale',
    'history.civilian': 'Besoins civils',
    'history.usable': 'Capacité utilisable cette saison',
    'history.growth': 'Nouvelle capacité productive',
    'history.publicInvestment': 'Investissement public',
    'history.privateInvestment': 'Investissement privé',
    'history.investment': 'Dépenses d’investissement',
    'history.capacity': 'Capacité installée',
    'history.nationalHelp':
        'Résultats saisonniers enregistrés. Les emprunts et remboursements du capital sont exclus des recettes et dépenses. Les repères politiques indiquent une date, pas une causalité.',
    'history.supplyHelp':
        'La production nationale sert d’abord les besoins civils et les intrants. La capacité utilisable est un plafond; les intrants et les travailleurs peuvent limiter la production réelle. Les réserves publiques sont distinctes.',
    'history.developmentHelp':
        'L’investissement est une dépense réelle; la capacité est physique. Les nouveaux équipements servent la saison suivante. Une conquête peut modifier la capacité sans construction. Une lacune indique une observation non enregistrée.',
    'history.industrySelector': 'Industrie',
    'finance.reserve': 'Réserve pour remboursement automatique',
    'finance.reserveHelp':
        'Cette réserve protège les fonds du remboursement automatique des dettes antérieures, mais pas des dépenses ordinaires. La politique prend effet la saison suivante. Un remboursement volontaire peut descendre sous cette cible.',
    'finance.amount': 'Montant du remboursement (crédits)',
    'finance.review': 'Rembourser maintenant…',
    'finance.confirm': 'Confirmer le remboursement',
    'finance.cancel': 'Annuler',
    'finance.preview':
        'Après remboursement : trésorerie non engagée {cash}; dette {debt}. Cette action est immédiate.',
    'finance.invalid': 'Saisissez un montant positif limité à la dette et aux fonds non engagés.',
    'economy.unsavedShort': 'Modifications non enregistrées.',
    'economy.pendingShort': 'Modifications prévues pour la prochaine saison.',
    'economy.draftActive': 'Prévision provisoire',
};
