<?php
require __DIR__.'/isolated-app.php';
set_exception_handler(function (Throwable $error) { fwrite(STDERR, (string) $error . PHP_EOL); exit(1); });
require __DIR__.'/generated-map-fixture.php';
use App\Domain\{DivisionType,DeploymentCommand};
use App\Domain\Resources\Quantity as Q;
use App\Services\Resources\{ResourceCatalogue as Catalogue,ResourceLedger};
use App\Models\{Game,User,NewNation,Territory,NationResourceStockpile,DivisionDetail};
use App\Services\{GameMutation,NationGrantService,PlayerWorkspace};
use Illuminate\Support\Facades\{DB,Hash,Artisan};
$count=0;
$check=function($ok,$message)use(&$count){++$count;if(!$ok)throw new RuntimeException($message);};
$reject=function($work,$message)use($check){try{$work();}catch(\Throwable $e){$check(true,$message);return;}$check(false,$message);};
Artisan::call('migrate',['--force'=>true]);
$doc=json_decode(file_get_contents(database_path('resource-templates/foundation.json')),true);
$doc['name']='Resource contract fixture';
// These catalogue/accounting fixtures retain terrain yields; positive geographic output has dedicated resolver tests.
foreach($doc['resources'] as &$definition)if(isset($definition['rules']['production.territorial_labor']))$definition['rules']['production.territorial_labor']['geographic']=false;unset($definition);
$check(Q::add('9999999999999.123456','0.000001')==='9999999999999.123457','Large exact addition');
$check(Q::sub('0.300000','0.100000')==='0.200000','Exact subtraction');
$reject(fn()=>Q::parse('1.0000001'),'Reject excess precision');
$reject(fn()=>Q::parse(1.2),'API quantities are decimal strings');
$reject(fn()=>Q::parse('-1'),'Reject negative quantities');
$invalid=$doc;$invalid['units']['Armored']['deployment']['unknown']='1';
$before=DB::table('resource_sets')->count();$reject(fn()=>Catalogue::createTemplate($invalid),'Unknown costs fail');
$check(DB::table('resource_sets')->count()===$before,'Invalid import is atomic');
$invalid=$doc;unset($invalid['units']['Infantry']['operation']);$reject(fn()=>Catalogue::createTemplate($invalid),'Missing phase is not silently free');
$invalid=$doc;$invalid['resources'][0]['rules']=['production.territorial_labor'=>$doc['resources'][2]['rules']['production.territorial_labor']];$reject(fn()=>Catalogue::createTemplate($invalid),'Currency cannot produce labor money');
$template=Catalogue::createTemplate($doc);
$makeGame=fn($tid)=>Game::createNew(generatedMapFixture(),resourceTemplateId:$tid);
$game=$makeGame($template->set['id']);$other=$makeGame($template->set['id']);
$cat=Catalogue::forGame($game);$otherCat=Catalogue::forGame($other);
$check($cat->get('food')['id']!==$otherCat->get('food')['id'],'Games own separate resources');
$reject(fn()=>$cat->key($otherCat->get('food')['id']),'Foreign reference rejected');
$changed=$template->document();$changed['resources'][0]['starting_quantity']='99';
Catalogue::edit($template->set['id'],1,$changed);
$check(Catalogue::load($cat->set['id'])->get('money')['starting_quantity']==='20.000000','Template changes do not leak');
$reject(fn()=>Catalogue::edit($template->set['id'],1,$changed),'Stale catalogue edit rejected');
$found=function(Game $game,string $prefix='resource'){
    $eligible=$game->freeSuitableTerritoriesInTurn()->get()->keyBy('id');$edges=Territory::getTerritoryConnections($game);$homes=[];
    foreach($eligible as $start){$queue=[$start->id];$seen=[];while($queue&&count($seen)<5){$id=array_shift($queue);if(isset($seen[$id]))continue;$seen[$id]=true;foreach($edges[$id] as $edge)if($edge->isConnectedByLand&&$eligible->has($edge->connectedTerritoryId)&&!isset($seen[$edge->connectedTerritoryId]))$queue[]=$edge->connectedTerritoryId;}if(count($seen)===5){$homes=array_keys($seen);break;}}
    if(count($homes)!==5)throw new RuntimeException('No connected homeland');
    $user=new User();$user->name=$prefix.'-'.bin2hex(random_bytes(4));$user->email=$user->name.'@example.test';$user->password=Hash::make('fixture-password');$user->is_admin=true;$user->save();
    return [NewNation::create($game,$user,$user->name)->finishSetup($homes,'Test leader'),$homes,$user];
};
[$nation,$homes,$user]=$found($game);[$recipient]=$found($game,'recipient');
$d=$nation->getDetail();$ledger=app(ResourceLedger::class);$snapshot=app(PlayerWorkspace::class)->export($nation);
$check($d->getStockpiledQuantity('money')==='20.000000','Starting treasury');
$check(Q::cmp($snapshot['budget']->production['money'],'0')===0,'Currency is not produced by labor');
$check(count($snapshot['definitions']['resources'])===6,'Six current resources');
$check(!NationResourceStockpile::where('nation_id',$nation->id)->where('resource_id',$cat->get('recruitment')['id'])->exists(),'No capacity stock');
$grant=app(NationGrantService::class);$cashA=$d->getStockpiledQuantity('money');$cashB=$recipient->getDetail()->getStockpiledQuantity('money');
$check(app(GameMutation::class)->run($game,fn()=>$grant->transfer($nation,$recipient,'money','0.123456')),'Exact fractional transfer');
$check(Q::add($nation->fresh()->getDetail()->getStockpiledQuantity('money'),$recipient->fresh()->getDetail()->getStockpiledQuantity('money'))===Q::add($cashA,$cashB),'Grant conservation');
$reject(fn()=>app(GameMutation::class)->run($game,fn()=>$grant->transfer($nation,$recipient,'recruitment','1')),'Cannot grant capacity');
$turn=$game->getCurrentTurn();$d=$nation->fresh()->getDetail();$capacity=$ledger->preview($d)['rows']['recruitment']['capacity'];
$plans=$ledger->plans($d);$plans['ore']['quantity']='0.500001';$plans['ore']['spending_limit']='10';
app(\App\Services\Policies\PolicyService::class)->submit($nation,$turn,$snapshot['policies']['edit_counter'],[],$plans);
$beforeRows=$ledger->preview($d);$stored=DB::table('nation_resource_acquisitions')->where('nation_id',$nation->id)->get()->toJson();
$preview=$ledger->preview($d,[...$plans,'ore'=>['quantity'=>'1.2','spending_limit'=>'10','priority'=>100]]);
$check(DB::table('nation_resource_acquisitions')->where('nation_id',$nation->id)->get()->toJson()===$stored,'Preview does not write');
$check($preview['rows']['ore']['acquisition']['acquisition_requested']==='1.200000','Preview applies draft');
app(GameMutation::class)->run($game,fn()=>$nation->deploy(new DeploymentCommand($homes[0],DivisionType::Armored)));
$expected=$ledger->preview($nation->fresh()->getDetail());
$check($expected['rows']['recruitment']['available']===Q::sub($capacity,'1'),'Pending deployment reserves once');
$check($expected['rows']['ore']['commands']==='5.000000','Configured unit cost');
$check($grant->available($nation)['money']===Q::sub(Q::sub($cashA,'0.123456'),'5'),'Grants preserve committed treasury');
$definitionCount=DB::table('resource_definitions')->count();
$next=$game->fresh()->tryNextTurn($turn);$nd=$nation->fresh()->getDetail($next);
foreach($cat->resources as $key=>$r)if($r['kind']==='stock')$check($nd->getStockpiledQuantity($key)===$expected['rows'][$key]['closing'],"Preview matches settlement: $key");
$check($ledger->preview($nd)['rows']['recruitment']['occupied']==='1.000000','Active division occupies capacity once');
$check(DB::table('resource_definitions')->count()===$definitionCount,'No definition copies per turn');
$check($nd->resource_report['ore']===json_decode(json_encode($expected['rows']['ore']['acquisition']),true),'Resolved physical report stored');
$resolved=$nd->getStockpiles()->map(fn($s)=>$s->available_quantity)->all();
$game->fresh()->rollbackLastTurn($next->id);
$check($nation->fresh()->getDetail()->getStockpiledQuantity('money')===Q::sub($cashA,'0.123456'),'Rollback restores treasury');
$retry=$game->fresh()->tryNextTurn($turn);
$check($nation->fresh()->getDetail($retry)->getStockpiles()->map(fn($s)=>$s->available_quantity)->all()===$resolved,'Retry reproduces balances');
// Same engine with fewer goods and renamed semantic resources; all unit maps explicit.
$small=$doc;$small['name']='Reduced roles';$small['resources']=array_slice($small['resources'],0,3);
$renames=['money'=>'credits','food'=>'nutrition','recruitment'=>'personnel'];
foreach($small['resources'] as &$r)$r['key']=$renames[$r['key']];unset($r);
foreach($small['units'] as &$phases)foreach($phases as &$costs){$out=[];foreach($costs as $k=>$q)if(isset($renames[$k]))$out[$renames[$k]]=$q;$costs=$out;}unset($phases,$costs);
$smallGame=$makeGame(Catalogue::createTemplate($small)->set['id']);[$smallNation]=$found($smallGame,'small');
$smallData=app(PlayerWorkspace::class)->export($smallNation);$check($smallData['definitions']['roles']['treasury']==='credits'&&count($smallData['definitions']['resources'])===3,'Renamed reduced catalogue works');
$smallNext=$smallGame->fresh()->tryNextTurn($smallGame->getCurrentTurn());$check(Q::cmp($smallNation->fresh()->getDetail($smallNext)->getStockpiledQuantity('credits'),'0')>=0,'Reduced catalogue settles');
// A new good needs no engine switch or source edit naming it.
$extra=$doc;$extra['name']='Synthetic resource fixture';$r=$doc['resources'][3];$r['key']='test_good';$r['rules']['production.territorial_labor']['geographic']=false;$r['labels']=['en'=>'Test good','fr'=>'Bien de test'];$r['icon_key']=null;$r['starting_quantity']='2';$extra['resources'][]=$r;
$extra['units']['Infantry']['deployment']['test_good']='0.123456';
$extraGame=$makeGame(Catalogue::createTemplate($extra)->set['id']);[$extraNation,$extraHomes,$extraUser]=$found($extraGame,'extra');
$extraCat=Catalogue::forGame($extraGame);$extraD=$extraNation->getDetail();
$check(isset($ledger->preview($extraD)['rows']['test_good']),'Synthetic good participates in preview');
app(GameMutation::class)->run($extraGame,fn()=>$extraNation->deploy(new DeploymentCommand($extraHomes[0],DivisionType::Infantry)));
$extraPreview=$ledger->preview($extraNation->fresh()->getDetail());$extraNext=$extraGame->fresh()->tryNextTurn($extraGame->getCurrentTurn());
$check($extraNation->fresh()->getDetail($extraNext)->getStockpiledQuantity('test_good')===$extraPreview['rows']['test_good']['closing'],'Synthetic deployment debit settles');
$check($extraNation->fresh()->getDetail($extraNext)->getStockpiledQuantity('test_good')==='1.876544','Six-decimal cost retained');
$extraGame=$extraGame->fresh();$extraGame->policy_testing_enabled=true;$extraGame->save();$changed=$extraCat->document();
foreach($changed['resources'] as &$r)if($r['key']==='test_good')$r['rules']['production.territorial_labor']['yields']['Forest']='2.5';unset($r);
$updated=Catalogue::edit($extraCat->set['id'],1,$changed);$check($updated->set['edit_counter']===2,'Test-game edit updates counter');
$check(Catalogue::load($otherCat->set['id'])->get('money')['starting_quantity']==='20.000000','Game edits isolated');
file_put_contents(getenv('NO7_ENTRY_TEST_ROOT').'/resource-fixture.json',json_encode(['game_id'=>$extraGame->id,'nation_id'=>$extraNation->id,'user'=>$extraUser->name]));
file_put_contents(getenv('NO7_ENTRY_TEST_ROOT').'/diplomacy-fixture.json',json_encode(['game_id'=>$game->id,'nations'=>[$nation->id,$recipient->id]]));
echo "$count resource checks passed.\n";
