// Generated by php8.3 artisan client:generate. Do not edit. No player data.
export const endpoints = {
    "applyProductionPlan": {
        "method": "POST",
        "path": "/nation/production-plan"
    },
    "cancelDeployments": {
        "method": "POST",
        "path": "/nation/deployments/cancel-deployment-requests"
    },
    "cancelNationTreaty": {
        "method": "POST",
        "path": "/nation/diplomacy/cancel-treaty"
    },
    "cancelOrders": {
        "method": "POST",
        "path": "/nation/divisions:cancel-orders"
    },
    "createNation": {
        "method": "POST",
        "path": "/nation"
    },
    "deploy": {
        "method": "POST",
        "path": "/nation/territories/deployments"
    },
    "getAllDeployments": {
        "method": "GET",
        "path": "/nation/deployments"
    },
    "getAllTerritories": {
        "method": "GET",
        "path": "/territories"
    },
    "getAllTerritoriesBaseInfo": {
        "method": "GET",
        "path": "/territories/base-infos"
    },
    "getAllTerritoriesBaseInfoRef": {
        "method": "GET",
        "path": "/territories/base-infos/ref"
    },
    "getAllTerritoriesSuitableAsHomeIds": {
        "method": "GET",
        "path": "/territories/suitable-as-home-ids"
    },
    "getAllTerritoriesTurnInfo": {
        "method": "GET",
        "path": "/territories/turn-infos"
    },
    "getAssetInfo": {
        "method": "GET",
        "path": "/assets/{encodedUri}",
        "doubleEncodedParams": [
            "encodedUri"
        ]
    },
    "getClientGameplay": {
        "method": "GET",
        "path": "/client/gameplay"
    },
    "getDiplomacyInbox": {
        "method": "GET",
        "path": "/nation/diplomacy"
    },
    "getEconomicHistory": {
        "method": "GET",
        "path": "/nation/economic-history"
    },
    "getEntrySession": {
        "method": "GET",
        "path": "/client/session"
    },
    "getEntrySetup": {
        "method": "GET",
        "path": "/client/setup"
    },
    "getGameIdentities": {
        "method": "GET",
        "path": "/game/identities"
    },
    "getGameInfo": {
        "method": "GET",
        "path": "/game"
    },
    "getGameMap": {
        "method": "GET",
        "path": "/game/map"
    },
    "getGameNews": {
        "method": "GET",
        "path": "/game/news"
    },
    "getGameRankingHistory": {
        "method": "GET",
        "path": "/game/ranking-history"
    },
    "getGameRankings": {
        "method": "GET",
        "path": "/game/rankings"
    },
    "getGameReadyStatus": {
        "method": "GET",
        "path": "/game/ready-status"
    },
    "getGameVictoryStatus": {
        "method": "GET",
        "path": "/game/victory-status"
    },
    "getGames": {
        "method": "GET",
        "path": "/games"
    },
    "getNationBattleLogs": {
        "method": "GET",
        "path": "/nation/battle-logs"
    },
    "getNationBudget": {
        "method": "GET",
        "path": "/nation/budget"
    },
    "getNationConversation": {
        "method": "GET",
        "path": "/nation/diplomacy/conversations/{nationId}"
    },
    "getNationDefenseCoverage": {
        "method": "GET",
        "path": "/nation/defense-coverage"
    },
    "getNationDivision": {
        "method": "GET",
        "path": "/nation/divisions/{divisionId}"
    },
    "getNationDivisions": {
        "method": "GET",
        "path": "/nation/divisions"
    },
    "getNationInfo": {
        "method": "GET",
        "path": "/nation"
    },
    "getNationTerritoriesTurnInfo": {
        "method": "GET",
        "path": "/nation/territories/turn-infos"
    },
    "getPublicNationInfo": {
        "method": "GET",
        "path": "/nations/{nationId}"
    },
    "getTerritoryBaseInfo": {
        "method": "GET",
        "path": "/territories/{territoryId}/base-info"
    },
    "getTerritoryDeployments": {
        "method": "GET",
        "path": "/nation/territories/{territoryId}/deployments"
    },
    "getTerritoryTurnInfo": {
        "method": "GET",
        "path": "/territories/{territoryId}/turn-info"
    },
    "getUserInfo": {
        "method": "GET",
        "path": "/user"
    },
    "getUserNationSetupStatus": {
        "method": "GET",
        "path": "/user/nation-setup-status"
    },
    "loginUser": {
        "method": "POST",
        "path": "/login-user"
    },
    "previewPolicies": {
        "method": "POST",
        "path": "/nation/policies/preview"
    },
    "previewProductionPlan": {
        "method": "POST",
        "path": "/nation/production-preview"
    },
    "proposeNationOffer": {
        "method": "POST",
        "path": "/nation/diplomacy/offers"
    },
    "readNationMessages": {
        "method": "POST",
        "path": "/nation/diplomacy/read"
    },
    "readyForNextTurn": {
        "method": "POST",
        "path": "/ready-for-next-turn"
    },
    "repayDebt": {
        "method": "POST",
        "path": "/nation/finance/repay"
    },
    "respondNationOffer": {
        "method": "POST",
        "path": "/nation/diplomacy/offers/respond"
    },
    "savePendingPolicies": {
        "method": "PUT",
        "path": "/nation/policies/pending"
    },
    "selectHomeTerritories": {
        "method": "POST",
        "path": "/nation:select-home-territories"
    },
    "sendDisbandOrders": {
        "method": "POST",
        "path": "/nation/divisions/disband-orders"
    },
    "sendGuardOrders": {
        "method": "POST",
        "path": "/nation/divisions/guard-orders"
    },
    "sendMoveOrders": {
        "method": "POST",
        "path": "/nation/divisions/move-orders"
    },
    "sendNationMessage": {
        "method": "POST",
        "path": "/nation/diplomacy/messages"
    },
    "storeNation": {
        "method": "POST",
        "path": "/client/setup/nation"
    }
};
