// Supported analysis descriptors. Availability is resolved against authoritative payloads.
export const groups = [
    ['land', 'world', 'Land & climate', 'Terres et climat'],
    ['water', 'Oil', 'Water & coasts', 'Eau et côtes'],
    ['resources', 'Ore', 'Resources', 'Ressources'],
    ['economy', 'economic', 'Population & economy', 'Population et économie'],
    ['politics', 'nation', 'Politics', 'Politique'],
    ['military', 'military', 'Military', 'Militaire'],
    ['display', 'layers', 'Display', 'Affichage'],
];

// Geography belongs to microcells; territory data is supplied by the current game snapshot.
const entry = (id, group, en, fr, scale = 'adaptive', source = 'geography', unit = '') => ({
    id,
    group,
    en,
    fr,
    scale,
    source,
    unit,
});
export const catalogue = [
    entry('terrain', 'land', 'Natural landscape', 'Paysage naturel', 'none'),
    entry('elevation', 'land', 'Elevation', 'Altitude', 'adaptive', 'geography', 'm'),
    entry('slope', 'land', 'Relief / slope', 'Relief / pente', 'adaptive', 'geography', 'index'),
    entry('biome', 'land', 'Biomes', 'Biomes', 'category'),
    entry('temperature', 'land', 'Temperature', 'Température', 'index'),
    entry('rainfall', 'land', 'Rainfall', 'Précipitations', 'index'),
    entry('moisture', 'land', 'Moisture', 'Humidité', 'index'),
    entry('snow', 'land', 'Snow & ice', 'Neige et glace', 'category'),
    entry('depth', 'water', 'Water depth', 'Profondeur de l’eau', 'adaptive', 'geography', 'm'),
    entry('basin', 'water', 'Drainage basins', 'Bassins versants', 'category'),
    entry('flow', 'water', 'Drainage flow', 'Écoulement', 'adaptive', 'geography', 'index'),
    entry('coast', 'water', 'Shore accessibility', 'Accessibilité côtière', 'shore'),
    entry('exposure', 'water', 'Coastal exposure', 'Exposition côtière', 'shore'),
    entry('bays', 'water', 'Detected bays', 'Baies détectées', 'category'),
    entry('fertility', 'resources', 'Agricultural potential', 'Potentiel agricole', 'index'),
    entry('forest', 'resources', 'Forest cover', 'Couvert forestier', 'category'),
    entry('deposits', 'resources', 'Resource distribution', 'Répartition des ressources', 'adaptive'),
    entry(
        'potential',
        'resources',
        'Geographic production potential',
        'Plafond géographique de production',
        'adaptive',
        'geography',
        '/season',
    ),
    entry('population', 'economy', 'Population', 'Population', 'adaptive', 'territory', 'people'),
    entry(
        'density',
        'economy',
        'Population density',
        'Densité de population',
        'adaptive',
        'territory',
        '/land region',
    ),
    entry('infrastructure', 'economy', 'Infrastructure', 'Infrastructures', 'percent', 'territory'),
    entry(
        'capacity',
        'economy',
        'Productive capacity',
        'Capacité productive',
        'adaptive',
        'territory',
        'index',
    ),
    entry(
        'income',
        'economy',
        'Last-season civilian income',
        'Revenu civil — saison passée',
        'adaptive',
        'territory',
        'credits/season',
    ),
    entry(
        'netIncome',
        'economy',
        'Last-season net income per resident',
        'Revenu net par habitant — saison passée',
        'adaptive',
        'territory',
        'credits/person/season',
    ),
    entry('unrest', 'economy', 'Unrest', 'Troubles', 'percent', 'territory'),
    entry('informal', 'economy', 'Informal activity', 'Économie informelle', 'percent', 'territory'),
    entry(
        'production',
        'economy',
        'Planned resource output',
        'Production prévue',
        'adaptive',
        'territory',
        '/season',
    ),
    entry(
        'workers',
        'economy',
        'Unallocated workers',
        'Travailleurs non affectés',
        'adaptive',
        'territory',
        'people',
    ),
    entry('ownership', 'politics', 'National ownership', 'Souveraineté nationale', 'category', 'territory'),
    entry('loyalty', 'politics', 'Loyalty', 'Loyauté', 'percent', 'territory'),
    entry('defense', 'military', 'Defense strength', 'Force défensive', 'adaptive', 'territory', 'points'),
    entry(
        'guard',
        'military',
        'Guard contribution',
        'Contribution de la garde',
        'adaptive',
        'territory',
        'points',
    ),
    entry(
        'forces',
        'military',
        'Division concentration',
        'Concentration des divisions',
        'adaptive',
        'territory',
        'divisions',
    ),
];
export const resourceLayers = new Set(['deposits', 'potential', 'production']);

export const gameCatalogue = catalogue.filter((l) => !['basin', 'flow', 'ownership'].includes(l.id));
